/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinEntityFactory.cpp
 *
 * Auto-tag stamping at creation: derives a gameplay tag from the asset name
 * via the auto-tag generator, refuses creation on collision, and writes the
 * resulting tag onto a freshly-added FSeinIdentityComponent entry in the
 * entity bridge's ComponentData array. Designer can edit / remove later.
 */

#include "Factories/SeinEntityFactory.h"
#include "SeinARTSEditorModule.h"
#include "Settings/PluginSettings.h"
#include "Dialogs/SSeinClassPickerDialog.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Actor/SeinActor.h"
#include "Actor/SeinActorBlueprint.h"
#include "Actor/SeinEntityBridgeComponent.h"
#include "Components/SeinIdentityComponent.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Misc/MessageDialog.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

USeinEntityFactory::USeinEntityFactory()
{
	bCreateNew = true;
	bEditAfterNew = true;
	SupportedClass = USeinActorBlueprint::StaticClass();
	ParentClass = ASeinActor::StaticClass();
	BlueprintType = BPTYPE_Normal;
}

UObject* USeinEntityFactory::FactoryCreateNew(UClass* Class, UObject* InParent, FName Name, EObjectFlags Flags, UObject* Context, FFeedbackContext* Warn, FName CallingContext)
{
	// Pre-creation collision check: derive what the tag WOULD be, then refuse
	// if some other SeinARTS asset already owns it. Doing this before the
	// CreateBlueprint call means we abort cleanly with no orphan asset.
	const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>();
	const FGameplayTag DerivedTag = SeinAutoTag::DeriveTagFromAssetName(Name, Settings);
	if (DerivedTag.IsValid())
	{
		const FString Collider = SeinAutoTag::FindCollidingAssetPath(DerivedTag);
		if (!Collider.IsEmpty())
		{
			FMessageDialog::Open(EAppMsgType::Ok, FText::Format(
				LOCTEXT("EntityTagCollisionMsg",
					"Cannot create '{0}' — its auto-generated tag '{1}' is already used by:\n\n{2}\n\nRename your new asset (or use a layer-disambiguator like '{0}_Variant') to produce a different tag."),
				FText::FromName(Name),
				FText::FromString(DerivedTag.ToString()),
				FText::FromString(Collider)));
			return nullptr;
		}
	}

	UBlueprint* NewBP = Cast<UBlueprint>(FKismetEditorUtilities::CreateBlueprint(
		ParentClass, InParent, Name, BlueprintType,
		USeinActorBlueprint::StaticClass(),
		UBlueprintGeneratedClass::StaticClass(),
		CallingContext));

	if (!NewBP || !DerivedTag.IsValid())
	{
		return NewBP;  // either creation failed or no tag to stamp (master toggle off etc.)
	}

	// Stamp the derived tag onto a fresh FSeinIdentityComponent entry in the
	// entity bridge's ComponentData. ASeinActor's constructor created the
	// bridge subobject; we just append to its data array.
	if (NewBP->GeneratedClass)
	{
		ASeinActor* CDO = Cast<ASeinActor>(NewBP->GeneratedClass->GetDefaultObject());
		if (CDO)
		{
			TArray<USeinEntityBridgeComponent*> Bridges;
			CDO->GetComponents<USeinEntityBridgeComponent>(Bridges);
			if (Bridges.Num() > 0 && Bridges[0])
			{
				FSeinIdentityComponent Identity;
				Identity.IdentityTag = DerivedTag;
				Identity.bAutoGeneratedTag = true;

				FInstancedStruct Entry;
				Entry.InitializeAs<FSeinIdentityComponent>(Identity);
				Bridges[0]->ComponentData.Add(Entry);

				SeinAutoTag::RegisterTagIfNeeded(DerivedTag);
				FBlueprintEditorUtils::MarkBlueprintAsModified(NewBP);
			}
		}
	}

	return NewBP;
}

bool USeinEntityFactory::ConfigureProperties()
{
	UClass* ChosenClass = SSeinClassPickerDialog::OpenDialog(
		LOCTEXT("PickEntityParentClass", "Pick Parent Class for Entity"),
		ASeinActor::StaticClass(),
		LOCTEXT("GenericEntity", "Generic Entity"),
		LOCTEXT("GenericEntityTip", "Create a bare Blueprint subclass of ASeinActor. The Entity Bridge component is auto-attached by the parent class — author sim components on its ComponentData array. Auto-tag generation: prefix the asset name with SBP_ (generic), SU_ (unit), or SR_ (research) so the framework can stamp a tag automatically.")
	);

	if (!ChosenClass) return false;
	ParentClass = ChosenClass;
	return true;
}

FText USeinEntityFactory::GetDisplayName() const
{
	return LOCTEXT("SeinEntityFactoryDisplayName", "SeinARTS Entity Blueprint");
}

uint32 USeinEntityFactory::GetMenuCategories() const
{
	uint32 Categories = FSeinARTSEditorModule::GetAssetCategoryBit();
	if (GetDefault<USeinARTSCoreSettings>()->bShowEntityInBasicCategory)
	{
		Categories |= EAssetTypeCategories::Basic;
	}
	return Categories;
}

#undef LOCTEXT_NAMESPACE
