/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file:		SeinARTSEditorModule.cpp
 * @date:		3/27/2026
 * @author:		RJ Macklem
 * @brief:		Implementation of the SeinARTS editor module.
 */

#include "SeinARTSEditorModule.h"
#include "SeinARTSEditorStyle.h"
#include "SeinAssetTypeActions.h"
#include "AssetToolsModule.h"
#include "IAssetTools.h"
#include "AssetDefinitionRegistry.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "Definitions/AssetDefinition_SeinWidgetBlueprint.h"
#include "ThumbnailRendering/ThumbnailManager.h"
#include "Thumbnails/SeinBlueprintThumbnailRenderer.h"
#include "Thumbnails/SeinStructThumbnailRenderer.h"
#include "Validators/SeinAbilityContinuationAnalysis.h"
#include "Validators/SeinAbilityContinuationValidator.h"
#include "Validators/SeinBalanceProfileValidator.h"
#include "Validators/SeinCanonicalStateRecipeDeterminismValidator.h"
#include "Validators/SeinCommandDeterminismValidator.h"
#include "Validators/SeinDeterministicStructValidator.h"
#include "Validators/SeinFormationDeterminismValidator.h"
#include "Validators/SeinMovementClassValidator.h"
#include "Validators/SeinMovementDeterminismValidator.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Util/SeinSimulationContentEditorGuards.h"
#include "Util/SeinSimulationContentManifestBuilder.h"
#include "Settings/PluginSettings.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Actor/SeinActor.h"
#include "Components/SeinIdentityComponent.h"
#include "StructUtils/UserDefinedStruct.h"
#include "StructUtils/InstancedStruct.h"
#include "Engine/Blueprint.h"
#include "Actor/SeinActorBlueprint.h"
#include "Abilities/SeinAbilityBlueprint.h"
#include "Effects/SeinEffectBlueprint.h"
#include "Formations/SeinFormationBlueprint.h"
#include "Widgets/SeinWidgetBlueprint.h"
#include "K2Node_AsyncAction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "EdGraphUtilities.h"
#include "Graph/SeinPinFactory.h"
#include "PropertyEditorModule.h"
#include "InstancedStructDetails.h"
#include "Details/SeinFixedPointDetails.h"
#include "Details/SeinInstancedStructDetails.h"
#include "Details/SeinAutoTagDetails.h"
#include "Details/SeinARTSCoreSettingsDetails.h"
#include "Details/SeinMovementModeDetails.h"
#include "Details/SeinBalanceProfileDetails.h"
#include "Balance/SeinBalanceProfile.h"
#include "Details/SeinSquadSlotDetails.h"
// Volume details panels live in their owning system modules (SeinARTSNavigation
// + SeinARTSFogOfWar), not here — preserves the "each subsystem self-contained"
// pattern. Each module registers its own customization at StartupModule under
// `#if WITH_EDITOR`, so the editor module never imports their headers.
#include "Details/SeinVisionStampDetails.h"
#include "Details/SeinCollisionResponseDetails.h"
#include "Details/SeinCollisionObjectTypeDetails.h"
#include "Visualizers/SeinEntityComponentVisualizer.h"
#include "Actor/SeinEntityComponent.h"
#include "Editor.h"
#include "EditorValidatorSubsystem.h"
#include "UnrealEdGlobals.h"
#include "Editor/UnrealEdEngine.h"
#include "CoreGlobals.h"
#include "UObject/UObjectBase.h"
#include "Features/IModularFeatures.h"
#include "HAL/IConsoleManager.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAutoTag, Log, All);
DEFINE_LOG_CATEGORY_STATIC(LogSeinARTSEditor, Log, All);

namespace SeinAutoTagRenameHandler
{
	/** Inspect a freshly-renamed asset; if it's a SeinARTS taggable BP with
	 *  `bAutoGeneratedTag = true`, regenerate its tag from the new name.
	 *  Collisions soft-fail (warning log, tag left untouched) because UE's
	 *  rename pipeline is post-fire — we can't veto from here. Designer
	 *  notices via the log + can fix manually via "Reset to Auto" after
	 *  resolving the name collision. */
	static void OnAssetRenamed(const FAssetData& Asset, const FString& OldObjectPath)
	{
		const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>();
		if (!Settings || !Settings->bEnableAutoTagGeneration) return;

		UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
		if (!BP || !BP->GeneratedClass) return;
		UObject* CDO = BP->GeneratedClass->GetDefaultObject();
		if (!CDO) return;

		const FName NewName = Asset.AssetName;
		const FGameplayTag NewTag = SeinAutoTag::DeriveTagFromAssetName(NewName, Settings);
		if (!NewTag.IsValid()) return;

		// Lambda — returns true if the tag was updated (BP needs marking dirty).
		auto UpdateAndCheckCollision = [&](FGameplayTag& OutTag, bool& OutAutoFlag) -> bool
		{
			if (!OutAutoFlag) return false;  // designer owns this tag — don't touch
			if (OutTag == NewTag) return false;  // already correct

			const FString Collider = SeinAutoTag::FindCollidingAssetPath(NewTag, Asset.PackageName.ToString());
			if (!Collider.IsEmpty())
			{
				UE_LOG(LogSeinAutoTag, Warning,
					TEXT("Asset '%s' renamed but new auto-tag '%s' collides with '%s'. Tag left as '%s' — fix by renaming again or click 'Reset to Auto' in the BP details after resolving the collision."),
					*Asset.PackageName.ToString(), *NewTag.ToString(), *Collider, *OutTag.ToString());
				return false;
			}

			OutTag = NewTag;
			SeinAutoTag::RegisterTagIfNeeded(NewTag);
			return true;
		};

		bool bDirty = false;
		if (USeinAbility* Ability = Cast<USeinAbility>(CDO))
		{
			bDirty = UpdateAndCheckCollision(Ability->AbilityTag, Ability->bAutoGeneratedTag);
		}
		else if (USeinEffect* Effect = Cast<USeinEffect>(CDO))
		{
			bDirty = UpdateAndCheckCollision(Effect->EffectTag, Effect->bAutoGeneratedTag);
		}
		else if (ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
		{
			// Walk the entity bridge's ComponentData for an FSeinIdentityComponent
			// entry. Modifying the struct in-place mutates the bridge's stored
			// FInstancedStruct.
			TArray<USeinEntityComponent*> Bridges;
			SeinActor->GetComponents<USeinEntityComponent>(Bridges);
			for (USeinEntityComponent* Bridge : Bridges)
			{
				if (!Bridge) continue;
				for (FInstancedStruct& Entry : Bridge->ComponentData)
				{
					if (!Entry.IsValid()) continue;
					if (Entry.GetScriptStruct() != FSeinIdentityComponent::StaticStruct()) continue;
					FSeinIdentityComponent& Identity = Entry.GetMutable<FSeinIdentityComponent>();
					if (UpdateAndCheckCollision(Identity.IdentityTag, Identity.bAutoGeneratedTag))
					{
						bDirty = true;
					}
				}
			}
		}

		if (bDirty)
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(BP);
			UE_LOG(LogSeinAutoTag, Log,
				TEXT("Auto-tag updated for renamed asset '%s' → '%s'"),
				*Asset.PackageName.ToString(), *NewTag.ToString());
		}
	}
}

namespace SeinAbilityContinuationCompilerGate
{
	/**
	 * UE 5.7's RegisterCompilerForBP and compiler-extension registries expose
	 * no unregister operation. A module-owned factory/extension would leave a
	 * stale callback after live module unload. The editor pre-compile delegate
	 * is symmetric, runs after CurrentMessageLog is installed, and therefore
	 * emits the same real blocking compiler errors without replacing the stock
	 * Kismet compiler.
	 */
	void Validate(UBlueprint* Blueprint)
	{
		if (!FSeinAbilityContinuationAnalysis::IsAbilityBlueprint(
				Blueprint))
		{
			return;
		}

		TArray<FSeinAbilityContinuationFinding> Findings;
		FSeinAbilityContinuationAnalysis::Analyze(*Blueprint, Findings);
		for (const FSeinAbilityContinuationFinding& Finding : Findings)
		{
			const UEdGraphNode* AsyncNode = Finding.AsyncNode;
			const UEdGraphNode* SourceNode =
				Finding.SourceNode ? Finding.SourceNode : AsyncNode;
			Blueprint->Message_Error(
				Finding.ToDiagnostic()
					+ TEXT(" Async node: @@. Unsafe source: @@."),
				AsyncNode,
				SourceNode);
		}
	}
}

EAssetTypeCategories::Type FSeinARTSEditorModule::SeinARTSCategoryBit = EAssetTypeCategories::Misc;

// Out-of-line ctor/dtor — keeps the forward-declared TUniquePtr<UDSValidator>
// + TSharedPtr<PinFactory> destructor calls inside this TU (where the types
// are complete). See the header for the full rationale.
FSeinARTSEditorModule::FSeinARTSEditorModule() = default;
FSeinARTSEditorModule::~FSeinARTSEditorModule() = default;

void FSeinARTSEditorModule::StartupModule()
{
	bModuleOwnedStateReleased = false;
	FSeinARTSEditorStyle::Initialize();

	// Asset definitions normally self-register when their CDO is constructed,
	// but a late-loaded editor module can create the CDO before the registry
	// exists. Make the lease explicit so Startup and PreUnload are symmetric.
	if (UAssetDefinitionRegistry* AssetDefinitionRegistry =
			UAssetDefinitionRegistry::Get())
	{
		AssetDefinitionRegistry->RegisterAssetDefinition(
			GetMutableDefault<UAssetDefinition_SeinWidgetBlueprint>());
	}

	// One shared, read-only preflight backs both gates. The module owns every
	// lease so editor/module reload cannot leave a stale PIE authorizer or cook
	// callback behind.
	SimulationContentCookIntegration =
		MakeUnique<FSeinSimulationContentCookIntegration>();
	SimulationContentGenerateCommand =
		MakeUnique<FAutoConsoleCommand>(
			TEXT("Sein.SimulationContent.GenerateManifest"),
			TEXT("Generate and save the exact active simulation-content manifest profile."),
			FConsoleCommandDelegate::CreateLambda(
				[]()
				{
					FSeinSimulationContentManifestBuildResult Result;
					FString Error;
					if (!FSeinSimulationContentManifestBuilder::
						GenerateConfiguredManifest(Result, Error))
					{
						UE_LOG(
							LogSeinARTSEditor,
							Error,
							TEXT("Simulation-content manifest generation failed: %s"),
							*Error);
						return;
					}
					UE_LOG(
						LogSeinARTSEditor,
						Display,
						TEXT("Generated simulation-content manifest %s (%d contributors, %d records, digest=%s)."),
						*Result.ManifestObjectPath,
						Result.ContributorCount,
						Result.RecordCount,
						*Result.RootDigest.ToString(
							EGuidFormats::Digits));
				}));
	if (!IsRunningCommandlet())
	{
		SimulationContentPIEAuthorizer =
			MakeUnique<FSeinSimulationContentPIEAuthorizer>();
		IModularFeatures::Get().RegisterModularFeature(
			IPIEAuthorizer::GetModularFeatureName(),
			SimulationContentPIEAuthorizer.Get());
	}

	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();

	if (SeinARTSCategoryBit == EAssetTypeCategories::Misc)
	{
		SeinARTSCategoryBit = AssetTools.RegisterAdvancedAssetCategory(
			FName(TEXT("SeinARTS")),
			LOCTEXT("SeinARTSAssetCategory", "SeinARTS")
		);
	}

	RegisterAssetTypeActions();

	if (GEditor != nullptr)
	{
		AbilityContinuationPreCompileHandle =
			GEditor->OnBlueprintPreCompile().AddStatic(
				&SeinAbilityContinuationCompilerGate::Validate);
	}

	// Register custom thumbnail renderers for our Blueprint subclasses.
	UThumbnailManager& ThumbnailMgr = UThumbnailManager::Get();
	ThumbnailMgr.RegisterCustomRenderer(
		USeinActorBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	ThumbnailMgr.RegisterCustomRenderer(
		USeinAbilityBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	ThumbnailMgr.RegisterCustomRenderer(
		USeinEffectBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	ThumbnailMgr.RegisterCustomRenderer(
		USeinFormationBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	// Sein UDSes (Right-click → Component) get the SeinComponentIcon92 tile.
	// The renderer falls through to the engine default for non-Sein UDSes.
	ThumbnailMgr.RegisterCustomRenderer(
		UUserDefinedStruct::StaticClass(),
		USeinStructThumbnailRenderer::StaticClass()
	);
	// Intentionally do NOT register our custom renderer for USeinWidgetBlueprint.
	// Widget BPs need the engine's UWidgetBlueprintThumbnailRenderer to draw the
	// designer preview; our 92px icon would otherwise overwrite it. The 16px
	// corner badge and the purple color bar are still applied via
	// ClassIcon.SeinWidgetBlueprint / ClassIcon.SeinUserWidget (style set) and
	// UAssetDefinition_SeinWidgetBlueprint::GetAssetColor (asset definition) —
	// both decorate the tile independently of the thumbnail renderer.

	SeinPinFactory = MakeShared<FSeinPinFactory>();
	FEdGraphUtilities::RegisterVisualPinFactory(SeinPinFactory);

	// UDS composition path: designer-authored UDSes show up in the entity
	// bridge's `ComponentData` array picker (filtered to
	// SeinEntityComponentsOnly + SeinDeterministic). No more "drag UDS onto
	// the actor BP's components panel" broker — that pattern instantiated
	// USeinStructComponent ACs which are now deleted.

	// Enforce the determinism whitelist on Sein UDSes. The validator auto-
	// registers with FStructureEditorUtils::FStructEditorManager in its ctor
	// (via INotifyOnStructChanged/InnerListenerType) and auto-removes in its
	// dtor when UDSValidator is reset at shutdown.
	UDSValidator = MakeUnique<FSeinDeterministicStructValidator>();

	{
		FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>("PropertyEditor");
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("FixedPoint"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinFixedPointDetails::MakeInstance));

		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("InstancedStruct"));
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("InstancedStruct"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinInstancedStructDetails::MakeInstance));

		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinVisionStamp"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinVisionStampDetails::MakeInstance));

		// Collision response matrix — Unreal-style Ignore/Overlap/Block per channel.
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinCollisionResponseContainer"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinCollisionResponseDetails::MakeInstance));

		// Object Type — dropdown of channel names from settings.
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinCollisionObjectType"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinCollisionObjectTypeDetails::MakeInstance));

		// Squad slot — hide the per-slot OffsetTransform when the squad's chosen formation isn't slot-based.
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinSquadSlot"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinSquadSlotDetails::MakeInstance));

		// Auto-tag-generation customizers — per-BP "Reset to Auto" buttons +
		// settings-page Regenerate buttons. See SeinAutoTagDetails.h.
		PropertyModule.RegisterCustomClassLayout(
			USeinAbility::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinAbilityAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomClassLayout(
			USeinEffect::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinEffectAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinIdentityComponent"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinIdentityComponentAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomClassLayout(
			USeinARTSCoreSettings::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinARTSCoreSettingsDetails::MakeInstance));

		// Movement-mode BPs (USeinMovement subclasses): a Class-Defaults "Sync Tuning
		// Struct" button that mirrors the BP's tuning vars into its paired UDS. Keyed by
		// class NAME so the editor module needs no SeinARTSMovement link dependency; the
		// customization no-ops for C++ modes (no ClassGeneratedBy).
		PropertyModule.RegisterCustomClassLayout(
			FName(TEXT("SeinMovement")),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinMovementModeDetails::MakeInstance));

		// Balance Profile — Preview / Gather / Push action buttons. Keyed by the
		// concrete class; the editor module depends on SeinARTSCoreEntity, so no
		// name-string indirection is needed (unlike SeinMovement above).
		PropertyModule.RegisterCustomClassLayout(
			USeinBalanceProfile::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinBalanceProfileDetails::MakeInstance));

		// Legacy `FSeinVisionComponent` / `FSeinExtentsComponent` / `FSeinMovementData`
		// details customizations (nav-layer-mask combo, etc.) were excised in
		// the Phase-5 refactor. The new `FSeinVisionComponent` /
		// `FSeinExtentsComponent` / `FSeinNavigationComponent` structs use the
		// standard bitmask combo. Re-add a customization keyed on the new
		// struct name if a custom combo is desired again.

		// The unified bake entry point is a CallInEditor button on
		// ASeinLevelVolume ("Bake Level Data"), so no volume details panels
		// are registered here — keeps the editor module decoupled from the
		// nav/FoW systems. Replace the nav/fog class via plugin settings; the
		// bake button stays on the volume regardless.

		PropertyModule.NotifyCustomizationModuleChanged();
	}

	// Component visualizers — drawn in the BP/level editor viewport when the
	// owning component is selected. Lets designers eyeball Extents shapes
	// without opening PIE. Registered against the entity bridge component;
	// the visualizer walks its ComponentData array for FSeinExtentsComponent
	// entries and draws each shape — no separate "extents preview" AC.
	if (GUnrealEd != nullptr)
	{
		// One visualizer per component class — this one walks the bridge's
		// ComponentData and draws every recognized FSein*Component entry's
		// debug geometry (extents wireframes + vision-stamp shapes).
		TSharedPtr<FComponentVisualizer> EntityViz = MakeShared<FSeinEntityComponentVisualizer>();
		GUnrealEd->RegisterComponentVisualizer(USeinEntityComponent::StaticClass()->GetFName(), EntityViz);
		EntityViz->OnRegister();
	}

	// Auto-tag rename hook. UE's AssetRegistry fires OnAssetRenamed after the
	// rename has completed; the handler regenerates auto-tags for SeinARTS BPs
	// whose `bAutoGeneratedTag = true`. Collisions soft-fail (warning log, tag
	// untouched) — see the handler's docstring for the post-rename rationale.
	{
		FAssetRegistryModule& AssetRegistryModule =
			FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
		OnAssetRenamedHandle = AssetRegistryModule.Get().OnAssetRenamed().AddStatic(
			&SeinAutoTagRenameHandler::OnAssetRenamed);
	}
}

void FSeinARTSEditorModule::PreUnloadCallback()
{
	ReleaseModuleOwnedState();
}

void FSeinARTSEditorModule::ShutdownModule()
{
	ReleaseModuleOwnedState();
}

void FSeinARTSEditorModule::ReleaseModuleOwnedState()
{
	if (bModuleOwnedStateReleased)
	{
		return;
	}
	bModuleOwnedStateReleased = true;

	if (AbilityContinuationPreCompileHandle.IsValid())
	{
		if (GEditor != nullptr)
		{
			GEditor->OnBlueprintPreCompile().Remove(
				AbilityContinuationPreCompileHandle);
		}
		AbilityContinuationPreCompileHandle.Reset();
	}

	SimulationContentGenerateCommand.Reset();
	if (SimulationContentPIEAuthorizer)
	{
		IModularFeatures::Get().UnregisterModularFeature(
			IPIEAuthorizer::GetModularFeatureName(),
			SimulationContentPIEAuthorizer.Get());
		SimulationContentPIEAuthorizer.Reset();
	}
	SimulationContentCookIntegration.Reset();

	const bool bCanTouchUObjectRegistries =
		UObjectInitialized() && !IsEngineExitRequested();
	if (bCanTouchUObjectRegistries)
	{
		// The registry holds the definition CDO strongly. Only remove our exact
		// generation so a replacement module loaded during a reload cannot be
		// accidentally unregistered by the outgoing generation.
		if (FModuleManager::Get().IsModuleLoaded("AssetDefinition"))
		{
			if (UAssetDefinitionRegistry* AssetDefinitionRegistry =
					UAssetDefinitionRegistry::Get())
			{
				UAssetDefinition_SeinWidgetBlueprint* AssetDefinition =
					GetMutableDefault<UAssetDefinition_SeinWidgetBlueprint>();
				if (AssetDefinitionRegistry->GetAssetDefinitionForClass(
						USeinWidgetBlueprint::StaticClass()) == AssetDefinition)
				{
					AssetDefinitionRegistry->UnregisterAssetDefinition(
						AssetDefinition);
				}
			}
		}

		// Native validators are normally discovered automatically, but the
		// subsystem retains their UObject instances until its deferred
		// ModuleUnloaded pass. Remove every concrete validator synchronously
		// while this generation's vtables are still resident.
		if (GEditor != nullptr)
		{
			if (UEditorValidatorSubsystem* ValidatorSubsystem =
					GEditor->GetEditorSubsystem<UEditorValidatorSubsystem>())
			{
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<
						USeinAbilityContinuationValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<USeinBalanceProfileValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<
						USeinCanonicalStateRecipeDeterminismValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<USeinCommandDeterminismValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<USeinFormationDeterminismValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<USeinMovementClassValidator>());
				ValidatorSubsystem->RemoveValidator(
					GetMutableDefault<USeinMovementDeterminismValidator>());
			}
		}
	}

	if (FModuleManager::Get().IsModuleLoaded("PropertyEditor"))
	{
		FPropertyEditorModule& PropertyModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>("PropertyEditor");
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("FixedPoint"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("InstancedStruct"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinVisionStamp"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinCollisionResponseContainer"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinCollisionObjectType"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinIdentityComponent"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinSquadSlot"));
		PropertyModule.UnregisterCustomClassLayout(USeinAbility::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(USeinEffect::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(USeinARTSCoreSettings::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(FName(TEXT("SeinMovement")));
		PropertyModule.UnregisterCustomClassLayout(USeinBalanceProfile::StaticClass()->GetFName());
		// Volume class-layouts unregistered by their owning system modules.

		// We replaced StructUtilsEditor's global InstancedStruct layout at
		// startup. On a live module unload, put the stock implementation back
		// before invalidating details views so no delegate points into this DLL.
		if (!IsEngineExitRequested()
			&& FModuleManager::Get().IsModuleLoaded("StructUtilsEditor"))
		{
			PropertyModule.RegisterCustomPropertyTypeLayout(
				TEXT("InstancedStruct"),
				FOnGetPropertyTypeCustomizationInstance::CreateStatic(
					&FInstancedStructDetails::MakeInstance));
		}
		PropertyModule.NotifyCustomizationModuleChanged();
	}

	if (UObjectInitialized() && !IsEngineExitRequested())
	{
		if (UThumbnailManager* ThumbnailManager = UThumbnailManager::TryGet())
		{
			ThumbnailManager->UnregisterCustomRenderer(USeinActorBlueprint::StaticClass());
			ThumbnailManager->UnregisterCustomRenderer(USeinAbilityBlueprint::StaticClass());
			ThumbnailManager->UnregisterCustomRenderer(USeinEffectBlueprint::StaticClass());
			ThumbnailManager->UnregisterCustomRenderer(USeinFormationBlueprint::StaticClass());
			ThumbnailManager->UnregisterCustomRenderer(UUserDefinedStruct::StaticClass());
		}
	}

	if (GUnrealEd != nullptr)
	{
		GUnrealEd->UnregisterComponentVisualizer(USeinEntityComponent::StaticClass()->GetFName());
	}

	// Unhook the auto-tag rename handler. GetModulePtr (not Checked) to survive
	// teardown ordering where AssetRegistry unloads before us.
	if (OnAssetRenamedHandle.IsValid())
	{
		if (FAssetRegistryModule* AssetRegistryModule =
				FModuleManager::GetModulePtr<FAssetRegistryModule>("AssetRegistry"))
		{
			AssetRegistryModule->Get().OnAssetRenamed().Remove(OnAssetRenamedHandle);
		}
		OnAssetRenamedHandle.Reset();
	}

	if (SeinPinFactory.IsValid())
	{
		FEdGraphUtilities::UnregisterVisualPinFactory(SeinPinFactory);
		SeinPinFactory.Reset();
	}

	// Dtor unregisters the listener via INotifyOnStructChanged RAII.
	UDSValidator.Reset();

	// Safety net — optional system editor modules SHOULD unregister their
	// own draw callbacks in their ShutdownModule, but a clean slate here
	// guards against stale bindings if an optional module's shutdown was
	// skipped (hot-reload race, runtime module-disable, etc.).
	ComponentDataDraws.Empty();

	UnregisterAssetTypeActions();
	FSeinARTSEditorStyle::Shutdown();
}

EAssetTypeCategories::Type FSeinARTSEditorModule::GetAssetCategoryBit()
{
	return SeinARTSCategoryBit;
}

void FSeinARTSEditorModule::RegisterComponentDataDraw(FName Key, FSeinComponentDataDrawDelegate Draw)
{
	// FindOrAdd semantics: re-registering with the same key replaces the old
	// delegate. Useful for hot-reload paths where an optional module gets
	// re-initialized without us tearing down the editor — the second register
	// silently supersedes the stale binding from the first load.
	ComponentDataDraws.FindOrAdd(Key) = MoveTemp(Draw);
}

void FSeinARTSEditorModule::UnregisterComponentDataDraw(FName Key)
{
	ComponentDataDraws.Remove(Key);
}

void FSeinARTSEditorModule::RegisterAssetTypeActions()
{
	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();

	auto RegisterAction = [&](const TSharedRef<IAssetTypeActions>& Action)
	{
		AssetTools.RegisterAssetTypeActions(Action);
		RegisteredActions.Add(Action);
	};

	RegisterAction(MakeShared<FAssetTypeActions_SeinActorBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinAbilityBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinEffectBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinFormationBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinBalanceProfile>());
}

void FSeinARTSEditorModule::UnregisterAssetTypeActions()
{
	if (FModuleManager::Get().IsModuleLoaded("AssetTools"))
	{
		IAssetTools& AssetTools = FModuleManager::GetModuleChecked<FAssetToolsModule>("AssetTools").Get();
		for (const TSharedPtr<IAssetTypeActions>& Action : RegisteredActions)
		{
			AssetTools.UnregisterAssetTypeActions(Action.ToSharedRef());
		}
	}
	RegisteredActions.Empty();
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FSeinARTSEditorModule, SeinARTSEditor)
