/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file:		SeinARTSEditorModule.cpp
 * @date:		3/27/2026
 * @author:		RJ Macklem
 * @brief:		Implementation of the SeinARTS editor module.
 */

#include "SeinARTSEditorModule.h"
#include "SeinARTSEditorStyle.h"
#include "SeinAssetTypeActions.h"
#include "AssetToolsModule.h"
#include "IAssetTools.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "ThumbnailRendering/ThumbnailManager.h"
#include "Thumbnails/SeinBlueprintThumbnailRenderer.h"
#include "Thumbnails/SeinStructThumbnailRenderer.h"
#include "Validators/SeinDeterministicStructValidator.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Settings/PluginSettings.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Actor/SeinActor.h"
#include "Components/SeinIdentityComponent.h"
#include "StructUtils/UserDefinedStruct.h"
#include "StructUtils/InstancedStruct.h"
#include "Engine/Blueprint.h"
#include "Actor/SeinActorBlueprint.h"
#include "Abilities/SeinAbilityBlueprint.h"
#include "Effects/SeinEffectBlueprint.h"
#include "Widgets/SeinWidgetBlueprint.h"
#include "WidgetBlueprint.h"
#include "KismetCompiler.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "EdGraphUtilities.h"
#include "Graph/SeinPinFactory.h"
#include "PropertyEditorModule.h"
#include "Details/SeinFixedPointDetails.h"
#include "Details/SeinInstancedStructDetails.h"
#include "Details/SeinAutoTagDetails.h"
#include "Details/SeinARTSCoreSettingsDetails.h"
// Volume details panels live in their owning system modules (SeinARTSNavigation
// + SeinARTSFogOfWar), not here — preserves the "each subsystem self-contained"
// pattern. Each module registers its own customization at StartupModule under
// `#if WITH_EDITOR`, so the editor module never imports their headers.
#include "Details/SeinVisionStampDetails.h"
#include "Details/SeinCollisionResponseDetails.h"
#include "Details/SeinCollisionObjectTypeDetails.h"
#include "Visualizers/SeinEntityComponentVisualizer.h"
#include "Actor/SeinEntityComponent.h"
#include "UnrealEdGlobals.h"
#include "Editor/UnrealEdEngine.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAutoTag, Log, All);

namespace SeinAutoTagRenameHandler
{
	/** Inspect a freshly-renamed asset; if it's a SeinARTS taggable BP with
	 *  `bAutoGeneratedTag = true`, regenerate its tag from the new name.
	 *  Collisions soft-fail (warning log, tag left untouched) because UE's
	 *  rename pipeline is post-fire — we can't veto from here. Designer
	 *  notices via the log + can fix manually via "Reset to Auto" after
	 *  resolving the name collision. */
	static void OnAssetRenamed(const FAssetData& Asset, const FString& OldObjectPath)
	{
		const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>();
		if (!Settings || !Settings->bEnableAutoTagGeneration) return;

		UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
		if (!BP || !BP->GeneratedClass) return;
		UObject* CDO = BP->GeneratedClass->GetDefaultObject();
		if (!CDO) return;

		const FName NewName = Asset.AssetName;
		const FGameplayTag NewTag = SeinAutoTag::DeriveTagFromAssetName(NewName, Settings);
		if (!NewTag.IsValid()) return;

		// Lambda — returns true if the tag was updated (BP needs marking dirty).
		auto UpdateAndCheckCollision = [&](FGameplayTag& OutTag, bool& OutAutoFlag) -> bool
		{
			if (!OutAutoFlag) return false;  // designer owns this tag — don't touch
			if (OutTag == NewTag) return false;  // already correct

			const FString Collider = SeinAutoTag::FindCollidingAssetPath(NewTag, Asset.PackageName.ToString());
			if (!Collider.IsEmpty())
			{
				UE_LOG(LogSeinAutoTag, Warning,
					TEXT("Asset '%s' renamed but new auto-tag '%s' collides with '%s'. Tag left as '%s' — fix by renaming again or click 'Reset to Auto' in the BP details after resolving the collision."),
					*Asset.PackageName.ToString(), *NewTag.ToString(), *Collider, *OutTag.ToString());
				return false;
			}

			OutTag = NewTag;
			SeinAutoTag::RegisterTagIfNeeded(NewTag);
			return true;
		};

		bool bDirty = false;
		if (USeinAbility* Ability = Cast<USeinAbility>(CDO))
		{
			bDirty = UpdateAndCheckCollision(Ability->AbilityTag, Ability->bAutoGeneratedTag);
		}
		else if (USeinEffect* Effect = Cast<USeinEffect>(CDO))
		{
			bDirty = UpdateAndCheckCollision(Effect->EffectTag, Effect->bAutoGeneratedTag);
		}
		else if (ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
		{
			// Walk the entity bridge's ComponentData for an FSeinIdentityComponent
			// entry. Modifying the struct in-place mutates the bridge's stored
			// FInstancedStruct.
			TArray<USeinEntityComponent*> Bridges;
			SeinActor->GetComponents<USeinEntityComponent>(Bridges);
			for (USeinEntityComponent* Bridge : Bridges)
			{
				if (!Bridge) continue;
				for (FInstancedStruct& Entry : Bridge->ComponentData)
				{
					if (!Entry.IsValid()) continue;
					if (Entry.GetScriptStruct() != FSeinIdentityComponent::StaticStruct()) continue;
					FSeinIdentityComponent& Identity = Entry.GetMutable<FSeinIdentityComponent>();
					if (UpdateAndCheckCollision(Identity.IdentityTag, Identity.bAutoGeneratedTag))
					{
						bDirty = true;
					}
				}
			}
		}

		if (bDirty)
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(BP);
			UE_LOG(LogSeinAutoTag, Log,
				TEXT("Auto-tag updated for renamed asset '%s' → '%s'"),
				*Asset.PackageName.ToString(), *NewTag.ToString());
		}
	}
}

EAssetTypeCategories::Type FSeinARTSEditorModule::SeinARTSCategoryBit = EAssetTypeCategories::Misc;

// Out-of-line ctor/dtor — keeps the forward-declared TUniquePtr<UDSValidator>
// + TSharedPtr<PinFactory> destructor calls inside this TU (where the types
// are complete). See the header for the full rationale.
FSeinARTSEditorModule::FSeinARTSEditorModule() = default;
FSeinARTSEditorModule::~FSeinARTSEditorModule() = default;

void FSeinARTSEditorModule::StartupModule()
{
	FSeinARTSEditorStyle::Initialize();

	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();

	if (SeinARTSCategoryBit == EAssetTypeCategories::Misc)
	{
		SeinARTSCategoryBit = AssetTools.RegisterAdvancedAssetCategory(
			FName(TEXT("SeinARTS")),
			LOCTEXT("SeinARTSAssetCategory", "SeinARTS")
		);
	}

	RegisterAssetTypeActions();

	// UMG's widget compiler is registered per-class via a direct map lookup
	// (no hierarchy walk) — see FKismetCompilerContext::GetCompilerForBP.
	// We must register USeinWidgetBlueprint explicitly, otherwise the lookup
	// misses, falls back to the generic FKismetCompilerContext, and the
	// WidgetTree never gets copied into the generated class (AddToViewport
	// would render nothing despite compilation succeeding).
	FKismetCompilerContext::RegisterCompilerForBP(
		USeinWidgetBlueprint::StaticClass(),
		&UWidgetBlueprint::GetCompilerForWidgetBP
	);

	// Register custom thumbnail renderers for our Blueprint subclasses.
	UThumbnailManager& ThumbnailMgr = UThumbnailManager::Get();
	ThumbnailMgr.RegisterCustomRenderer(
		USeinActorBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	ThumbnailMgr.RegisterCustomRenderer(
		USeinAbilityBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	ThumbnailMgr.RegisterCustomRenderer(
		USeinEffectBlueprint::StaticClass(),
		USeinBlueprintThumbnailRenderer::StaticClass()
	);
	// Sein UDSes (Right-click → Component) get the SeinComponentIcon92 tile.
	// The renderer falls through to the engine default for non-Sein UDSes.
	ThumbnailMgr.RegisterCustomRenderer(
		UUserDefinedStruct::StaticClass(),
		USeinStructThumbnailRenderer::StaticClass()
	);
	// Intentionally do NOT register our custom renderer for USeinWidgetBlueprint.
	// Widget BPs need the engine's UWidgetBlueprintThumbnailRenderer to draw the
	// designer preview; our 92px icon would otherwise overwrite it. The 16px
	// corner badge and the purple color bar are still applied via
	// ClassIcon.SeinWidgetBlueprint / ClassIcon.SeinUserWidget (style set) and
	// UAssetDefinition_SeinWidgetBlueprint::GetAssetColor (asset definition) —
	// both decorate the tile independently of the thumbnail renderer.

	SeinPinFactory = MakeShared<FSeinPinFactory>();
	FEdGraphUtilities::RegisterVisualPinFactory(SeinPinFactory);

	// UDS composition path: designer-authored UDSes show up in the entity
	// bridge's `ComponentData` array picker (filtered to
	// SeinEntityComponentsOnly + SeinDeterministic). No more "drag UDS onto
	// the actor BP's components panel" broker — that pattern instantiated
	// USeinStructComponent ACs which are now deleted.

	// Enforce the determinism whitelist on Sein UDSes. The validator auto-
	// registers with FStructureEditorUtils::FStructEditorManager in its ctor
	// (via INotifyOnStructChanged/InnerListenerType) and auto-removes in its
	// dtor when UDSValidator is reset at shutdown.
	UDSValidator = MakeUnique<FSeinDeterministicStructValidator>();

	{
		FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>("PropertyEditor");
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("FixedPoint"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinFixedPointDetails::MakeInstance));

		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("InstancedStruct"));
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("InstancedStruct"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinInstancedStructDetails::MakeInstance));

		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinVisionStamp"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinVisionStampDetails::MakeInstance));

		// Collision response matrix — Unreal-style Ignore/Overlap/Block per channel.
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinCollisionResponseContainer"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinCollisionResponseDetails::MakeInstance));

		// Object Type — dropdown of channel names from settings.
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinCollisionObjectType"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinCollisionObjectTypeDetails::MakeInstance));

		// Auto-tag-generation customizers — per-BP "Reset to Auto" buttons +
		// settings-page Regenerate buttons. See SeinAutoTagDetails.h.
		PropertyModule.RegisterCustomClassLayout(
			USeinAbility::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinAbilityAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomClassLayout(
			USeinEffect::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinEffectAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomPropertyTypeLayout(
			TEXT("SeinIdentityComponent"),
			FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FSeinIdentityComponentAutoTagDetails::MakeInstance));
		PropertyModule.RegisterCustomClassLayout(
			USeinARTSCoreSettings::StaticClass()->GetFName(),
			FOnGetDetailCustomizationInstance::CreateStatic(&FSeinARTSCoreSettingsDetails::MakeInstance));

		// Legacy `FSeinVisionComponent` / `FSeinExtentsComponent` / `FSeinMovementData`
		// details customizations (nav-layer-mask combo, etc.) were excised in
		// the Phase-5 refactor. The new `FSeinVisionComponent` /
		// `FSeinExtentsComponent` / `FSeinNavigationComponent` structs use the
		// standard bitmask combo. Re-add a customization keyed on the new
		// struct name if a custom combo is desired again.

		// Volume details panels (ASeinNavVolume, ASeinFogOfWarVolume) are
		// registered by their owning system modules' StartupModule under
		// `#if WITH_EDITOR` — keeps the editor module decoupled from those
		// systems. Replace the nav class via plugin settings; the framework's
		// bake button stays on the volume regardless.

		PropertyModule.NotifyCustomizationModuleChanged();
	}

	// Component visualizers — drawn in the BP/level editor viewport when the
	// owning component is selected. Lets designers eyeball Extents shapes
	// without opening PIE. Registered against the entity bridge component;
	// the visualizer walks its ComponentData array for FSeinExtentsComponent
	// entries and draws each shape — no separate "extents preview" AC.
	if (GUnrealEd != nullptr)
	{
		// One visualizer per component class — this one walks the bridge's
		// ComponentData and draws every recognized FSein*Component entry's
		// debug geometry (extents wireframes + vision-stamp shapes).
		TSharedPtr<FComponentVisualizer> EntityViz = MakeShared<FSeinEntityComponentVisualizer>();
		GUnrealEd->RegisterComponentVisualizer(USeinEntityComponent::StaticClass()->GetFName(), EntityViz);
		EntityViz->OnRegister();
	}

	// Auto-tag rename hook. UE's AssetRegistry fires OnAssetRenamed after the
	// rename has completed; the handler regenerates auto-tags for SeinARTS BPs
	// whose `bAutoGeneratedTag = true`. Collisions soft-fail (warning log, tag
	// untouched) — see the handler's docstring for the post-rename rationale.
	{
		FAssetRegistryModule& AssetRegistryModule =
			FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
		OnAssetRenamedHandle = AssetRegistryModule.Get().OnAssetRenamed().AddStatic(
			&SeinAutoTagRenameHandler::OnAssetRenamed);
	}
}

void FSeinARTSEditorModule::ShutdownModule()
{
	if (FModuleManager::Get().IsModuleLoaded("PropertyEditor"))
	{
		FPropertyEditorModule& PropertyModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>("PropertyEditor");
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("FixedPoint"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("InstancedStruct"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinVisionStamp"));
		PropertyModule.UnregisterCustomPropertyTypeLayout(TEXT("SeinIdentityComponent"));
		PropertyModule.UnregisterCustomClassLayout(USeinAbility::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(USeinEffect::StaticClass()->GetFName());
		PropertyModule.UnregisterCustomClassLayout(USeinARTSCoreSettings::StaticClass()->GetFName());
		// Volume class-layouts unregistered by their owning system modules.
	}

	if (GUnrealEd != nullptr)
	{
		GUnrealEd->UnregisterComponentVisualizer(USeinEntityComponent::StaticClass()->GetFName());
	}

	// Unhook the auto-tag rename handler. GetModulePtr (not Checked) to survive
	// teardown ordering where AssetRegistry unloads before us.
	if (OnAssetRenamedHandle.IsValid())
	{
		if (FAssetRegistryModule* AssetRegistryModule =
				FModuleManager::GetModulePtr<FAssetRegistryModule>("AssetRegistry"))
		{
			AssetRegistryModule->Get().OnAssetRenamed().Remove(OnAssetRenamedHandle);
		}
		OnAssetRenamedHandle.Reset();
	}

	if (SeinPinFactory.IsValid())
	{
		FEdGraphUtilities::UnregisterVisualPinFactory(SeinPinFactory);
		SeinPinFactory.Reset();
	}

	// Dtor unregisters the listener via INotifyOnStructChanged RAII.
	UDSValidator.Reset();

	// Safety net — optional system editor modules SHOULD unregister their
	// own draw callbacks in their ShutdownModule, but a clean slate here
	// guards against stale bindings if an optional module's shutdown was
	// skipped (hot-reload race, runtime module-disable, etc.).
	ComponentDataDraws.Empty();

	UnregisterAssetTypeActions();
	FSeinARTSEditorStyle::Shutdown();
}

EAssetTypeCategories::Type FSeinARTSEditorModule::GetAssetCategoryBit()
{
	return SeinARTSCategoryBit;
}

void FSeinARTSEditorModule::RegisterComponentDataDraw(FName Key, FSeinComponentDataDrawDelegate Draw)
{
	// FindOrAdd semantics: re-registering with the same key replaces the old
	// delegate. Useful for hot-reload paths where an optional module gets
	// re-initialized without us tearing down the editor — the second register
	// silently supersedes the stale binding from the first load.
	ComponentDataDraws.FindOrAdd(Key) = MoveTemp(Draw);
}

void FSeinARTSEditorModule::UnregisterComponentDataDraw(FName Key)
{
	ComponentDataDraws.Remove(Key);
}

void FSeinARTSEditorModule::RegisterAssetTypeActions()
{
	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();

	auto RegisterAction = [&](const TSharedRef<IAssetTypeActions>& Action)
	{
		AssetTools.RegisterAssetTypeActions(Action);
		RegisteredActions.Add(Action);
	};

	RegisterAction(MakeShared<FAssetTypeActions_SeinActorBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinAbilityBlueprint>());
	RegisterAction(MakeShared<FAssetTypeActions_SeinEffectBlueprint>());
}

void FSeinARTSEditorModule::UnregisterAssetTypeActions()
{
	if (FModuleManager::Get().IsModuleLoaded("AssetTools"))
	{
		IAssetTools& AssetTools = FModuleManager::GetModuleChecked<FAssetToolsModule>("AssetTools").Get();
		for (const TSharedPtr<IAssetTypeActions>& Action : RegisteredActions)
		{
			AssetTools.UnregisterAssetTypeActions(Action.ToSharedRef());
		}
	}
	RegisteredActions.Empty();
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FSeinARTSEditorModule, SeinARTSEditor)
