/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinEffect.h
 * @brief   Blueprintable base class for designer-authored sim-side effects.
 *          Per DESIGN §8: one primitive handles instant / finite / infinite /
 *          periodic, with `Scope` determining where the effect lives (Instance
 *          on the target entity, Class on the owner's player state,
 *          Player on the owner's player state targeting player-state fields).
 *
 *          Configuration lives on the CDO; `FSeinActiveEffect` in component
 *          storage carries only the class reference + per-instance runtime
 *          state (stacks, remaining duration, source, instance ID, and the
 *          exact ability grants committed by that instance).
 */

#pragma once

#include "CoreMinimal.h"
#include "Types/FixedPoint.h"
#include "Core/SeinEntityHandle.h"
#include "Core/SeinPlayerID.h"
#include "GameplayTagContainer.h"
#include "Attributes/SeinModifier.h"
#include "SeinEffect.generated.h"

class USeinAbility;

/**
 * How an effect's lifetime is handled. Replaces the old `-1 / 0 / positive`
 * sentinel pattern on `Duration` with explicit intent.
 *
 *   Instant    → applies + removes the same tick. OnApply fires; OnExpire never
 *                does (no real expiration happened). Use for one-shot stat
 *                bumps, "give resources now," instant-damage effects, etc.
 *   Persistent → never expires on its own. Stays until explicitly removed
 *                (e.g. by RemoveEffect, or by the entity being
 *                destroyed). Use for tech effects, "while alive" buffs,
 *                permanent stat upgrades.
 *   Timed      → finite duration; ticks down in FSeinEffectTickSystem and
 *                fires OnExpire when RemainingDuration hits zero. Reads the
 *                `Duration` field for the timer length.
 */
UENUM(BlueprintType)
enum class ESeinEffectDurationMode : uint8
{
	Instant,
	Persistent,
	Timed
};

/**
 * Where a tech effect lands on apply. Per DESIGN §10 Q5.
 * `Player` = researching player only. `Team` = every teammate (tracked via the
 * alliance graph). Non-tech effects leave this at the default and it's inert.
 */
UENUM(BlueprintType)
enum class ESeinTechScope : uint8
{
	/** Default. Applies only to the researching player. */
	Player,
	/** Applies to every teammate of the researching player. */
	Team
};

/**
 * How re-application of the same effect class to the same target behaves.
 * DESIGN §8 Q1d.
 */
UENUM(BlueprintType)
enum class ESeinEffectStackingRule : uint8
{
	/** Default. On re-apply, CurrentStacks++; modifiers multiply by stack count;
	 *  duration refreshes to the CDO's Duration. Cap at MaxStacks. */
	Stack,
	/** CurrentStacks stays at 1; duration refreshes to the CDO's Duration.
	 *  Classic "refresh DoT timer without stacking". */
	Refresh,
	/** Each apply adds a separate FSeinActiveEffect instance that tracks its own
	 *  timer. MaxStacks caps the number of concurrent independent instances. */
	Independent
};

/**
 * Designer-authored effect base. Subclass in Blueprint to define behavior.
 *
 * Effects are deterministic, stateless class-default strategies that run sim-side.
 * Hooks are BlueprintImplementable — designers fill them in BP graphs; C++ provides
 * no default behavior. Future-affecting state belongs in FSeinActiveEffect or world
 * component storage; callbacks must never mutate this definition object.
 *
 * Lifetime: pick a `DurationMode` (Instant / Persistent / Timed). Timed effects
 * read `Duration` for the timer length; Instant/Persistent ignore it.
 *
 * TickInterval semantics: `Zero` = no periodic firing, positive = fire
 * `OnTick` every N sim-seconds while active. Orthogonal to DurationMode — a
 * Persistent aura can periodically pulse, a Timed DoT can tick per second.
 */
UCLASS(Blueprintable, Abstract, Const, ClassGroup = (SeinARTS),
	meta = (DisplayName = "SeinARTS Effect"))
class SEINARTSCOREENTITY_API USeinEffect : public UObject
{
	GENERATED_BODY()

public:
	// ─── Identity ───

	/** Gameplay tag that uniquely identifies this effect class. Used by
	 *  RemoveEffectsWithTag and for UI / replay hooks. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect")
	FGameplayTag EffectTag;

	/** Provenance flag for the auto-tag-generation system. See
	 *  USeinAbility::bAutoGeneratedTag for full semantics. */
	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect",
		AdvancedDisplay)
	bool bAutoGeneratedTag = false;

	// ─── Scope + Lifetime ───

	/** Where this effect lives + what its modifiers target. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Scope")
	ESeinModifierScope Scope = ESeinModifierScope::Instance;

	/** For Class-scope effects: the modifier's TargetClassTag is usually
	 *  authored per-modifier, but this field lets a designer default every modifier
	 *  on this effect to a single class tag. Left unset = modifiers carry their
	 *  own per-entry TargetClassTag. (Design convenience, not framework-enforced.) */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Scope",
		meta = (EditCondition = "Scope == ESeinModifierScope::Class"))
	FGameplayTag DefaultTargetClassTag;

	/** How this effect's lifetime is handled. Instant / Persistent ignore the
	 *  `Duration` field below; Timed reads it. The details panel hides
	 *  `Duration` unless DurationMode is Timed. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Duration")
	ESeinEffectDurationMode DurationMode = ESeinEffectDurationMode::Instant;

	/** Lifetime in sim-seconds. Only read when `DurationMode == Timed`. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Duration",
		meta = (EditCondition = "DurationMode == ESeinEffectDurationMode::Timed",
		        EditConditionHides, ClampMin = "0.0"))
	FFixedPoint Duration = FFixedPoint::FromInt(10);

	/** Zero = no periodic firing. Positive = fire OnTick every TickInterval sim-seconds
	 *  while active. Orthogonal to Duration: an effect can be finite + periodic
	 *  (DoT for 30s, 1 dmg/s) or infinite + periodic (aura fires every 5s forever). */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Duration")
	FFixedPoint TickInterval = FFixedPoint::Zero;

	// ─── Stacking ───

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Stacking")
	ESeinEffectStackingRule StackingRule = ESeinEffectStackingRule::Stack;

	/** Cap for stack count (Stack / Independent rules). 1 = non-stacking.
	 *  Designers wanting effectively-unlimited stacks use a large number (e.g. 9999). */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Stacking", meta = (ClampMin = "1"))
	int32 MaxStacks = 1;

	/** When the source entity dies, remove the effect. Default false — most effects
	 *  persist past source death (bleed from a dead attacker, tech modifier after
	 *  the researcher-building dies). Opt in for source-dependent effects. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Stacking")
	bool bRemoveOnSourceDeath = false;

	// ─── Modifiers + Tags ───

	/** Attribute modifiers applied while this effect is active. Scope comes from
	 *  the containing effect's Scope field — designers don't re-author it per modifier. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Modifiers")
	TArray<FSeinModifier> Modifiers;

	/** Tags granted while this effect is active. Instance scope grants them to
	 *  the target entity; Class/Player scope grants them to the owning player's
	 *  tag state. All paths are refcounted so overlapping grants survive removal. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Tags")
	FGameplayTagContainer GrantedTags;

	/** On apply, remove any existing active effect on the same target whose CDO's
	 *  EffectTag matches any tag in this container. The exact victims and the
	 *  replacement's transaction-relevant definition are frozen after predictable
	 *  validation. OnRemoved may run arbitrary Blueprint; if it invalidates the
	 *  target or frozen definition, committed removals are not rolled back and the
	 *  replacement itself is not applied. Classic
	 *  "anti-poison removes poison". */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Tags")
	FGameplayTagContainer RemoveEffectsWithTag;

	// ─── Ability Grants (effects can grant abilities at runtime) ───
	//
	// Lets a tech effect add abilities at runtime — the "research unlocks
	// Place Vehicle Depot" pattern. Without this field the only way to
	// gate an ability post-spawn was to grant it natively + tag-gate via
	// RequiredPlayerTags; that worked for "available but locked" but kept
	// the locked ability cluttering the action bar / cooldown logic. With
	// this field, the locked ability genuinely doesn't exist on the
	// entity until the effect applies.
	//
	// Grant lifecycle is reference-counted (see
	// FSeinAbilityPayload::AbilityGrantCounts). Two effects granting the
	// same ability class coexist cleanly — each Apply bumps the refcount,
	// each Remove decrements, and the instance is only destroyed when no
	// holder remains. A natively-authored ability and an effect-granted
	// duplicate behave the same way.
	//
	// Fan-out (Class / Player scope effects):
	//   Walks every entity owned by the affected player; if the entity's
	//   tag state contains `AbilityTargetClassTag`, every class in
	//   GrantedAbilities is added via USeinAbilityBPFL::SeinGrantAbility.
	//   Empty AbilityTargetClassTag = no fan-out (designers must specify
	//   the entity class — no "give to everyone" footgun).
	//
	// Instance-scope effects: GrantedAbilities goes to the target entity
	// directly. AbilityTargetClassTag is inert (the target is already
	// known).
	//
	// Spawn-time integration: when a new entity comes online,
	// ReplayEffectAbilityGrants checks the owner's active Class/Player
	// effects for any whose AbilityTargetClassTag matches the new entity's
	// tag state, and grants those abilities — so a unit spawned AFTER tech
	// research completes still receives the unlocked ability.
	//
	// Revoke on remove: each successful grant is recorded on the active
	// effect and removal revokes exactly that ledger. With refcount semantics
	// the ability only disappears if no other source (native authoring,
	// another effect) still holds it. This remains balanced when a passive
	// callback removes the effect partway through the authored array.

	/** Ability classes granted on apply. See class docblock for fan-out
	 *  rules per scope. Empty = no abilities granted. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Abilities")
	TArray<TSubclassOf<USeinAbility>> GrantedAbilities;

	/** Entity-tag filter for Class/Player scope ability fan-out. Required
	 *  for Class/Player scope — empty value skips ability grants
	 *  (modifier/tag grants on the effect still apply). For Instance scope
	 *  this field is ignored. Eligibility is sampled during apply, spawn replay,
	 *  and owner-transfer replay (and rechecked between callback-capable grants);
	 *  later standalone tag changes do not automatically grant or revoke. Example:
	 *  a Vehicle Depot tech effect with
	 *  AbilityTargetClassTag = `Unit.Role.ConstructionWorker` grants
	 *  PlaceVehicleDepot to every construction unit the player owns
	 *  (existing + future). */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Abilities")
	FGameplayTag AbilityTargetClassTag;

	// ─── Tech (DESIGN §10 — tech is an effect) ───

	/** Default false = permanent. True = can be removed post-apply via the standard
	 *  effect-remove API. Typical RTS baselines keep most tech permanent; revocable
	 *  supports commander-swap / era-regression patterns. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Tech")
	bool bRevocable = false;

	/** Per-tech apply scope. `Player` (default) applies to the researching player
	 *  only. `Team` applies to every teammate via the alliance graph. Inert for
	 *  Instance-scope effects (no player to fan out to). */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Tech")
	ESeinTechScope TechScope = ESeinTechScope::Player;

	/** Tags that MUST be ABSENT from the target's tag set for this effect to be
	 *  researchable / applicable. Enables mutually-exclusive commander picks and
	 *  "you already picked Tier 2A so can't pick Tier 2B" patterns. DESIGN §10 Q6. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "SeinARTS|Effect|Tech")
	FGameplayTagContainer ForbiddenPrerequisiteTags;

	/** Escape hatch for BP-scripted eligibility logic (faction-specific, time-gated,
	 *  map-condition-based). Runs after tag prerequisite + forbidden checks; both
	 *  must pass for the research to be enqueue-able / apply-able. DESIGN §10 Q6. */
	UFUNCTION(BlueprintNativeEvent, Category = "SeinARTS|Effect|Tech", meta = (DisplayName = "Can Research"))
	bool CanResearch(FSeinPlayerID PlayerID) const;
	virtual bool CanResearch_Implementation(FSeinPlayerID PlayerID) const { return true; }

	// ─── BP hooks ───

	/** Runs after the new instance, tags, and GrantedAbilities are committed.
	 *  Passive ability activation happens first; if it synchronously removes the
	 *  effect, On Apply is skipped because the instance no longer exists. The
	 *  EffectApplied visual event is queued at initial commit, so self-removal
	 *  produces EffectApplied then EffectRemoved, never the reverse. */
	UFUNCTION(BlueprintImplementableEvent, Category = "SeinARTS|Effect", meta = (DisplayName = "On Apply"))
	void OnApply(FSeinEntityHandle Target, FSeinEntityHandle Source) const;

	UFUNCTION(BlueprintImplementableEvent, Category = "SeinARTS|Effect", meta = (DisplayName = "On Tick"))
	void OnTick(FSeinEntityHandle Target, FFixedPoint DeltaTime) const;

	UFUNCTION(BlueprintImplementableEvent, Category = "SeinARTS|Effect", meta = (DisplayName = "On Expire"))
	void OnExpire(FSeinEntityHandle Target) const;

	UFUNCTION(BlueprintImplementableEvent, Category = "SeinARTS|Effect", meta = (DisplayName = "On Removed"))
	void OnRemoved(FSeinEntityHandle Target, bool bByExpiration) const;

#if WITH_EDITOR
	/** Watches manual edits to EffectTag in the BP details panel and flips
	 *  `bAutoGeneratedTag = false` so the auto-tag-generation system knows
	 *  the designer is now the owner of this tag. */
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

	/** Surfaces `EffectTag` onto this asset's FAssetData (key
	 *  `SeinAssetTagKeys::EffectTag`, bare `ToString()` form) so editor tooling
	 *  — the auto-tag collision check in particular — can read it WITHOUT loading
	 *  the Blueprint + CDO. Additive: chains Super first, never replaces engine
	 *  tags. Harvested at save / FAssetData construction. */
	virtual void GetAssetRegistryTags(FAssetRegistryTagsContext Context) const override;
};
