/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file         SeinAbility.cpp
 * @author       RJ Macklem
 * @created      03 Apr 2026
 * @latest       05 Sep 2026
 * @brief        Implements ability activation, cost ownership, and refundable cooldown sharing.
 *
 *               Cooldown recipients are resolved through neutral broker data.
 *               Captured activation provenance protects cancellation across membership changes.
 *
 * @disclaimer   This code was generated in whole or in part with the assistance
 *               of an AI language model.
 */

#include "Abilities/SeinAbility.h"
#include "UObject/Package.h"
#include "UObject/UnrealType.h"
#include "Simulation/SeinWorldSubsystem.h"
#include "Abilities/SeinLatentActionManager.h"
#include "Lib/SeinResourceBPFL.h"
#include "Components/SeinProductionPayload.h"
#include "Components/SeinCommandBrokerData.h"
#include "Components/SeinBrokerMembershipData.h"
#include "Components/SeinAbilityPayload.h"
#include "Components/SeinIdentityPayload.h"
#include "Components/SeinProduciblePayload.h"
#include "Actor/SeinEntityBridgeComponent.h"
#include "Events/SeinVisualEvent.h"
#include "Effects/SeinEffect.h"
#include "Actor/SeinActor.h"
#include "Core/SeinAssetTagKeys.h"
#include "Core/SeinSimContext.h"
#include "UObject/AssetRegistryTagsContext.h"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAbilityImpl, Log, All);

#if WITH_EDITOR
void USeinAbility::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);
	const FName ChangedName = PropertyChangedEvent.Property
		? PropertyChangedEvent.Property->GetFName()
		: NAME_None;
	if (ChangedName == GET_MEMBER_NAME_CHECKED(USeinAbility, AbilityTag))
	{
		// Designer edited the tag manually — surrender provenance ownership
		// so the auto-tag-generation pipeline leaves this BP alone on future
		// renames + regenerate-all passes.
		bAutoGeneratedTag = false;
	}
}
#endif

void USeinAbility::GetAssetRegistryTags(FAssetRegistryTagsContext Context) const
{
	Super::GetAssetRegistryTags(Context);

	// Surface AbilityTag onto the asset's FAssetData so the editor auto-tag
	// collision check reads it without loading this CDO. Bare ToString() form so
	// a string compare against another tag's ToString() is a valid equality test.
	if (AbilityTag.IsValid())
	{
		Context.AddTag(FAssetRegistryTag(
			SeinAssetTagKeys::AbilityTag(),
			AbilityTag.ToString(),
			FAssetRegistryTag::TT_Alphabetical));
	}
}

void USeinAbility::ResolveActivationCosts(
	const UObject* WorldContextObject,
	FSeinResourceCost& OutActivationCost,
	FSeinResourceCost& OutProductionCompletionCost) const
{
	OutProductionCompletionCost.Amounts.Reset();
	if (CostTiming == ESeinAbilityCostTiming::ProductionQueue)
	{
		USeinResourceBPFL::SeinSplitCostByCatalog(
			WorldContextObject, ResourceCost,
			OutActivationCost, OutProductionCompletionCost);
		return;
	}

	// Immediate is also the fail-safe for an invalid serialized enum value.
	OutActivationCost = ResourceCost;
}

void USeinAbility::EnqueueProduction(TSubclassOf<ASeinActor> ProducibleClass)
{
	if (!WorldSubsystem)
	{
		UE_LOG(LogSeinAbilityImpl, Warning, TEXT("EnqueueProduction[%s]: ability has no WorldSubsystem"),
			*GetName());
		return;
	}
	if (!SeinIsInSimContext(WorldSubsystem))
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("EnqueueProduction rejected outside this world's simulation context for %s"),
			*GetName());
		return;
	}
	if (!ResourcePayer.IsValid())
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: no unconsumed activation funding snapshot"),
			*GetName());
		return;
	}
	const auto RollBackFailedEnqueue = [this]()
	{
		if (!DeductedCost.IsEmpty() && ResourcePayer.IsValid())
		{
			USeinResourceBPFL::SeinRefund(
				WorldSubsystem, ResourcePayer, DeductedCost);
		}
		DeductedCost.Amounts.Empty();
		PendingCompletionCost.Amounts.Empty();
		ResourcePayer = FSeinPlayerID::Neutral();
	};
	if (!ProducibleClass)
	{
		UE_LOG(LogSeinAbilityImpl, Warning, TEXT("EnqueueProduction[%s]: null ProducibleClass"),
			*GetName());
		RollBackFailedEnqueue();
		return;
	}

	FSeinProductionPayload* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionPayload>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: owner %s has no FSeinProductionPayload"),
			*GetName(), *OwnerEntity.ToString());
		RollBackFailedEnqueue();
		return;
	}
	if (!ProdComp->CanQueueMore())
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: owner %s queue full (max=%d)"),
			*GetName(), *OwnerEntity.ToString(), ProdComp->MaxQueueSize);
		RollBackFailedEnqueue();
		return;
	}

	// Producible's authoring lives on the producible class's entity bridge —
	// FSeinProduciblePayload (BuildTime / RefundPolicy / research metadata)
	// and FSeinIdentityPayload (IdentityTag for the production visual
	// event). Both are FInstancedStruct entries in
	// `USeinEntityBridgeComponent::ComponentData` on the BP CDO.
	const FSeinProduciblePayload* Producible = nullptr;
	const FSeinIdentityPayload* Identity = nullptr;
	{
		TArray<const USeinEntityBridgeComponent*> Bridges;
		AActor::GetActorClassDefaultComponents<USeinEntityBridgeComponent>(ProducibleClass, Bridges);
		for (const USeinEntityBridgeComponent* Bridge : Bridges)
		{
			if (!Bridge) continue;
			if (!Producible) Producible = Bridge->FindAuthoredData<FSeinProduciblePayload>();
			if (!Identity)   Identity   = Bridge->FindAuthoredData<FSeinIdentityPayload>();
		}
	}
	if (!Producible)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: producible %s has no FSeinProduciblePayload on its entity bridge; skipping"),
			*GetName(), *ProducibleClass->GetName());
		RollBackFailedEnqueue();
		return;
	}
	UClass* ResearchEffectClass = Producible->GrantedTechEffect.Get();
	if (Producible->bIsResearch
		&& (!ResearchEffectClass
			|| ResearchEffectClass->HasAnyClassFlags(CLASS_Abstract)
			|| !GetDefault<USeinEffect>(ResearchEffectClass)))
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: research producible %s has no usable GrantedTechEffect"),
			*GetName(), *ProducibleClass->GetName());
		RollBackFailedEnqueue();
		return;
	}

	FSeinProductionQueueSettings QueueSettings;
	int64 QueueUsed = 0;
	if (WorldSubsystem->CheckProductionQueue(OwnerEntity, ProducibleClass, QueueSettings, QueueUsed)
		!= ESeinProductionQueueResult::Available)
	{
		RollBackFailedEnqueue();
		return;
	}

	// The activation snapshot is already policy-resolved. Immediate abilities
	// transfer the full deducted cost and no completion cost; Production Queue
	// abilities transfer the catalog split.
	FSeinProductionQueueEntry Entry;
	Entry.ActorClass = ProducibleClass;
	Entry.TotalBuildTime = Producible->BuildTime;
	Entry.AtEnqueueCost = DeductedCost;
	Entry.AtCompletionCost = PendingCompletionCost;
	Entry.ResourcePayer = ResourcePayer;
	Entry.bIsResearch = Producible->bIsResearch;
	Entry.ResearchEffectClass = Producible->GrantedTechEffect;
	Entry.RefundPolicy = Producible->RefundPolicy;

	const bool bWasEmpty = ProdComp->Queue.Num() == 0;
	ProdComp->Queue.Add(MoveTemp(Entry));

	// Economic ownership has transferred to the queue entry. The ability must
	// not retain a second refundable copy if its graph is cancelled afterward.
	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();

	UE_LOG(LogSeinAbilityImpl, Verbose,
		TEXT("EnqueueProduction[%s]: queued %s on %s (build=%.2fs, queue depth=%d)"),
		*GetName(), *ProducibleClass->GetName(), *OwnerEntity.ToString(),
		Producible->BuildTime.ToFloat(), ProdComp->Queue.Num());

	if (bWasEmpty)
	{
		ProdComp->CurrentBuildProgress = FFixedPoint::Zero;
		ProdComp->bStalledAtCompletion = false;
		const FGameplayTag IdentityTag = Identity ? Identity->IdentityTag : FGameplayTag();
		WorldSubsystem->EnqueueVisualEvent(FSeinVisualEvent::MakeProductionEvent(
			OwnerEntity, IdentityTag, /*bCompleted=*/false));
	}
}

bool USeinAbility::CancelProduction(int32 QueueIndex)
{
	if (!WorldSubsystem)
	{
		return false;
	}
	if (!SeinIsInSimContext(WorldSubsystem))
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("CancelProduction rejected outside this world's simulation context for %s"),
			*GetName());
		return false;
	}
	return WorldSubsystem->CancelProduction(OwnerEntity, QueueIndex);
}

void USeinAbility::SetRallyPoint(const FFixedTransform& Transform)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilitySetRallyPoint")))
	{
		return;
	}
	FSeinProductionPayload* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionPayload>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("SetRallyPoint[%s]: owner %s has no FSeinProductionPayload"),
			*GetName(), *OwnerEntity.ToString());
		return;
	}
	ProdComp->bRallyToEntity = false;
	ProdComp->RallyTransform = Transform;
	ProdComp->RallyEntity = FSeinEntityHandle();
}

void USeinAbility::SetRallyEntity(FSeinEntityHandle RallyEntity)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilitySetRallyEntity")))
	{
		return;
	}
	FSeinProductionPayload* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionPayload>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("SetRallyEntity[%s]: owner %s has no FSeinProductionPayload"),
			*GetName(), *OwnerEntity.ToString());
		return;
	}
	ProdComp->bRallyToEntity = true;
	ProdComp->RallyEntity = RallyEntity;
	ProdComp->RallyTransform = FFixedTransform();
}

void USeinAbility::ClearRallyPoint()
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilityClearRallyPoint")))
	{
		return;
	}
	FSeinProductionPayload* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionPayload>(OwnerEntity);
	if (!ProdComp) return;
	ProdComp->bRallyToEntity = false;
	ProdComp->RallyTransform = FFixedTransform();
	ProdComp->RallyEntity = FSeinEntityHandle();
}

void USeinAbility::InitializeAbility(FSeinEntityHandle Owner, USeinWorldSubsystem* Subsystem)
{
	OwnerEntity = Owner;
	WorldSubsystem = Subsystem;
	RuntimePoolID = INDEX_NONE;
	CooldownRemaining = FFixedPoint::Zero;
	bIsActive = false;
	AbilityActivationID = 0;
	bCooldownStarted = false;
	CooldownSourceActivationID = 0;
	CooldownRecipientIDs.Reset();
	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();
	CommittedGrantedTags.Reset();
}

UWorld* USeinAbility::GetWorld() const
{
	// Skip during CDO construction — UObject systems probe GetWorld() while
	// laying out the class default object, before any subsystem is bound. The
	// nullptr return matches the UObject default for CDOs.
	if (HasAnyFlags(RF_ClassDefaultObject)) { return nullptr; }
	return WorldSubsystem ? WorldSubsystem->GetWorld() : nullptr;
}

bool USeinAbility::CanCommitGrantedTags() const
{
	if (!WorldSubsystem)
	{
		return true;
	}
	const bool bWillReleaseCurrentOwnership = bIsActive
		&& GrantedTags.HasAny(CancelAbilitiesWithTag);
	if (bIsActive && !bWillReleaseCurrentOwnership)
	{
		return false;
	}
	for (const FGameplayTag& Tag : GrantedTags)
	{
		if (!WorldSubsystem->CanGrantTag(OwnerEntity, Tag)
			&& !(bWillReleaseCurrentOwnership
				&& CommittedGrantedTags.HasTagExact(Tag)))
		{
			return false;
		}
	}
	return true;
}

bool USeinAbility::AcquireGrantedTags()
{
	CommittedGrantedTags.Reset();
	if (!WorldSubsystem)
	{
		return true;
	}
	for (const FGameplayTag& Tag : GrantedTags)
	{
		if (!WorldSubsystem->GrantTag(OwnerEntity, Tag))
		{
			ReleaseCommittedGrantedTags();
			return false;
		}
		CommittedGrantedTags.AddTag(Tag);
	}
	return true;
}

void USeinAbility::ReleaseCommittedGrantedTags()
{
	if (WorldSubsystem)
	{
		for (const FGameplayTag& Tag : CommittedGrantedTags)
		{
			WorldSubsystem->UngrantTag(OwnerEntity, Tag);
		}
	}
	CommittedGrantedTags.Reset();
}

bool USeinAbility::ActivateAbility(FSeinEntityHandle Target, FFixedVector Location, const FSeinAbilityActivationInputs& Inputs)
{
	return ActivateAbilityInternal(Target, Location, nullptr, Inputs);
}

bool USeinAbility::ActivateAbilityWithTargeterPoints(FSeinEntityHandle Target, FFixedVector Location,
	const TArray<FSeinTargeterPoint>& Points, const FSeinAbilityActivationInputs& Inputs)
{
	return ActivateAbilityInternal(Target, Location, &Points, Inputs);
}

bool USeinAbility::ActivateAbilityInternal(FSeinEntityHandle Target,
	FFixedVector Location,
	const TArray<FSeinTargeterPoint>* Points, const FSeinAbilityActivationInputs& Inputs)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(
			Points ? TEXT("ActivateAbilityWithTargeterPoints")
				: TEXT("ActivateAbility")))
	{
		return false;
	}
	if (bIsActive)
	{
		return false;
	}
	TStrongObjectPtr<USeinAbility> InputValues;
	const TArray<FName> InputNames = GetActivationInputNames();
	if (!InputNames.IsEmpty() || !Inputs.IsEmpty())
	{
		InputValues.Reset(NewObject<USeinAbility>(GetTransientPackage(), GetClass()));
		FString InputError;
		if (!Inputs.Decode(*InputValues, InputError)) return false;
	}
	MarkDeterministicStateDirty();
	if (!AcquireGrantedTags())
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: refused because an owned tag is saturated on %s"),
			*GetName(), *OwnerEntity.ToString());
		return false;
	}
	int64 NewActivationID = 0;
	if (!WorldSubsystem->TryAllocateAbilityActivationID(NewActivationID))
	{
		ReleaseCommittedGrantedTags();
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: deterministic activation ID space is exhausted."),
			*GetName());
		return false;
	}

	// Publish complete runtime identity before executing designer code. This
	// makes GetActiveAbility/GetActivePassives truthful from inside OnActivate,
	// and lets synchronous EndAbility detach the exact identity immediately.
	const int64 PreviousActivationID = AbilityActivationID;
	const FSeinEntityHandle PreviousTargetEntity = TargetEntity;
	const FFixedVector PreviousTargetLocation = TargetLocation;
	const bool bPreviousCooldownStarted = bCooldownStarted;
	TArray<FSeinTargeterPoint> PreviousTargeterPoints = MoveTemp(TargeterPoints);
	if (Points)
	{
		TargeterPoints = *Points;
	}
	else
	{
		// Right-click / direct-activation path — no targeter points captured.
		// Empty means the ability should read TargetLocation alone.
		TargeterPoints.Reset();
	}
	TargetEntity = Target;
	TargetLocation = Points && Points->Num() > 0
		? (*Points)[0].Location
		: Location;
	AbilityActivationID = NewActivationID;
	bIsActive = true;
	bCooldownStarted = false;
	if (!WorldSubsystem->RegisterAbilityActivity(this))
	{
		bIsActive = false;
		AbilityActivationID = PreviousActivationID;
		TargetEntity = PreviousTargetEntity;
		TargetLocation = PreviousTargetLocation;
		TargeterPoints = MoveTemp(PreviousTargeterPoints);
		bCooldownStarted = bPreviousCooldownStarted;
		ReleaseCommittedGrantedTags();
		return false;
	}

	for (FName Name : InputNames)
	{
		FProperty* Property = FindFProperty<FProperty>(GetClass(), Name);
		Property->CopyCompleteValue(Property->ContainerPtrToValuePtr<void>(this),
			Property->ContainerPtrToValuePtr<void>(InputValues.Get()));
	}
	CooldownRecipientIDs.Reset();
	// Start cooldown if the ability's timing fires on activate. OnEnd-timed abilities
	// defer cooldown until DeactivateAbility.
	if (CooldownStartTiming == ESeinCooldownStartTiming::OnActivate)
	{
		StartCooldownInternal();
	}

	// Queue before designer callbacks so an immediate end follows activation.
	WorldSubsystem->EnqueueVisualEvent(
		FSeinVisualEvent::MakeAbilityEvent(OwnerEntity, AbilityTag, true));
	OnActivate();
	return true;
}

void USeinAbility::TickAbility(FFixedPoint DeltaTime)
{
	if (bIsActive)
	{
		// The callback is the normal Blueprint write barrier: derived Blueprint
		// variables may change even when native fields do not.
		MarkDeterministicStateDirty();
		OnTick(DeltaTime);
	}
}

void USeinAbility::DeactivateAbility(bool bCancelled)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("DeactivateAbility")))
	{
		return;
	}
	if (!bIsActive)
	{
		return;
	}
	MarkDeterministicStateDirty();

	bIsActive = false;
	// Detach before any refund, latent cancellation, or OnEnd callback can
	// synchronously grant/activate a replacement. The old ability may be
	// revoked and its pool slot recycled during OnEnd; pointer-validated world
	// ownership ensures it can never clear the replacement afterwards.
	WorldSubsystem->UnregisterAbilityActivity(this);
	// Queue before cleanup callbacks can activate a replacement ability.
	WorldSubsystem->EnqueueVisualEvent(
		FSeinVisualEvent::MakeAbilityEvent(OwnerEntity, AbilityTag, false));

	// Refund only the costs and cooldown writes owned by this activation.
	if (bCancelled && WorldSubsystem)
	{
		if (bRefundCostOnCancel && !DeductedCost.IsEmpty())
		{
			USeinResourceBPFL::SeinRefund(WorldSubsystem, ResourcePayer, DeductedCost);
		}
		if (bRefundCooldownOnCancel && bCooldownStarted)
		{
			RefundCooldownInternal();
		}
	}
	// Start cooldown on natural end when timing is OnEnd and not already running
	else if (!bCancelled && CooldownStartTiming == ESeinCooldownStartTiming::OnEnd && !bCooldownStarted)
	{
		StartCooldownInternal();
	}

	CooldownRecipientIDs.Reset();
	// Tear down any latent actions belonging to this ability. Without this,
	// actions like SeinMoveTo linger after EndAbility/CancelAbility and keep
	// ticking against a logically-inactive ability.
	if (WorldSubsystem && WorldSubsystem->LatentActionManager)
	{
		WorldSubsystem->LatentActionManager->CancelActionsForAbility(this);
	}

	ReleaseCommittedGrantedTags();

	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();

	// Clear captured targeter points so a subsequent right-click activation
	// doesn't see stale data from the prior targeter cast.
	TargeterPoints.Reset();

	OnEnd(bCancelled);
}

void USeinAbility::EndAbility()
{
	DeactivateAbility(false);
}

void USeinAbility::CancelAbility()
{
	DeactivateAbility(true);
}

void USeinAbility::MarkDeterministicStateDirty()
{
	if (WorldSubsystem)
	{
		WorldSubsystem->MarkAbilityRuntimeStateDirty(this);
	}
}

void USeinAbility::TickCooldown(FFixedPoint DeltaTime)
{
	if (CooldownRemaining > FFixedPoint::Zero)
	{
		MarkDeterministicStateDirty();
		CooldownRemaining = CooldownRemaining - DeltaTime;
		if (CooldownRemaining <= FFixedPoint::Zero)
		{
			CooldownRemaining = FFixedPoint::Zero;
			CooldownSourceActivationID = 0;
		}
	}
}

bool USeinAbility::IsOnCooldown() const
{
	return CooldownRemaining > FFixedPoint::Zero;
}

void USeinAbility::StartCooldownInternal()
{
	MarkDeterministicStateDirty();
	CooldownRecipientIDs.Reset();
	CooldownRemaining = Cooldown > FFixedPoint::Zero ? Cooldown : FFixedPoint::Zero;
	CooldownSourceActivationID = CooldownRemaining > FFixedPoint::Zero
		? AbilityActivationID : 0;
	bCooldownStarted = true;

	if (CooldownScope != ESeinCooldownScope::SharedGroup) return;
	if (Cooldown <= FFixedPoint::Zero) return;
	if (!WorldSubsystem || !AbilityTag.IsValid()) return;

	const FSeinBrokerMembershipData* Membership =
		WorldSubsystem->GetComponent<FSeinBrokerMembershipData>(OwnerEntity);
	if (!Membership) return;
	const FSeinEntityHandle BrokerHandle = Membership->CurrentBrokerHandle;
	const FSeinCommandBrokerData* Broker =
		WorldSubsystem->GetComponent<FSeinCommandBrokerData>(BrokerHandle);
	if (!Broker || !Broker->bSharesAbilityCooldowns
		|| !Broker->Members.Contains(OwnerEntity)) return;

	TArray<FSeinEntityHandle> Members = Broker->Members;
	Members.Sort();
	FSeinEntityHandle Previous;
	for (const FSeinEntityHandle Member : Members)
	{
		if (Member == Previous) continue;
		Previous = Member;
		if (Member == OwnerEntity || !WorldSubsystem->IsEntityAlive(Member)) continue;
		const FSeinBrokerMembershipData* MemberMembership =
			WorldSubsystem->GetComponent<FSeinBrokerMembershipData>(Member);
		if (!MemberMembership || MemberMembership->CurrentBrokerHandle != BrokerHandle) continue;
		const FSeinAbilityPayload* Abilities =
			WorldSubsystem->GetComponent<FSeinAbilityPayload>(Member);
		if (!Abilities) continue;
		if (USeinAbility* Recipient = Abilities->FindAbilityByTag(*WorldSubsystem, AbilityTag))
		{
			if (Recipient->OwnerEntity != Member) continue;
			Recipient->MarkDeterministicStateDirty();
			Recipient->CooldownRemaining = Cooldown;
			Recipient->CooldownSourceActivationID = AbilityActivationID;
			CooldownRecipientIDs.Add(Recipient->GetRuntimePoolID());
		}
	}
}

void USeinAbility::RefundCooldownInternal()
{
	// A later activation may have overwritten even our local cooldown.
	if (CooldownSourceActivationID == AbilityActivationID)
	{
		CooldownRemaining = FFixedPoint::Zero;
		CooldownSourceActivationID = 0;
	}
	for (const int32 RecipientID : CooldownRecipientIDs)
	{
		USeinAbility* Recipient = WorldSubsystem->GetAbilityInstance(RecipientID);
		if (Recipient && Recipient->CooldownSourceActivationID == AbilityActivationID)
		{
			Recipient->MarkDeterministicStateDirty();
			Recipient->CooldownRemaining = FFixedPoint::Zero;
			Recipient->CooldownSourceActivationID = 0;
		}
	}
}

TArray<FName> USeinAbility::GetActivationInputNames() const
{
	const USeinAbility* Defaults = GetClass()->GetDefaultObject<USeinAbility>();
	TArray<FName> Names = Defaults->NativeActivationInputNames;
#if WITH_EDITOR
	for (TFieldIterator<FProperty> It(GetClass(), EFieldIterationFlags::IncludeSuper); It; ++It)
	{
		if (It->GetBoolMetaData(TEXT("SeinExposeOnActivate"))) Names.AddUnique(It->GetFName());
	}
#else
	for (FName Name : Defaults->ActivationInputNames) Names.AddUnique(Name);
#endif
	Names.Sort(FNameLexicalLess());
	return Names;
}

void USeinAbility::Serialize(FArchive& Ar)
{
#if WITH_EDITOR
	if (Ar.IsSaving() && HasAnyFlags(RF_ClassDefaultObject)) ActivationInputNames = GetActivationInputNames();
#endif
	Super::Serialize(Ar);
}

#if WITH_EDITOR
void USeinAbility::PostCDOCompiled(const FPostCDOCompiledContext& Context)
{
	Super::PostCDOCompiled(Context);
	ActivationInputNames = GetActivationInputNames();
}
#endif
