/**
 * SeinARTS Framework
 * Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file:		SeinAbility.cpp
 * @date:		4/3/2026
 * @author:		RJ Macklem
 * @brief:		Base ability class implementation. Tracks activation/cancel
 *				lifecycle including cost refund + cooldown timing per
 *				DESIGN §7 Q2a / Q3c / Q4c. Cost-deduct happens on the caller
 *				side (ProcessCommands::ActivateAbility); this class consumes
 *				the deduct snapshot via RecordDeductedCost.
 * @disclaimer: This code was generated in part by an AI language model.
 */

#include "Abilities/SeinAbility.h"
#include "Simulation/SeinWorldSubsystem.h"
#include "Abilities/SeinLatentActionManager.h"
#include "Lib/SeinResourceBPFL.h"
#include "Components/SeinProductionComponent.h"
#include "Components/SeinSquadComponent.h"
#include "Components/SeinSquadMemberComponent.h"
#include "Components/SeinAbilityComponent.h"
#include "Components/SeinIdentityComponent.h"
#include "Components/SeinProducibleComponent.h"
#include "Actor/SeinEntityComponent.h"
#include "Events/SeinVisualEvent.h"
#include "Effects/SeinEffect.h"
#include "Actor/SeinActor.h"
#include "Core/SeinAssetTagKeys.h"
#include "Core/SeinSimContext.h"
#include "UObject/AssetRegistryTagsContext.h"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAbilityImpl, Log, All);

#if WITH_EDITOR
void USeinAbility::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);
	const FName ChangedName = PropertyChangedEvent.Property
		? PropertyChangedEvent.Property->GetFName()
		: NAME_None;
	if (ChangedName == GET_MEMBER_NAME_CHECKED(USeinAbility, AbilityTag))
	{
		// Designer edited the tag manually — surrender provenance ownership
		// so the auto-tag-generation pipeline leaves this BP alone on future
		// renames + regenerate-all passes.
		bAutoGeneratedTag = false;
	}
}
#endif

void USeinAbility::GetAssetRegistryTags(FAssetRegistryTagsContext Context) const
{
	Super::GetAssetRegistryTags(Context);

	// Surface AbilityTag onto the asset's FAssetData so the editor auto-tag
	// collision check reads it without loading this CDO. Bare ToString() form so
	// a string compare against another tag's ToString() is a valid equality test.
	if (AbilityTag.IsValid())
	{
		Context.AddTag(FAssetRegistryTag(
			SeinAssetTagKeys::AbilityTag(),
			AbilityTag.ToString(),
			FAssetRegistryTag::TT_Alphabetical));
	}
}

void USeinAbility::ResolveActivationCosts(
	const UObject* WorldContextObject,
	FSeinResourceCost& OutActivationCost,
	FSeinResourceCost& OutProductionCompletionCost) const
{
	OutProductionCompletionCost.Amounts.Reset();
	if (CostTiming == ESeinAbilityCostTiming::ProductionQueue)
	{
		USeinResourceBPFL::SeinSplitCostByCatalog(
			WorldContextObject, ResourceCost,
			OutActivationCost, OutProductionCompletionCost);
		return;
	}

	// Immediate is also the fail-safe for an invalid serialized enum value.
	OutActivationCost = ResourceCost;
}

void USeinAbility::EnqueueProduction(TSubclassOf<ASeinActor> ProducibleClass)
{
	if (!WorldSubsystem)
	{
		UE_LOG(LogSeinAbilityImpl, Warning, TEXT("EnqueueProduction[%s]: ability has no WorldSubsystem"),
			*GetName());
		return;
	}
	if (!SeinIsInSimContext(WorldSubsystem))
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("EnqueueProduction rejected outside this world's simulation context for %s"),
			*GetName());
		return;
	}
	if (!ResourcePayer.IsValid())
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: no unconsumed activation funding snapshot"),
			*GetName());
		return;
	}
	const auto RollBackFailedEnqueue = [this]()
	{
		if (!DeductedCost.IsEmpty() && ResourcePayer.IsValid())
		{
			USeinResourceBPFL::SeinRefund(
				WorldSubsystem, ResourcePayer, DeductedCost);
		}
		DeductedCost.Amounts.Empty();
		PendingCompletionCost.Amounts.Empty();
		ResourcePayer = FSeinPlayerID::Neutral();
	};
	if (!ProducibleClass)
	{
		UE_LOG(LogSeinAbilityImpl, Warning, TEXT("EnqueueProduction[%s]: null ProducibleClass"),
			*GetName());
		RollBackFailedEnqueue();
		return;
	}

	FSeinProductionComponent* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionComponent>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: owner %s has no FSeinProductionComponent"),
			*GetName(), *OwnerEntity.ToString());
		RollBackFailedEnqueue();
		return;
	}
	if (!ProdComp->CanQueueMore())
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: owner %s queue full (max=%d)"),
			*GetName(), *OwnerEntity.ToString(), ProdComp->MaxQueueSize);
		RollBackFailedEnqueue();
		return;
	}

	// Producible's authoring lives on the producible class's entity bridge —
	// FSeinProducibleComponent (BuildTime / RefundPolicy / research metadata)
	// and FSeinIdentityComponent (IdentityTag for the production visual
	// event). Both are FInstancedStruct entries in
	// `USeinEntityComponent::ComponentData` on the BP CDO.
	const FSeinProducibleComponent* Producible = nullptr;
	const FSeinIdentityComponent* Identity = nullptr;
	{
		TArray<const USeinEntityComponent*> Bridges;
		AActor::GetActorClassDefaultComponents<USeinEntityComponent>(ProducibleClass, Bridges);
		for (const USeinEntityComponent* Bridge : Bridges)
		{
			if (!Bridge) continue;
			if (!Producible) Producible = Bridge->FindAuthoredData<FSeinProducibleComponent>();
			if (!Identity)   Identity   = Bridge->FindAuthoredData<FSeinIdentityComponent>();
		}
	}
	if (!Producible)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: producible %s has no FSeinProducibleComponent on its entity bridge; skipping"),
			*GetName(), *ProducibleClass->GetName());
		RollBackFailedEnqueue();
		return;
	}
	UClass* ResearchEffectClass = Producible->GrantedTechEffect.Get();
	if (Producible->bIsResearch
		&& (!ResearchEffectClass
			|| ResearchEffectClass->HasAnyClassFlags(CLASS_Abstract)
			|| !GetDefault<USeinEffect>(ResearchEffectClass)))
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("EnqueueProduction[%s]: research producible %s has no usable GrantedTechEffect"),
			*GetName(), *ProducibleClass->GetName());
		RollBackFailedEnqueue();
		return;
	}

	// The activation snapshot is already policy-resolved. Immediate abilities
	// transfer the full deducted cost and no completion cost; Production Queue
	// abilities transfer the catalog split.
	FSeinProductionQueueEntry Entry;
	Entry.ActorClass = ProducibleClass;
	Entry.TotalBuildTime = Producible->BuildTime;
	Entry.AtEnqueueCost = DeductedCost;
	Entry.AtCompletionCost = PendingCompletionCost;
	Entry.ResourcePayer = ResourcePayer;
	Entry.bIsResearch = Producible->bIsResearch;
	Entry.ResearchEffectClass = Producible->GrantedTechEffect;
	Entry.RefundPolicy = Producible->RefundPolicy;

	const bool bWasEmpty = ProdComp->Queue.Num() == 0;
	ProdComp->Queue.Add(MoveTemp(Entry));

	// Economic ownership has transferred to the queue entry. The ability must
	// not retain a second refundable copy if its graph is cancelled afterward.
	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();

	UE_LOG(LogSeinAbilityImpl, Verbose,
		TEXT("EnqueueProduction[%s]: queued %s on %s (build=%.2fs, queue depth=%d)"),
		*GetName(), *ProducibleClass->GetName(), *OwnerEntity.ToString(),
		Producible->BuildTime.ToFloat(), ProdComp->Queue.Num());

	if (bWasEmpty)
	{
		ProdComp->CurrentBuildProgress = FFixedPoint::Zero;
		ProdComp->bStalledAtCompletion = false;
		const FGameplayTag IdentityTag = Identity ? Identity->IdentityTag : FGameplayTag();
		WorldSubsystem->EnqueueVisualEvent(FSeinVisualEvent::MakeProductionEvent(
			OwnerEntity, IdentityTag, /*bCompleted=*/false));
	}
}

void USeinAbility::SetRallyPoint(const FFixedTransform& Transform)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilitySetRallyPoint")))
	{
		return;
	}
	FSeinProductionComponent* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionComponent>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("SetRallyPoint[%s]: owner %s has no FSeinProductionComponent"),
			*GetName(), *OwnerEntity.ToString());
		return;
	}
	ProdComp->bRallyToEntity = false;
	ProdComp->RallyTransform = Transform;
	ProdComp->RallyEntity = FSeinEntityHandle();
}

void USeinAbility::SetRallyEntity(FSeinEntityHandle RallyEntity)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilitySetRallyEntity")))
	{
		return;
	}
	FSeinProductionComponent* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionComponent>(OwnerEntity);
	if (!ProdComp)
	{
		UE_LOG(LogSeinAbilityImpl, Warning,
			TEXT("SetRallyEntity[%s]: owner %s has no FSeinProductionComponent"),
			*GetName(), *OwnerEntity.ToString());
		return;
	}
	ProdComp->bRallyToEntity = true;
	ProdComp->RallyEntity = RallyEntity;
	ProdComp->RallyTransform = FFixedTransform();
}

void USeinAbility::ClearRallyPoint()
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("AbilityClearRallyPoint")))
	{
		return;
	}
	FSeinProductionComponent* ProdComp =
		WorldSubsystem->GetComponentMutable<
			FSeinProductionComponent>(OwnerEntity);
	if (!ProdComp) return;
	ProdComp->bRallyToEntity = false;
	ProdComp->RallyTransform = FFixedTransform();
	ProdComp->RallyEntity = FSeinEntityHandle();
}

void USeinAbility::InitializeAbility(FSeinEntityHandle Owner, USeinWorldSubsystem* Subsystem)
{
	OwnerEntity = Owner;
	WorldSubsystem = Subsystem;
	RuntimePoolID = INDEX_NONE;
	CooldownRemaining = FFixedPoint::Zero;
	bIsActive = false;
	AbilityActivationID = 0;
	bCooldownStarted = false;
	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();
	CommittedGrantedTags.Reset();
}

UWorld* USeinAbility::GetWorld() const
{
	// Skip during CDO construction — UObject systems probe GetWorld() while
	// laying out the class default object, before any subsystem is bound. The
	// nullptr return matches the UObject default for CDOs.
	if (HasAnyFlags(RF_ClassDefaultObject)) { return nullptr; }
	return WorldSubsystem ? WorldSubsystem->GetWorld() : nullptr;
}

bool USeinAbility::CanCommitGrantedTags() const
{
	if (!WorldSubsystem)
	{
		return true;
	}
	const bool bWillReleaseCurrentOwnership = bIsActive
		&& GrantedTags.HasAny(CancelAbilitiesWithTag);
	if (bIsActive && !bWillReleaseCurrentOwnership)
	{
		return false;
	}
	for (const FGameplayTag& Tag : GrantedTags)
	{
		if (!WorldSubsystem->CanGrantTag(OwnerEntity, Tag)
			&& !(bWillReleaseCurrentOwnership
				&& CommittedGrantedTags.HasTagExact(Tag)))
		{
			return false;
		}
	}
	return true;
}

bool USeinAbility::AcquireGrantedTags()
{
	CommittedGrantedTags.Reset();
	if (!WorldSubsystem)
	{
		return true;
	}
	for (const FGameplayTag& Tag : GrantedTags)
	{
		if (!WorldSubsystem->GrantTag(OwnerEntity, Tag))
		{
			ReleaseCommittedGrantedTags();
			return false;
		}
		CommittedGrantedTags.AddTag(Tag);
	}
	return true;
}

void USeinAbility::ReleaseCommittedGrantedTags()
{
	if (WorldSubsystem)
	{
		for (const FGameplayTag& Tag : CommittedGrantedTags)
		{
			WorldSubsystem->UngrantTag(OwnerEntity, Tag);
		}
	}
	CommittedGrantedTags.Reset();
}

bool USeinAbility::ActivateAbility(FSeinEntityHandle Target, FFixedVector Location)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("ActivateAbility")))
	{
		return false;
	}
	if (bIsActive)
	{
		return false;
	}
	if (!AcquireGrantedTags())
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: refused because an owned tag is saturated on %s"),
			*GetName(), *OwnerEntity.ToString());
		return false;
	}
	int64 NewActivationID = 0;
	if (!WorldSubsystem->TryAllocateAbilityActivationID(NewActivationID))
	{
		ReleaseCommittedGrantedTags();
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: deterministic activation ID space is exhausted."),
			*GetName());
		return false;
	}

	// Right-click / direct-activation path — no targeter points captured.
	// Empty TargeterPoints array signals "trigger came from the smart-command
	// flow" to OnActivate; ability reads TargetLocation alone.
	TargeterPoints.Reset();
	TargetEntity = Target;
	TargetLocation = Location;
	AbilityActivationID = NewActivationID;
	bIsActive = true;

	// Start cooldown if the ability's timing fires on activate. OnEnd-timed abilities
	// defer cooldown until DeactivateAbility.
	if (CooldownStartTiming == ESeinCooldownStartTiming::OnActivate)
	{
		StartCooldownInternal();
	}

	OnActivate();
	return true;
}

bool USeinAbility::ActivateAbilityWithTargeterPoints(FSeinEntityHandle Target, FFixedVector Location,
	const TArray<FSeinTargeterPoint>& Points)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(
			TEXT("ActivateAbilityWithTargeterPoints")))
	{
		return false;
	}
	if (bIsActive)
	{
		return false;
	}
	if (!AcquireGrantedTags())
	{
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: refused because an owned tag is saturated on %s"),
			*GetName(), *OwnerEntity.ToString());
		return false;
	}
	int64 NewActivationID = 0;
	if (!WorldSubsystem->TryAllocateAbilityActivationID(NewActivationID))
	{
		ReleaseCommittedGrantedTags();
		UE_LOG(LogSeinAbilityImpl, Error,
			TEXT("ActivateAbility[%s]: deterministic activation ID space is exhausted."),
			*GetName());
		return false;
	}

	// Targeter-originated activation. TargetLocation mirrors Points[0].Location
	// when available so single-point ability OnActivate logic that only reads
	// TargetLocation continues to work — multi-target abilities iterate
	// TargeterPoints directly.
	TargeterPoints = Points;
	TargetEntity = Target;
	TargetLocation = Points.Num() > 0 ? Points[0].Location : Location;
	AbilityActivationID = NewActivationID;
	bIsActive = true;

	if (CooldownStartTiming == ESeinCooldownStartTiming::OnActivate)
	{
		StartCooldownInternal();
	}

	OnActivate();
	return true;
}

void USeinAbility::TickAbility(FFixedPoint DeltaTime)
{
	if (bIsActive)
	{
		OnTick(DeltaTime);
	}
}

void USeinAbility::DeactivateAbility(bool bCancelled)
{
	if (!WorldSubsystem
		|| !WorldSubsystem->RequireStateMutationAuthorization(TEXT("DeactivateAbility")))
	{
		return;
	}
	if (!bIsActive)
	{
		return;
	}

	bIsActive = false;

	// Refund on cancel ─ drive DESIGN §7 Q2a / Q3c policy
	if (bCancelled && WorldSubsystem)
	{
		if (bRefundCostOnCancel && !DeductedCost.IsEmpty())
		{
			USeinResourceBPFL::SeinRefund(WorldSubsystem, ResourcePayer, DeductedCost);
		}
		if (bRefundCooldownOnCancel && bCooldownStarted)
		{
			CooldownRemaining = FFixedPoint::Zero;
		}
	}
	// Start cooldown on natural end when timing is OnEnd and not already running
	else if (!bCancelled && CooldownStartTiming == ESeinCooldownStartTiming::OnEnd && !bCooldownStarted)
	{
		StartCooldownInternal();
	}

	// Tear down any latent actions belonging to this ability. Without this,
	// actions like SeinMoveTo linger after EndAbility/CancelAbility and keep
	// ticking against a logically-inactive ability.
	if (WorldSubsystem && WorldSubsystem->LatentActionManager)
	{
		WorldSubsystem->LatentActionManager->CancelActionsForAbility(this);
	}

	ReleaseCommittedGrantedTags();

	DeductedCost.Amounts.Empty();
	PendingCompletionCost.Amounts.Empty();
	ResourcePayer = FSeinPlayerID::Neutral();

	// Clear captured targeter points so a subsequent right-click activation
	// doesn't see stale data from the prior targeter cast.
	TargeterPoints.Reset();

	OnEnd(bCancelled);
}

void USeinAbility::EndAbility()
{
	DeactivateAbility(false);
}

void USeinAbility::CancelAbility()
{
	DeactivateAbility(true);
}

void USeinAbility::TickCooldown(FFixedPoint DeltaTime)
{
	if (CooldownRemaining > FFixedPoint::Zero)
	{
		CooldownRemaining = CooldownRemaining - DeltaTime;
		if (CooldownRemaining < FFixedPoint::Zero)
		{
			CooldownRemaining = FFixedPoint::Zero;
		}
	}
}

bool USeinAbility::IsOnCooldown() const
{
	return CooldownRemaining > FFixedPoint::Zero;
}

void USeinAbility::StartCooldownInternal()
{
	// Always set local cooldown.
	CooldownRemaining = Cooldown;
	bCooldownStarted = true;

	// Squad-scope propagation: if the activator is a squad member AND this
	// ability is squad-scope-cooldown, mirror the cooldown to every squadmate's
	// instance of this ability tag. Member-scope abilities, lone (non-squad)
	// activators, and zero-cooldown abilities all skip this branch.
	if (CooldownScope != ESeinCooldownScope::Squad) return;
	if (Cooldown <= FFixedPoint::Zero) return;
	if (!WorldSubsystem) return;

	const FSeinSquadMemberComponent* MemberData = WorldSubsystem->GetComponent<FSeinSquadMemberComponent>(OwnerEntity);
	if (!MemberData || !MemberData->SquadEntity.IsValid()) return;

	const FSeinSquadComponent* Squad = WorldSubsystem->GetComponent<FSeinSquadComponent>(MemberData->SquadEntity);
	if (!Squad) return;

	for (const FSeinSquadSlot& Slot : Squad->Slots)
	{
		const FSeinEntityHandle Mate = Slot.CurrentOccupant;
		if (!Mate.IsValid() || Mate == OwnerEntity) continue;

		const FSeinAbilityComponent* MateAC = WorldSubsystem->GetComponent<FSeinAbilityComponent>(Mate);
		if (!MateAC) continue;

		if (USeinAbility* MateInstance = MateAC->FindAbilityByTag(*WorldSubsystem, AbilityTag))
		{
			MateInstance->CooldownRemaining = Cooldown;
			MateInstance->bCooldownStarted = true;
		}
	}
}
