/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinCanonicalStatePropertyPolicy.cpp
 */

#include "Serialization/SeinCanonicalStatePropertyPolicy.h"
#include "UObject/TextProperty.h"

#include "Abilities/SeinAbility.h"
#include "Abilities/SeinTargeterSpec.h"
#include "GameplayTagContainer.h"
#include "UObject/UnrealType.h"

namespace
{
	bool IsGameplayTagQueryDescription(const FProperty& Property)
	{
		if (Property.GetOwnerStruct()
			!= FGameplayTagQuery::StaticStruct())
		{
			return false;
		}
		const FName Name = Property.GetFName();
		return Name == TEXT("UserDescription")
			|| Name == TEXT("AutoDescription");
	}
}

bool FSeinCanonicalStatePropertyPolicy::ShouldSkip(
	const FProperty& Property)
{
	if (Property.HasAnyPropertyFlags(
			CPF_Transient | CPF_EditorOnly | CPF_Deprecated
				| CPF_SkipSerialization)
		|| Property.IsA<FTextProperty>()
		|| IsGameplayTagQueryDescription(Property))
	{
		return true;
	}

	const UStruct* Owner = Property.GetOwnerStruct();
	const FName Name = Property.GetFName();
	if (Owner == USeinAbility::StaticClass())
	{
		return Name
				== GET_MEMBER_NAME_CHECKED(
					USeinAbility, bAutoGeneratedTag)
			|| Name
				== GET_MEMBER_NAME_CHECKED(
					USeinAbility, Icon);
	}
	if (Owner == USeinTargeterSpec::StaticClass())
	{
		return Name
				== GET_MEMBER_NAME_CHECKED(
					USeinTargeterSpec, PreviewClass)
			|| Name
				== GET_MEMBER_NAME_CHECKED(
					USeinTargeterSpec,
					bRejectClickWhenBlocked);
	}
	if (Owner == USeinPointFacingTargeterSpec::StaticClass())
	{
		return Name
			== GET_MEMBER_NAME_CHECKED(
				USeinPointFacingTargeterSpec,
				PreviewMeshOverride);
	}
	return false;
}
