/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file         K2Node_SeinAbilityInputs.cpp
 * @author       RJ Macklem
 * @created      12 Sep 2026
 * @latest       12 Sep 2026
 * @brief        Compiles activation pins into bounded input construction and submission.
 *
 * @disclaimer   Generated with assistance from an AI language model.
 */
#include "Graph/K2Node_SeinAbilityInputs.h"
#include "Abilities/SeinAbility.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetCompiler.h"
#include "Lib/SeinAbilityInputBPFL.h"
#include "Lib/SeinPlayerAbilityBPFL.h"
#include "Player/SeinPlayerController.h"
#include "UObject/UnrealType.h"

namespace
{
	FName InputPin(FName Name) { return FName(*(TEXT("Input_") + Name.ToString())); }
}

void UK2Node_SeinAbilityInputs::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	if (Operation)
	{
		CreatePin(EGPD_Input, Schema->PC_Exec, Schema->PN_Execute);
		CreatePin(EGPD_Output, Schema->PC_Exec, Schema->PN_Then);
		if (Operation == 1) CreatePin(EGPD_Input, Schema->PC_Object, ASeinPlayerController::StaticClass(), TEXT("PC"));
		else CreatePin(EGPD_Input, Schema->PC_Object, UObject::StaticClass(), TEXT("WorldContextObject"))->bHidden = true;
		CreatePin(EGPD_Input, Schema->PC_Struct, FSeinEntityHandle::StaticStruct(), TEXT("Entity"));
		CreatePin(EGPD_Input, Schema->PC_Struct, FSeinEntityHandle::StaticStruct(), TEXT("TargetEntity"));
		CreatePin(EGPD_Input, Schema->PC_Struct, FFixedVector::StaticStruct(), TEXT("TargetLocation"));
		CreatePin(EGPD_Output, Schema->PC_Boolean, TEXT("ReturnValue"));
	}
	else CreatePin(EGPD_Output, Schema->PC_Struct, FSeinAbilityActivationInputs::StaticStruct(), TEXT("ReturnValue"));
	UEdGraphPin* ClassPin = CreatePin(EGPD_Input, Schema->PC_Class, USeinAbility::StaticClass(), TEXT("AbilityClass"));
	ClassPin->DefaultObject = AbilityClass;
	ClassPin->bNotConnectable = true;
	if (!AbilityClass || !AbilityClass->IsChildOf(USeinAbility::StaticClass())) return;
	FString SchemaError;
	FSeinAbilityActivationInputs::ComputeSchemaDigest(AbilityClass, InputSchema, SchemaError);
	const USeinAbility* Defaults = AbilityClass->GetDefaultObject<USeinAbility>();
	for (FName Name : Defaults->GetActivationInputNames())
	{
		FProperty* Property = FindFProperty<FProperty>(AbilityClass, Name);
		FEdGraphPinType Type;
		if (!Property || !Schema->ConvertPropertyToPinType(Property, Type)) continue;
		UEdGraphPin* Pin = CreatePin(EGPD_Input, Type, InputPin(Name));
		if (UBlueprint* Owner = Cast<UBlueprint>(Property->GetOwnerClass()->ClassGeneratedBy))
			Pin->PersistentGuid = FBlueprintEditorUtils::FindMemberVariableGuidByName(Owner, Name);
		Pin->PinFriendlyName = Property->GetDisplayNameText();
		Pin->PinToolTip = Property->GetToolTipText().ToString();
		FString Default;
		if (FBlueprintEditorUtils::PropertyValueToString(Property, reinterpret_cast<const uint8*>(Defaults), Default, this))
			Schema->SetPinAutogeneratedDefaultValue(Pin, Default);
	}
}

void UK2Node_SeinAbilityInputs::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	AllocateDefaultPins();
	RestoreSplitPins(OldPins);
}

void UK2Node_SeinAbilityInputs::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == TEXT("AbilityClass"))
	{
		AbilityClass = Cast<UClass>(Pin->DefaultObject);
		ReconstructNode();
		FBlueprintEditorUtils::MarkBlueprintAsModified(GetBlueprint());
	}
}

FText UK2Node_SeinAbilityInputs::GetNodeTitle(ENodeTitleType::Type) const
{
	return FText::FromString(Operation == 0 ? TEXT("Make Ability Inputs") : Operation == 1 ? TEXT("Activate Ability") : TEXT("Issue Ability"));
}
FText UK2Node_SeinAbilityInputs::GetMenuCategory() const { return NSLOCTEXT("SeinAbilityInputs", "Category", "SeinARTS|Ability"); }
FText UK2Node_SeinAbilityInputs::GetTooltipText() const
{
	return NSLOCTEXT("SeinAbilityInputs", "Tooltip", "Select an ability to expose its activation variables. Each request captures its own values. Activate Ability accepts player input; Issue Ability chains from simulation callbacks.");
}
FBlueprintNodeSignature UK2Node_SeinAbilityInputs::GetSignature() const
{
	FBlueprintNodeSignature Signature = Super::GetSignature();
	Signature.AddNamedValue(TEXT("Operation"), FString::FromInt(Operation));
	return Signature;
}

void UK2Node_SeinAbilityInputs::GetMenuActions(FBlueprintActionDatabaseRegistrar& Registrar) const
{
	if (!Registrar.IsOpenForRegistration(GetClass())) return;
	for (uint8 Mode = 0; Mode < 3; ++Mode)
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
		Spawner->CustomizeNodeDelegate = UBlueprintNodeSpawner::FCustomizeNodeDelegate::CreateLambda(
			[Mode](UEdGraphNode* Node, bool) { CastChecked<UK2Node_SeinAbilityInputs>(Node)->Operation = Mode; });
		Registrar.AddBlueprintAction(GetClass(), Spawner);
	}
}
bool UK2Node_SeinAbilityInputs::HasExternalDependencies(TArray<UStruct*>* Output) const
{
	if (AbilityClass && Output) Output->AddUnique(AbilityClass);
	return Super::HasExternalDependencies(Output) || AbilityClass != nullptr;
}

void UK2Node_SeinAbilityInputs::ExpandNode(FKismetCompilerContext& Compiler, UEdGraph* Graph)
{
	Super::ExpandNode(Compiler, Graph);
	FString Error;
	if (!FSeinAbilityActivationInputs::ValidateClass(AbilityClass, Error))
	{
		Compiler.MessageLog.Error(*FString::Printf(TEXT("@@: %s"), *Error), this);
		BreakAllNodeLinks();
		return;
	}
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	auto Call = [&](FName Name)
	{
		UK2Node_CallFunction* Node = Compiler.SpawnIntermediateNode<UK2Node_CallFunction>(this, Graph);
		Node->FunctionReference.SetExternalMember(Name, Name == TEXT("SubmitAbility")
			? USeinPlayerAbilityBPFL::StaticClass() : USeinAbilityInputBPFL::StaticClass());
		Node->AllocateDefaultPins();
		if (UEdGraphPin* ClassPin = Node->FindPin(TEXT("AbilityClass"))) ClassPin->DefaultObject = AbilityClass;
		return Node;
	};
	UK2Node_CallFunction* Make = Call(GET_FUNCTION_NAME_CHECKED(USeinAbilityInputBPFL, MakeInputs));
	UEdGraphPin* Values = Make->GetReturnValuePin();
	for (FName Name : AbilityClass->GetDefaultObject<USeinAbility>()->GetActivationInputNames())
	{
		UEdGraphPin* Source = FindPin(InputPin(Name));
		FEdGraphPinType ExpectedType;
		FProperty* Property = FindFProperty<FProperty>(AbilityClass, Name);
		if (!Source || !Schema->ConvertPropertyToPinType(Property, ExpectedType) || Source->PinType != ExpectedType)
		{
			Compiler.MessageLog.Error(TEXT("@@ has stale activation pins. Refresh this node."), this);
			BreakAllNodeLinks();
			return;
		}
		if (Source->LinkedTo.IsEmpty() && !Schema->PinDefaultValueIsEditable(*Source)) continue;
		UK2Node_CallFunction* Set = Call(GET_FUNCTION_NAME_CHECKED(USeinAbilityInputBPFL, SetInput));
		Set->FindPinChecked(TEXT("Name"))->DefaultValue = Name.ToString();
		FGuid CompiledSchema;
		FSeinAbilityActivationInputs::ComputeSchemaDigest(AbilityClass, CompiledSchema, Error);
		TBaseStructure<FGuid>::Get()->ExportText(Set->FindPinChecked(TEXT("CompiledSchema"))->DefaultValue,
			&CompiledSchema, nullptr, nullptr, PPF_None, nullptr);
		UEdGraphPin* Value = Set->FindPinChecked(TEXT("Value"));
		Value->PinType = Source->PinType;
		Compiler.MovePinLinksToIntermediate(*Source, *Value);
		Schema->TryCreateConnection(Values, Set->FindPinChecked(TEXT("Inputs")));
		Values = Set->GetReturnValuePin();
	}
	if (!Operation) Compiler.MovePinLinksToIntermediate(*FindPinChecked(TEXT("ReturnValue")), *Values);
	else
	{
		UK2Node_CallFunction* Submit = Call(Operation == 1
			? GET_FUNCTION_NAME_CHECKED(USeinPlayerAbilityBPFL, SubmitAbility)
			: GET_FUNCTION_NAME_CHECKED(USeinAbilityInputBPFL, IssueAbility));
		Schema->TryCreateConnection(Values, Submit->FindPinChecked(TEXT("Inputs")));
		FGameplayTag Tag = AbilityClass->GetDefaultObject<USeinAbility>()->AbilityTag;
		if (!Tag.IsValid()) Compiler.MessageLog.Error(TEXT("@@ requires an ability with a valid Ability Tag."), this);
		FGameplayTag::StaticStruct()->ExportText(Submit->FindPinChecked(TEXT("AbilityTag"))->DefaultValue,
			&Tag, nullptr, nullptr, PPF_None, nullptr);
		for (const FName Name : {Schema->PN_Execute, Schema->PN_Then, (Operation == 1 ? FName(TEXT("PC")) : FName(TEXT("WorldContextObject"))), FName(TEXT("Entity")),
			FName(TEXT("TargetEntity")), FName(TEXT("TargetLocation")), FName(TEXT("ReturnValue"))})
			Compiler.MovePinLinksToIntermediate(*FindPinChecked(Name), *Submit->FindPinChecked(Name));
	}
	BreakAllNodeLinks();
}

bool UK2Node_SeinAbilityInputs::RefreshInputPins()
{
	if (!AbilityClass) return false;
	AbilityClass = AbilityClass->GetAuthoritativeClass();
	FGuid Current;
	FString Error;
	if (!FSeinAbilityActivationInputs::ComputeSchemaDigest(AbilityClass, Current, Error)) return false;
	if (Current != InputSchema)
	{
		ReconstructNode();
		FBlueprintEditorUtils::MarkBlueprintAsModified(GetBlueprint());
		return true;
	}
	// Default edits do not change the type schema. Update untouched pins while
	// preserving literal overrides entered on the caller.
	bool Changed = false;
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	const USeinAbility* Defaults = AbilityClass->GetDefaultObject<USeinAbility>();
	for (FName Name : Defaults->GetActivationInputNames())
	{
		UEdGraphPin* Pin = FindPin(InputPin(Name));
		FProperty* Property = FindFProperty<FProperty>(AbilityClass, Name);
		FString Value;
		if (!Pin || !Property || !FBlueprintEditorUtils::PropertyValueToString(
			Property, reinterpret_cast<const uint8*>(Defaults), Value, this) || Pin->AutogeneratedDefaultValue == Value) continue;
		const bool UsesDefault = Schema->DoesDefaultValueMatchAutogenerated(*Pin);
		Pin->AutogeneratedDefaultValue = Value;
		if (UsesDefault) Schema->ResetPinToAutogeneratedDefaultValue(Pin, false);
		Changed = true;
	}
	if (Changed)
	{
		GetGraph()->NotifyNodeChanged(this);
		FBlueprintEditorUtils::MarkBlueprintAsModified(GetBlueprint());
	}
	return Changed;
}

UK2Node::ERedirectType UK2Node_SeinAbilityInputs::DoPinsMatchForReconstruction(
	const UEdGraphPin* NewPin, int32 NewIndex, const UEdGraphPin* OldPin, int32 OldIndex) const
{
	if (NewPin->PersistentGuid.IsValid() && NewPin->PersistentGuid == OldPin->PersistentGuid
		&& NewPin->PinType == OldPin->PinType && NewPin->Direction == OldPin->Direction) return ERedirectType_Name;
	return Super::DoPinsMatchForReconstruction(NewPin, NewIndex, OldPin, OldIndex);
}
