/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinARTSCoreSettingsDetails.cpp
 */

#include "Details/SeinARTSCoreSettingsDetails.h"

#include "Util/SeinAutoTagGenerator.h"

#include "DetailCategoryBuilder.h"
#include "DetailLayoutBuilder.h"
#include "DetailWidgetRow.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/SBoxPanel.h"
#include "Misc/MessageDialog.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

TSharedRef<IDetailCustomization> FSeinARTSCoreSettingsDetails::MakeInstance()
{
	return MakeShared<FSeinARTSCoreSettingsDetails>();
}

void FSeinARTSCoreSettingsDetails::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	IDetailCategoryBuilder& TagCategory = DetailBuilder.EditCategory(
		TEXT("Tag Semantics"),
		FText::GetEmpty(),
		ECategoryPriority::Default);

	// --- Regenerate Auto-Generated Tags (non-destructive) ---
	TagCategory.AddCustomRow(LOCTEXT("RegenAutoRowFilter", "Regenerate Auto-Generated Tags"))
	.NameContent()
	[
		SNew(STextBlock)
		.Text(LOCTEXT("RegenAutoLabel", "Regenerate Auto-Generated Tags"))
		.Font(IDetailLayoutBuilder::GetDetailFont())
		.ToolTipText(LOCTEXT("RegenAutoTip",
			"Walks every SeinARTS Blueprint (Ability / Effect / Entity / Research) and re-derives its tag from the current asset name + settings. "
			"Only touches BPs whose bAutoGeneratedTag is true (designer-edited tags are preserved). "
			"Use this after changing TagPrefix, PrefixCategoryMappings, or AllowTagLayering."))
	]
	.ValueContent()
	[
		SNew(SButton)
		.HAlign(HAlign_Center)
		.OnClicked_Lambda([]() -> FReply
		{
			const int32 NumChanged = SeinAutoTag::RegenerateAllAssetTags(/*bForceOverManual*/ false);
			FMessageDialog::Open(EAppMsgType::Ok, FText::Format(
				LOCTEXT("RegenAutoDone", "Regenerated {0} auto-tagged asset(s).\n\nManually-edited tags (bAutoGeneratedTag = false) were skipped. Use Force Regenerate All to override."),
				FText::AsNumber(NumChanged)));
			return FReply::Handled();
		})
		[
			SNew(STextBlock).Text(LOCTEXT("RegenAutoBtn", "Regenerate Auto-Generated Tags"))
		]
	];

	// --- Force Regenerate All Tags (destructive, confirmation required) ---
	TagCategory.AddCustomRow(LOCTEXT("ForceRegenRowFilter", "Force Regenerate All Tags"))
	.NameContent()
	[
		SNew(STextBlock)
		.Text(LOCTEXT("ForceRegenLabel", "Force Regenerate All Tags"))
		.Font(IDetailLayoutBuilder::GetDetailFont())
		.ToolTipText(LOCTEXT("ForceRegenTip",
			"DESTRUCTIVE: Walks every SeinARTS Blueprint and overwrites its tag with one derived from the asset name — INCLUDING manually-authored tags. "
			"All affected BPs are marked with bAutoGeneratedTag = true after this runs. Use sparingly — designer-authored tag values that don't match the naming convention will be lost."))
	]
	.ValueContent()
	[
		SNew(SButton)
		.HAlign(HAlign_Center)
		.OnClicked_Lambda([]() -> FReply
		{
			const EAppReturnType::Type Result = FMessageDialog::Open(
				EAppMsgType::YesNo,
				LOCTEXT("ForceRegenConfirm",
					"This will overwrite EVERY SeinARTS Blueprint's tag with one derived from its asset name, "
					"including manually-authored tags. Proceed?"));
			if (Result != EAppReturnType::Yes) return FReply::Handled();

			const int32 NumChanged = SeinAutoTag::RegenerateAllAssetTags(/*bForceOverManual*/ true);
			FMessageDialog::Open(EAppMsgType::Ok, FText::Format(
				LOCTEXT("ForceRegenDone", "Force-regenerated {0} asset(s)."),
				FText::AsNumber(NumChanged)));
			return FReply::Handled();
		})
		[
			SNew(STextBlock).Text(LOCTEXT("ForceRegenBtn", "Force Regenerate All Tags"))
		]
	];
}

#undef LOCTEXT_NAMESPACE
