/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinAutoTagDetails.cpp
 */

#include "Details/SeinAutoTagDetails.h"

#include "Util/SeinAutoTagGenerator.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Components/SeinIdentityComponent.h"

#include "DetailCategoryBuilder.h"
#include "DetailLayoutBuilder.h"
#include "DetailWidgetRow.h"
#include "IDetailChildrenBuilder.h"
#include "PropertyHandle.h"
#include "Framework/Application/SlateApplication.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Notifications/SNotificationList.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/SBoxPanel.h"
#include "Engine/Blueprint.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

namespace SeinAutoTagDetailsLocal
{
	static void ShowRegenerationResult(
		const UBlueprint& Blueprint,
		const FSeinAutoTagRegenerationResult& Result)
	{
		if (!FSlateApplication::IsInitialized())
		{
			return;
		}

		FNotificationInfo Info(Result.ToUserMessage(&Blueprint));
		Info.ExpireDuration = Result.IsFailure() ? 8.0f : 4.0f;
		Info.bUseSuccessFailIcons = true;
		if (TSharedPtr<SNotificationItem> Item =
			FSlateNotificationManager::Get().AddNotification(Info))
		{
			Item->SetCompletionState(
				Result.IsFailure()
					? SNotificationItem::CS_Fail
					: SNotificationItem::CS_Success);
		}
	}

	/** Walk objects-being-customized back to the owning UBlueprint. CDOs are
	 *  typically what's customized; their outer is the UClass, whose
	 *  ClassGeneratedBy is the BP. */
	static UBlueprint* ResolveOwningBlueprint(IDetailLayoutBuilder& DetailBuilder)
	{
		TArray<TWeakObjectPtr<UObject>> Objects;
		DetailBuilder.GetObjectsBeingCustomized(Objects);
		for (const TWeakObjectPtr<UObject>& WeakObj : Objects)
		{
			UObject* Obj = WeakObj.Get();
			if (!Obj) continue;
			UClass* Cls = Obj->GetClass();
			if (Cls && Cls->ClassGeneratedBy)
			{
				return Cast<UBlueprint>(Cls->ClassGeneratedBy);
			}
		}
		return nullptr;
	}

	/** Build the "Reset to Auto" row widget. Click handler regenerates the
	 *  tag forcing over manual ownership (the user explicitly clicked to
	 *  hand the tag back to the auto-system). */
	static TSharedRef<SWidget> MakeResetButton(TWeakObjectPtr<UBlueprint> WeakBP)
	{
		return SNew(SHorizontalBox)
			+ SHorizontalBox::Slot()
			.AutoWidth()
			[
				SNew(SButton)
				.ToolTipText(LOCTEXT("ResetToAutoTooltip",
					"Regenerate this asset's tag from its name and set bAutoGeneratedTag = true. "
					"Use after manually editing the tag if you want the auto-tag-generation system to resume maintaining it on rename / Regenerate-Auto."))
				.OnClicked_Lambda([WeakBP]() -> FReply
				{
					if (UBlueprint* BP = WeakBP.Get())
					{
						const FSeinAutoTagRegenerationResult Result =
							SeinAutoTag::RegenerateAssetTagDetailed(
								BP,
								/*bForceOverManual=*/true);
						ShowRegenerationResult(*BP, Result);
					}
					return FReply::Handled();
				})
				[
					SNew(STextBlock).Text(LOCTEXT("ResetToAutoLabel", "Reset to Auto"))
				]
			];
	}

	/** Add a "Reset to Auto" row inside `Category`, hidden when no BP is
	 *  resolvable (defensive — the asset is being viewed without a Blueprint
	 *  context, e.g. native CDO). */
	static void AddResetRowToCategory(IDetailCategoryBuilder& Category, IDetailLayoutBuilder& DetailBuilder)
	{
		TWeakObjectPtr<UBlueprint> WeakBP = ResolveOwningBlueprint(DetailBuilder);
		if (!WeakBP.IsValid()) return;
		Category.AddCustomRow(LOCTEXT("ResetToAutoRowFilter", "Reset to Auto"))
		.NameContent()
		[
			SNew(STextBlock)
			.Text(LOCTEXT("AutoTagRowLabel", "Auto Tag"))
			.Font(IDetailLayoutBuilder::GetDetailFont())
		]
		.ValueContent()
		[
			MakeResetButton(WeakBP)
		];
	}
}

// ─────────────────────────────────────────────────────────────────────
// USeinAbility — adds "Reset to Auto" row in the SeinARTS|Ability category
// ─────────────────────────────────────────────────────────────────────

TSharedRef<IDetailCustomization> FSeinAbilityAutoTagDetails::MakeInstance()
{
	return MakeShared<FSeinAbilityAutoTagDetails>();
}

void FSeinAbilityAutoTagDetails::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	IDetailCategoryBuilder& AbilityCategory = DetailBuilder.EditCategory(TEXT("SeinARTS|Ability"));
	SeinAutoTagDetailsLocal::AddResetRowToCategory(AbilityCategory, DetailBuilder);
}

// ─────────────────────────────────────────────────────────────────────
// USeinEffect — adds "Reset to Auto" row in the SeinARTS|Effect category
// ─────────────────────────────────────────────────────────────────────

TSharedRef<IDetailCustomization> FSeinEffectAutoTagDetails::MakeInstance()
{
	return MakeShared<FSeinEffectAutoTagDetails>();
}

void FSeinEffectAutoTagDetails::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	IDetailCategoryBuilder& EffectCategory = DetailBuilder.EditCategory(TEXT("SeinARTS|Effect"));
	SeinAutoTagDetailsLocal::AddResetRowToCategory(EffectCategory, DetailBuilder);
}

// ─────────────────────────────────────────────────────────────────────
// FSeinIdentityComponent — property-type customization. Adds the Reset
// button as the last child row after the struct's authored fields.
// ─────────────────────────────────────────────────────────────────────

TSharedRef<IPropertyTypeCustomization> FSeinIdentityComponentAutoTagDetails::MakeInstance()
{
	return MakeShared<FSeinIdentityComponentAutoTagDetails>();
}

void FSeinIdentityComponentAutoTagDetails::CustomizeHeader(
	TSharedRef<IPropertyHandle> PropertyHandle,
	FDetailWidgetRow& HeaderRow,
	IPropertyTypeCustomizationUtils& /*CustomizationUtils*/)
{
	// Collapse the header row entirely. The FInstancedStruct customization
	// (`FSeinInstancedStructDetails`) that owns the outer "Index [N] → Sein
	// Identity Component" row already labels this entry; a second "Sein
	// Identity Component" header below it is redundant. EVisibility::Collapsed
	// removes the row from the layout. Children still render via
	// CustomizeChildren — UE's struct-customization pipeline doesn't gate
	// the children area on header visibility. (Mirrors the same fix on
	// FSeinCoverComponentDetails.)
	HeaderRow.Visibility(EVisibility::Collapsed);
}

void FSeinIdentityComponentAutoTagDetails::CustomizeChildren(
	TSharedRef<IPropertyHandle> PropertyHandle,
	IDetailChildrenBuilder& ChildBuilder,
	IPropertyTypeCustomizationUtils& /*CustomizationUtils*/)
{
	// Default-render every authored field — we just want to APPEND a button row.
	uint32 NumChildren = 0;
	PropertyHandle->GetNumChildren(NumChildren);
	for (uint32 i = 0; i < NumChildren; ++i)
	{
		TSharedPtr<IPropertyHandle> Child = PropertyHandle->GetChildHandle(i);
		if (Child.IsValid() && Child->GetProperty())
		{
			ChildBuilder.AddProperty(Child.ToSharedRef());
		}
	}

	// Resolve the owning BP via the property's owning object chain.
	TArray<UObject*> OuterObjects;
	PropertyHandle->GetOuterObjects(OuterObjects);
	UBlueprint* OwningBP = nullptr;
	for (UObject* Obj : OuterObjects)
	{
		if (!Obj) continue;
		UClass* Cls = Obj->GetClass();
		if (Cls && Cls->ClassGeneratedBy)
		{
			OwningBP = Cast<UBlueprint>(Cls->ClassGeneratedBy);
			if (OwningBP) break;
		}
	}
	if (!OwningBP) return;
	TWeakObjectPtr<UBlueprint> WeakBP = OwningBP;

	ChildBuilder.AddCustomRow(LOCTEXT("IdentityResetRowFilter", "Reset to Auto"))
	.NameContent()
	[
		SNew(STextBlock)
		.Text(LOCTEXT("AutoTagRowLabel2", "Auto Tag"))
		.Font(IDetailLayoutBuilder::GetDetailFont())
	]
	.ValueContent()
	[
		SeinAutoTagDetailsLocal::MakeResetButton(WeakBP)
	];
}

#undef LOCTEXT_NAMESPACE
