/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file         SeinSemanticDefault.h
 * @author       RJ Macklem
 * @created      4 Sep 2026
 * @latest       4 Sep 2026
 * @brief        Declares reset-to-default helpers for dynamically constructed
 *               SeinARTS authoring values.
 *
 * @disclaimer   This code was generated in whole or in part with the assistance
 *               of an AI language model.
 */

#pragma once

#include "CoreMinimal.h"
#include "IDetailPropertyRow.h"

class IPropertyHandle;

namespace SeinSemanticDefault
{
	/**
	 * Reset override for properties whose meaningful default is constructed
	 * from an array element or the selected type inside an FInstancedStruct.
	 *
	 * InstancedStructRoot is supplied for synthetic child handles generated by
	 * FInstancedStructDataDetails, whose custom-builder boundary otherwise
	 * prevents a parent row's propagated reset override from reaching them.
	 */
	FResetToDefaultOverride MakeResetOverride(
		TSharedPtr<IPropertyHandle> InstancedStructRoot = nullptr);

	/** Apply MakeResetOverride to Row and all ordinary descendant rows. */
	void ApplyResetOverride(
		IDetailPropertyRow& Row,
		TSharedPtr<IPropertyHandle> InstancedStructRoot = nullptr);
}
