/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinARTSCoreSettingsDetails.cpp
 */

#include "Details/SeinARTSCoreSettingsDetails.h"

#include "Util/SeinAutoTagGenerator.h"

#include "DetailCategoryBuilder.h"
#include "DetailLayoutBuilder.h"
#include "DetailWidgetRow.h"
#include "PropertyHandle.h"
#include "PropertyCustomizationHelpers.h"
#include "IPropertyUtilities.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/Layout/SBox.h"
#include "Widgets/SNullWidget.h"
#include "Misc/MessageDialog.h"
#include "Settings/PluginSettings.h"

#define LOCTEXT_NAMESPACE "SeinARTSEditor"

namespace
{
	/** Human-readable label for a collision response (used by the reserved-Default row). */
	FText SeinCollisionResponseToText(ESeinCollisionResponse Response)
	{
		switch (Response)
		{
		case ESeinCollisionResponse::Ignore:  return LOCTEXT("RespIgnore",  "Ignore");
		case ESeinCollisionResponse::Overlap: return LOCTEXT("RespOverlap", "Overlap");
		default:                              return LOCTEXT("RespBlock",   "Block");
		}
	}
}

TSharedRef<IDetailCustomization> FSeinARTSCoreSettingsDetails::MakeInstance()
{
	return MakeShared<FSeinARTSCoreSettingsDetails>();
}

void FSeinARTSCoreSettingsDetails::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	IDetailCategoryBuilder& TagCategory = DetailBuilder.EditCategory(
		TEXT("Tag Semantics"),
		FText::GetEmpty(),
		ECategoryPriority::Default);

	// --- Regenerate Auto-Generated Tags (non-destructive) ---
	TagCategory.AddCustomRow(LOCTEXT("RegenAutoRowFilter", "Regenerate Auto-Generated Tags"))
	.NameContent()
	[
		SNew(STextBlock)
		.Text(LOCTEXT("RegenAutoLabel", "Regenerate Auto-Generated Tags"))
		.Font(IDetailLayoutBuilder::GetDetailFont())
		.ToolTipText(LOCTEXT("RegenAutoTip",
			"Walks every SeinARTS Blueprint (Ability / Effect / Entity / Research) and re-derives its tag from the current asset name + settings. "
			"Only touches BPs whose bAutoGeneratedTag is true (designer-edited tags are preserved). "
			"Use this after changing TagPrefix, PrefixCategoryMappings, or AllowTagLayering."))
	]
	.ValueContent()
	[
		SNew(SButton)
		.HAlign(HAlign_Center)
		.OnClicked_Lambda([]() -> FReply
		{
			const int32 NumChanged = SeinAutoTag::RegenerateAllAssetTags(/*bForceOverManual*/ false);
			FMessageDialog::Open(EAppMsgType::Ok, FText::Format(
				LOCTEXT("RegenAutoDone", "Regenerated {0} auto-tagged asset(s).\n\nManually-edited tags (bAutoGeneratedTag = false) were skipped. Use Force Regenerate All to override."),
				FText::AsNumber(NumChanged)));
			return FReply::Handled();
		})
		[
			SNew(STextBlock).Text(LOCTEXT("RegenAutoBtn", "Regenerate Auto-Generated Tags"))
		]
	];

	// --- Force Regenerate All Tags (destructive, confirmation required) ---
	TagCategory.AddCustomRow(LOCTEXT("ForceRegenRowFilter", "Force Regenerate All Tags"))
	.NameContent()
	[
		SNew(STextBlock)
		.Text(LOCTEXT("ForceRegenLabel", "Force Regenerate All Tags"))
		.Font(IDetailLayoutBuilder::GetDetailFont())
		.ToolTipText(LOCTEXT("ForceRegenTip",
			"DESTRUCTIVE: Walks every SeinARTS Blueprint and overwrites its tag with one derived from the asset name — INCLUDING manually-authored tags. "
			"All affected BPs are marked with bAutoGeneratedTag = true after this runs. Use sparingly — designer-authored tag values that don't match the naming convention will be lost."))
	]
	.ValueContent()
	[
		SNew(SButton)
		.HAlign(HAlign_Center)
		.OnClicked_Lambda([]() -> FReply
		{
			const EAppReturnType::Type Result = FMessageDialog::Open(
				EAppMsgType::YesNo,
				LOCTEXT("ForceRegenConfirm",
					"This will overwrite EVERY SeinARTS Blueprint's tag with one derived from its asset name, "
					"including manually-authored tags. Proceed?"));
			if (Result != EAppReturnType::Yes) return FReply::Handled();

			const int32 NumChanged = SeinAutoTag::RegenerateAllAssetTags(/*bForceOverManual*/ true);
			FMessageDialog::Open(EAppMsgType::Ok, FText::Format(
				LOCTEXT("ForceRegenDone", "Force-regenerated {0} asset(s)."),
				FText::AsNumber(NumChanged)));
			return FReply::Handled();
		})
		[
			SNew(STextBlock).Text(LOCTEXT("ForceRegenBtn", "Force Regenerate All Tags"))
		]
	];

	// --- Collision Channels table. The default UE array widget (+ at the header,
	// element delete via a per-row dropdown) doesn't match the desired UX, so the
	// underlying CollisionChannels array is HIDDEN and rendered as a custom table:
	// a greyed read-only "Default" row pinned at the top (reserved — can't be
	// edited or removed), one editable row per ADDITIONAL channel (Name / Default
	// Response / Color) with a trash button on the right, and an Add (+) button at
	// the bottom. The array is driven via its IPropertyHandleArray. ---
	{
		IDetailCategoryBuilder& CollisionCategory = DetailBuilder.EditCategory(
			TEXT("Collision"), FText::GetEmpty(), ECategoryPriority::Default);

		const TSharedRef<IPropertyHandle> ChannelsHandle =
			DetailBuilder.GetProperty(GET_MEMBER_NAME_CHECKED(USeinARTSCoreSettings, CollisionChannels));
		DetailBuilder.HideProperty(ChannelsHandle);  // replaced by the custom table below

		const TSharedPtr<IPropertyUtilities> PropUtils = DetailBuilder.GetPropertyUtilities();
		const TSharedPtr<IPropertyHandleArray> ChannelsArray = ChannelsHandle->AsArray();

		// Column headers (bold), aligned to the row columns below.
		CollisionCategory.AddCustomRow(LOCTEXT("ChannelHeaderFilter", "Collision Channels"))
		.NameContent()
		[
			SNew(STextBlock)
			.Text(LOCTEXT("ChannelHeaderName", "Name"))
			.Font(IDetailLayoutBuilder::GetDetailFontBold())
		]
		.ValueContent()
		.MinDesiredWidth(280.f)
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot().FillWidth(1.f).VAlign(VAlign_Center).Padding(0.f, 0.f, 8.f, 0.f)
			[
				SNew(STextBlock)
				.Text(LOCTEXT("ChannelHeaderResponse", "Default Response"))
				.Font(IDetailLayoutBuilder::GetDetailFontBold())
			]
		];

		// Reserved "Default" row — greyed, read-only, no trash. Always first.
		if (const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>())
		{
			const TArray<FSeinCollisionChannelDefinition> AllChannels = Settings->GetAllCollisionChannels();
			if (AllChannels.Num() > 0)
			{
				const FSeinCollisionChannelDefinition& Reserved = AllChannels[0]; // Default is always first
				CollisionCategory.AddCustomRow(LOCTEXT("ReservedDefaultFilter", "Default Collision Channel"))
				.NameContent()
				[
					SNew(STextBlock)
					.IsEnabled(false)
					.Text(FText::FromName(Reserved.Name))
					.Font(IDetailLayoutBuilder::GetDetailFont())
					.ToolTipText(LOCTEXT("ReservedDefaultTip",
						"Reserved framework collision channel: always present, cannot be edited or removed (like the nav Default layer / vision Normal layer). Add ADDITIONAL channels below."))
				]
				.ValueContent()
				.MinDesiredWidth(280.f)
				[
					SNew(SHorizontalBox)
					.IsEnabled(false)
					+ SHorizontalBox::Slot().FillWidth(1.f).VAlign(VAlign_Center).Padding(0.f, 0.f, 8.f, 0.f)
					[
						SNew(STextBlock)
						.Text(FText::Format(LOCTEXT("ReservedDefaultValue", "{0}  (reserved)"),
							SeinCollisionResponseToText(Reserved.DefaultResponse)))
						.Font(IDetailLayoutBuilder::GetDetailFont())
					]
				];
			}
		}

		// One editable row per additional channel: Name | Default Response | Color | [trash].
		uint32 NumChannels = 0;
		if (ChannelsArray.IsValid())
		{
			ChannelsArray->GetNumElements(NumChannels);
		}
		for (uint32 ChannelIdx = 0; ChannelIdx < NumChannels; ++ChannelIdx)
		{
			const TSharedRef<IPropertyHandle> Element = ChannelsArray->GetElement(static_cast<int32>(ChannelIdx));
			const TSharedPtr<IPropertyHandle> NameHandle  = Element->GetChildHandle(TEXT("Name"));
			const TSharedPtr<IPropertyHandle> RespHandle  = Element->GetChildHandle(TEXT("DefaultResponse"));

			const TSharedRef<SWidget> NameWidget  = NameHandle.IsValid()  ? NameHandle->CreatePropertyValueWidget(false)  : SNullWidget::NullWidget;
			const TSharedRef<SWidget> RespWidget  = RespHandle.IsValid()  ? RespHandle->CreatePropertyValueWidget(false)  : SNullWidget::NullWidget;

			CollisionCategory.AddCustomRow(FText::FromString(TEXT("Collision Channel")))
			.NameContent()
			[
				NameWidget
			]
			.ValueContent()
			.MinDesiredWidth(280.f)
			[
				SNew(SHorizontalBox)
				+ SHorizontalBox::Slot().FillWidth(1.f).VAlign(VAlign_Center).Padding(0.f, 0.f, 8.f, 0.f)
				[
					RespWidget
				]
				+ SHorizontalBox::Slot().AutoWidth().VAlign(VAlign_Center)
				[
					PropertyCustomizationHelpers::MakeDeleteButton(
						FSimpleDelegate::CreateLambda([ChannelsArray, ChannelIdx, PropUtils]()
						{
							if (ChannelsArray.IsValid())
							{
								ChannelsArray->DeleteItem(static_cast<int32>(ChannelIdx));
							}
							if (PropUtils.IsValid())
							{
								PropUtils->ForceRefresh();
							}
						}),
						LOCTEXT("DeleteChannelTip", "Remove this collision channel"))
				]
			];
		}

		// Add (+) button at the bottom.
		CollisionCategory.AddCustomRow(LOCTEXT("AddChannelFilter", "Add Collision Channel"))
		.WholeRowContent()
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot().AutoWidth().VAlign(VAlign_Center)
			[
				PropertyCustomizationHelpers::MakeAddButton(
					FSimpleDelegate::CreateLambda([ChannelsArray, PropUtils]()
					{
						if (ChannelsArray.IsValid())
						{
							ChannelsArray->AddItem();
						}
						if (PropUtils.IsValid())
						{
							PropUtils->ForceRefresh();
						}
					}),
					LOCTEXT("AddChannelLabel", "Add a collision channel"))
			]
			+ SHorizontalBox::Slot().AutoWidth().VAlign(VAlign_Center).Padding(6.f, 0.f, 0.f, 0.f)
			[
				SNew(STextBlock)
				.Text(LOCTEXT("AddChannelText", "Add Collision Channel"))
				.Font(IDetailLayoutBuilder::GetDetailFont())
			]
		];
	}
}

#undef LOCTEXT_NAMESPACE
