/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinEffect.cpp
 *
 * USeinEffect's runtime is BlueprintImplementable hooks — most logic lives
 * in BP graphs. This .cpp exists to host editor-only overrides (currently
 * just PostEditChangeProperty for auto-tag provenance tracking).
 */

#include "Effects/SeinEffect.h"

#if WITH_EDITOR
void USeinEffect::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);
	const FName ChangedName = PropertyChangedEvent.Property
		? PropertyChangedEvent.Property->GetFName()
		: NAME_None;
	if (ChangedName == GET_MEMBER_NAME_CHECKED(USeinEffect, EffectTag))
	{
		// Designer edited the tag manually — surrender provenance ownership.
		// See USeinAbility::PostEditChangeProperty for full lifecycle.
		bAutoGeneratedTag = false;
	}
}
#endif
