/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file:    SeinIdentityComponent.h
 * @brief:   UI/identity metadata for an entity — display name, description,
 *           icon, portrait, identity tag. Decomposed out of
 *           `USeinArchetypeDefinition` as part of the Phase-1 entity-component
 *           refactor (single `USeinEntityBridgeComponent` with an array of authored
 *           data structs).
 *
 *           Optional component — entities without UI presence (abstract sim
 *           entities, scenario owners) don't need it. The `bIsAbstract` flag
 *           that previously lived on the archetype is NOT in this struct; it
 *           moves to the top-level `USeinEntityBridgeComponent` UPROPERTY because
 *           "has a render actor" is a framework-level entity classification,
 *           not authoring metadata.
 */

#pragma once

#include "CoreMinimal.h"
#include "Components/SeinPayload.h"
#include "GameplayTagContainer.h"
#include "SeinIdentityPayload.generated.h"

class UTexture2D;

USTRUCT(BlueprintType, meta = (SeinDeterministic))
struct SEINARTSCOREENTITY_API FSeinIdentityPayload : public FSeinPayload
{
	GENERATED_BODY()

	/** Display name for this entity type (shown in UI, production queues, etc.) */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS")
	FText DisplayName;

	/** Long-form description for tooltips, info panels, codex entries. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS",
		meta = (MultiLine = true))
	FText Description;

	/** Icon texture for UI (production buttons, selection panel). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS")
	TObjectPtr<UTexture2D> Icon;

	/** Portrait texture for UI (info panel, veterancy display). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS")
	TObjectPtr<UTexture2D> Portrait;

	/** Optional per-type minimap blip sprite. When set, the minimap draws this for the
	 *  entity (typically tinted by team relation) instead of the default dot — e.g. a tank
	 *  silhouette vs an infantry dot. Null → default dot. Render-side metadata only (not
	 *  hashed, like Icon / Portrait). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS")
	TObjectPtr<UTexture2D> MinimapIcon;

	/** Gameplay tag uniquely identifying this entity's type
	 *  (e.g., `Unit.Infantry`, `Building.Barracks`). Drives Class-scope
	 *  modifier matching, tag-based selection, and entity-type queries. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "SeinARTS")
	FGameplayTag IdentityTag;

	/** Provenance flag for the auto-tag-generation system. See
	 *  USeinAbility::bAutoGeneratedTag for full semantics. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "SeinARTS",
		AdvancedDisplay)
	bool bAutoGeneratedTag = false;
};

FORCEINLINE uint32 GetTypeHash(const FSeinIdentityPayload& Component)
{
	// Identity is UI-only sim metadata — hash by the only field that affects
	// sim equality (IdentityTag). Textures / FText fields are render-side
	// only; hashing them adds no sim-determinism value and FText doesn't
	// have a stable cross-locale hash to begin with.
	return GetTypeHash(Component.IdentityTag);
}
