/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file:    SeinAutoTagGenerator.h
 * @brief:   Editor-only utility for the auto-tag-generation pipeline.
 *           Consumed by the SeinARTS factories at creation time, the
 *           asset-rename hook in SeinARTSEditorModule, and the
 *           Regenerate-* buttons on the settings details panel.
 *
 *           Name matching is deterministic over (FName AssetName, settings).
 *           Derivation persists a missing tag into the dedicated generated
 *           Gameplay Tags source so it can return a valid FGameplayTag.
 *           Lives in the editor module - not needed at runtime.
 *
 *           Tag shape:
 *             <TagPrefix>.<Category>.<NameSegments>
 *
 *           Examples (default settings, TagPrefix="SeinARTS"):
 *             SA_Move                     → SeinARTS.Ability.Move
 *             SE_Movement_SprintBoost     → SeinARTS.Effect.Movement.SprintBoost
 *             SU_Infantry_Officer         → SeinARTS.Unit.Infantry.Officer
 *             SBP_Projectile_Smoke        → SeinARTS.Entity.Projectile.Smoke
 *
 *           Hierarchical layering (the second through Nth underscore segments
 *           becoming tag hierarchy levels) is gated on the
 *           `bAllowTagLayering` setting. When off, the rest of the name is
 *           flattened ("SeinARTS.Effect.Movement_SprintBoost" preserved verbatim
 *           after the prefix split).
 */

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"

class UBlueprint;
class USeinARTSCoreSettings;
struct FSeinTagPrefixMapping;

enum class ESeinAutoTagRegenerationOutcome : uint8
{
	Updated,
	AlreadyCurrent,
	SkippedDesignerOwned,
	InvalidBlueprint,
	AutoTagDisabled,
	UnsupportedAsset,
	TagDerivationFailed,
	Collision,
};

/** Detailed outcome for one editor auto-tag regeneration attempt. */
struct SEINARTSEDITOR_API FSeinAutoTagRegenerationResult
{
	ESeinAutoTagRegenerationOutcome Outcome =
		ESeinAutoTagRegenerationOutcome::InvalidBlueprint;
	FGameplayTag DerivedTag;
	FString CollidingAssetPath;

	bool WasUpdated() const
	{
		return Outcome == ESeinAutoTagRegenerationOutcome::Updated;
	}

	bool IsFailure() const;
	FText ToUserMessage(const UBlueprint* OwningBP) const;
};

namespace SeinAutoTag
{
	/** Derive a gameplay tag from an asset name + the active plugin settings.
	 *  Returns an invalid `FGameplayTag()` if:
	 *    - Settings is null
	 *    - bEnableAutoTagGeneration is false
	 *    - AssetName has no prefix segment (no underscore)
	 *    - AssetName's prefix doesn't match any entry in PrefixCategoryMappings
	 *    - The post-prefix name segment is empty (e.g. "SA_" alone)
	 *
	 *  If the derived tag is missing, this function persists it to
	 *  `SeinAutoGeneratedTags.ini` and refreshes the Gameplay Tags tree before
	 *  returning. During an explicitly suspended editor refresh, the first
	 *  call may return invalid until the owner resumes the tree; bulk
	 *  regeneration handles that deferred lookup internally. */
	SEINARTSEDITOR_API FGameplayTag DeriveTagFromAssetName(
		const FName& AssetName,
		const USeinARTSCoreSettings* Settings);

	/** Walk Settings.PrefixCategoryMappings, return the first entry whose
	 *  AssetPrefix matches the leading underscore-delimited segment of
	 *  AssetName. Returns nullptr if no match. */
	SEINARTSEDITOR_API const FSeinTagPrefixMapping* FindMatchingPrefixMapping(
		const FName& AssetName,
		const USeinARTSCoreSettings* Settings);

	/** Register a tag with the gameplay tags manager if it's not already
	 *  present. Idempotent. Safe to call repeatedly. */
	SEINARTSEDITOR_API void RegisterTagIfNeeded(const FGameplayTag& Tag);

	/** Walk the asset registry for any SeinARTS-known asset class (ability,
	 *  effect, entity blueprint) whose stored tag equals `Tag`. Returns the
	 *  first colliding asset's package path, or empty if no collision.
	 *  `IgnorePackagePath` lets the caller exclude its own asset from the
	 *  scan (we don't want a BP to collide with itself on rename). */
	SEINARTSEDITOR_API FString FindCollidingAssetPath(
		const FGameplayTag& Tag,
		const FString& IgnorePackagePath = FString());

	/** Regenerate the tag on a single asset CDO. If `bForceOverManual` is
	 *  false, skips when the CDO's `bAutoGeneratedTag` is false (designer
	 *  owns it). If true, overrides regardless + sets `bAutoGeneratedTag` =
	 *  true. Returns a specific outcome and collision path suitable for
	 *  actionable editor feedback. */
	SEINARTSEDITOR_API FSeinAutoTagRegenerationResult
		RegenerateAssetTagDetailed(
			UBlueprint* OwningBP,
			bool bForceOverManual);

#if WITH_DEV_AUTOMATION_TESTS
	/** Automation-only scoped collision seam. Production regeneration always
	 *  enforces project-wide tag uniqueness. */
	SEINARTSEDITOR_API FSeinAutoTagRegenerationResult
		RegenerateAssetTagDetailedForAutomation(
			UBlueprint* OwningBP,
			bool bForceOverManual,
			const FString& CollisionSearchPackageRoot);
#endif

	/** Compatibility wrapper over `RegenerateAssetTagDetailed`. Returns true
	 *  only when the asset was actually changed. */
	SEINARTSEDITOR_API bool RegenerateAssetTag(
		UBlueprint* OwningBP,
		bool bForceOverManual);

	/** Walk the asset registry for every SeinARTS taggable BP and call
	 *  RegenerateAssetTag. Returns the count of assets updated.
	 *  `bForceOverManual` mirrors the "Force Regenerate All" vs
	 *  "Regenerate Auto" buttons on the settings panel. */
	SEINARTSEDITOR_API int32 RegenerateAllAssetTags(bool bForceOverManual);
}
