/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file         SeinTagAudit.cpp
 * @author       RJ Macklem
 * @created      7 Sep 2026
 * @latest       7 Sep 2026
 * @brief        Retains referenced, redirected, shared-source and uncertain generated tags.
 * @disclaimer   Generated with assistance from an AI language model.
 */
#include "Util/SeinTagAudit.h"
#include "Util/SeinTagSourcePersistence.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Core/SeinAssetTagKeys.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/Blueprint.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsSettings.h"
#include "GameplayTagsEditorModule.h"
#include "Editor.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/ConfigCacheIni.h"
#include "Misc/Paths.h"
#include "UObject/UObjectIterator.h"
#include "UObject/Package.h"
#include "Framework/Application/SlateApplication.h"
#include "Widgets/SWindow.h"
#include "Widgets/Layout/SScrollBox.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/Input/SButton.h"
#include "Misc/MessageDialog.h"

namespace
{
	const FName GeneratedSource(TEXT("SeinAutoGeneratedTags.ini"));
	TArray<const FGameplayTagSource*> TagSources()
	{
		TArray<const FGameplayTagSource*> Result;
		UGameplayTagsManager::Get().FindTagSourcesWithType(EGameplayTagSourceType::TagList, Result);
		return Result;
	}
}

bool SeinTagAudit::IsRedirectEndpoint(FName Tag)
{
	auto Contains = [Tag](const UGameplayTagsList* List)
	{
		if (List) for (const FGameplayTagRedirect& Redirect : List->GameplayTagRedirects)
			if (Redirect.OldTagName == Tag || Redirect.NewTagName == Tag) return true;
		return false;
	};
	if (Contains(GetDefault<UGameplayTagsSettings>())) return true;
	for (const auto* Source : TagSources()) if (Contains(Source->SourceTagList)) return true;
	return false;
}

FString SeinTagAudit::MutationBlocker()
{
	if (GEditor && GEditor->PlayWorld) return TEXT("Stop Play in Editor first.");
	auto& Registry = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry").Get();
	if (Registry.IsLoadingAssets()) return TEXT("Wait for asset discovery to complete.");
	for (TObjectIterator<UPackage> It; It; ++It)
	{
		if (!IsValid(*It)) continue;
		const FString Name = It->GetName();
		if (It->IsDirty() && !It->HasAnyPackageFlags(PKG_CompiledIn) && !It->HasAnyFlags(RF_Transient)
			&& !Name.StartsWith(TEXT("/Temp/")) && !Name.StartsWith(TEXT("/Memory/"))
			&& *It != GetTransientPackage())
			return FString::Printf(TEXT("Save content first: %s has unsaved changes."), *Name);
	}
	return FString();
}

static TArray<FSeinTagAuditRow> InspectSource(FName SourceName)
{
	using namespace SeinTagAudit;
	TArray<FSeinTagAuditRow> Rows;
	auto& Manager = UGameplayTagsManager::Get();
	const auto* Source = Manager.FindTagSource(SourceName);
	if (!Source || !Source->SourceTagList) return Rows;
	const FString Blocker = MutationBlocker();
	const bool bSourceCurrent = SeinTagSourcePersistence::MatchesDisk(Source->SourceTagList->ConfigFileName, Source->SourceTagList);
	const bool bWritable = !IFileManager::Get().IsReadOnly(*Source->SourceTagList->ConfigFileName);
	TArray<TSharedPtr<FGameplayTagNode>> Unused;
	IGameplayTagsEditorModule::Get().GetUnusedGameplayTags(Unused);
	TSet<FName> UnusedNames;
	for (const auto& Node : Unused) if (Node.IsValid()) UnusedNames.Add(Node->GetCompleteTagName());
	auto& Registry = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry").Get();
	FARFilter Filter;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	Filter.bRecursiveClasses = true;
	TArray<FAssetData> Assets;
	Registry.GetAssets(Filter, Assets);
	// Native code/string-based requests are not searchable-name dependencies. Conservative text
	// matching intentionally retains comments and ancestor references rather than guessing intent.
	TArray<TPair<FString, FString>> TextSources;
	bool bReadFailed = false;
	for (const FString Root : {(FPaths::ProjectDir() / TEXT("Source")), FPaths::ProjectConfigDir(), FPaths::ProjectPluginsDir()})
	{
		TArray<FString> Files;
		IFileManager::Get().FindFilesRecursive(Files, *Root, TEXT("*"), true, false);
		for (const FString& File : Files)
		{
			const FString Extension = FPaths::GetExtension(File);
			if (File.Contains(TEXT("/Intermediate/")) || File.Contains(TEXT("/Binaries/"))
				|| FPaths::GetCleanFilename(File) == SourceName.ToString()) continue;
			if (Extension != TEXT("cpp") && Extension != TEXT("h") && Extension != TEXT("ini")) continue;
			FString Text;
			if (!FFileHelper::LoadFileToString(Text, *File)) { bReadFailed = true; continue; }
			TextSources.Emplace(File, MoveTemp(Text));
		}
	}
	for (const auto& Entry : Source->SourceTagList->GameplayTagList)
	{
		FSeinTagAuditRow Row;
		Row.Tag = Entry.Tag;
		const FGameplayTag Tag = Manager.RequestGameplayTag(Entry.Tag, false);
		for (const FAssetData& Asset : Assets)
		{
			FGameplayTag Identity;
			bool bGenerated = false;
			if (const auto* BP = Cast<UBlueprint>(Asset.FastGetAsset(false)))
			{
				if (SeinAutoTag::ReadAssetIdentity(BP, Identity, bGenerated) && Identity == Tag)
					Row.Owners.Add(Asset.PackageName.ToString());
			}
			else for (const FName Key : {SeinAssetTagKeys::AbilityTag(), SeinAssetTagKeys::EffectTag(), SeinAssetTagKeys::IdentityTag()})
			{
				FString Value;
				if (Asset.GetTagValue(Key, Value) && FName(*Value) == Entry.Tag)
					Row.Owners.AddUnique(Asset.PackageName.ToString());
			}
		}
		FString Comment;
		TArray<FName> Sources;
		bool bExplicit = false, bRestricted = false, bAllowChildren = false;
		Manager.GetTagEditorData(Entry.Tag, Comment, Sources, bExplicit, bRestricted, bAllowChildren);
		if (!Blocker.IsEmpty()) Row.Reason = Blocker;
		else if (!bSourceCurrent) Row.Reason = TEXT("Tag source differs from disk; refresh its dictionary before cleanup.");
		else if (!bWritable) Row.Reason = TEXT("Generated tag source is read-only.");
		else if (bReadFailed) Row.Reason = TEXT("A source/config file could not be inspected.");
		else if (!Row.Owners.IsEmpty()) Row.Reason = Row.Owners.Num() > 1 ? TEXT("Duplicate identity owners; resolve explicitly.") : TEXT("Owned by an asset.");
		else if (!Entry.DevComment.StartsWith(TEXT("Auto-generated by SeinARTS"))) Row.Reason = TEXT("No generated provenance; retained as authored data.");
		else if (Sources.Num() != 1 || Sources[0] != SourceName || bRestricted) Row.Reason = TEXT("Shared/native/restricted source; retained.");
		else if (IsRedirectEndpoint(Entry.Tag)) Row.Reason = TEXT("Compatibility redirect endpoint; retained.");
		else if (!Manager.RequestGameplayTagChildren(Tag).IsEmpty()) Row.Reason = TEXT("Has descendant tags; hierarchy retained.");
		else if (!UnusedNames.Contains(Entry.Tag)) Row.Reason = TEXT("Referenced by saved assets or configuration.");
		else
		{
			TArray<FString> RemovedNames{Entry.Tag.ToString()};
			// Only implicit ancestors whose sole child is this chain disappear with the leaf.
			FString Parent = Entry.Tag.ToString();
			int32 Dot = INDEX_NONE;
			while (Parent.FindLastChar(TEXT('.'), Dot))
			{
				Parent.LeftInline(Dot);
				const auto ParentNode = Manager.FindTagNode(FName(*Parent));
				if (!ParentNode.IsValid() || ParentNode->IsExplicitTag() || ParentNode->GetChildTagNodes().Num() != 1) break;
				RemovedNames.Add(Parent);
				if (IsRedirectEndpoint(FName(*Parent))) Row.Reason = TEXT("Removing this leaf would remove a redirected implicit parent.");
			}
			for (const auto& Text : TextSources)
				if (RemovedNames.ContainsByPredicate([&Text](const FString& Name) { return Text.Value.Contains(Name); }))
				{
					Row.Reason = TEXT("Source/config reference: ") + Text.Key;
					break;
				}
			if (Row.Reason.IsEmpty()) { Row.bCanDelete = true; Row.Reason = TEXT("Unused generated leaf; eligible for cleanup."); }
		}
		Row.Owners.Sort();
		Rows.Add(MoveTemp(Row));
	}
	Rows.Sort([](const auto& A, const auto& B) { return A.Tag.ToString() < B.Tag.ToString(); });
	return Rows;
}

TArray<FSeinTagAuditRow> SeinTagAudit::Inspect()
{
	return InspectSource(GeneratedSource);
}

#if WITH_DEV_AUTOMATION_TESTS
TArray<FSeinTagAuditRow> SeinTagAudit::InspectForAutomation(FName SourceName)
{
	return InspectSource(SourceName);
}
#endif

FString SeinTagAudit::Format(const TArray<FSeinTagAuditRow>& Rows)
{
	FString Text = TEXT("Generated tag audit\n\n");
	for (const auto& Row : Rows)
	{
		Text += Row.Tag.ToString() + TEXT(" — ") + Row.Reason + TEXT("\n");
		for (const auto& Owner : Row.Owners) Text += TEXT("  ") + Owner + TEXT("\n");
	}
	return Text;
}

static FString CleanupSource(FName SourceName, const TArray<FName>& Candidates)
{
	using namespace SeinTagAudit;
	FString Receipt;
	bool bRemoved = false;
	for (FName Candidate : Candidates)
	{
		// Refresh the whole evidence set per deletion; callers cannot reuse a stale approval/report.
		const auto Rows = InspectSource(SourceName);
		const auto* Row = Rows.FindByPredicate([Candidate](const auto& R) { return R.Tag == Candidate; });
		if (!Row || !Row->bCanDelete)
		{
			Receipt += Candidate.ToString() + TEXT(": retained — ") + (Row ? Row->Reason : TEXT("not a generated entry")) + TEXT("\n");
			continue;
		}
		const auto* Source = UGameplayTagsManager::Get().FindTagSource(SourceName);
		if (!Source || !Source->SourceTagList) continue;
		UGameplayTagsList* SourceList = Source->SourceTagList;
		const FString Path = SourceList->ConfigFileName;
		FString Before, After;
		const FString Section = SourceList->GetClass()->GetPathName();
		auto ExpectedDefinitions = SourceList->GameplayTagList;
		ExpectedDefinitions.RemoveAll([Candidate](const auto& Entry) { return Entry.Tag == Candidate; });
		const auto ExpectedRedirects = SourceList->GameplayTagRedirects;
		if (!FFileHelper::LoadFileToString(Before, *Path) || !SeinTagSourcePersistence::MatchesDisk(Path, SourceList))
		{
			Receipt += Candidate.ToString() + TEXT(": source could not be read; retained\n");
			continue;
		}
		bool bDeleted = IGameplayTagsEditorModule::Get().DeleteTagFromINI(UGameplayTagsManager::Get().FindTagNode(Candidate));
		bDeleted = bDeleted && SeinTagSourcePersistence::MatchesDisk(Path, Section, ExpectedDefinitions, ExpectedRedirects);
		if (!bDeleted)
		{
			const bool bRestored = FFileHelper::SaveStringToFile(Before, *Path)
				&& FFileHelper::LoadFileToString(After, *Path) && After == Before;
			GConfig->LoadFile(Path);
			SourceList->ReloadConfig(nullptr, *Path);
			UGameplayTagsManager::Get().EditorRefreshGameplayTagTree();
			if (!bRestored)
			{
				Receipt += Candidate.ToString() + TEXT(": source restoration failed; restore the INI from source control before continuing.\n");
				break;
			}
		}
		bRemoved |= bDeleted;
		Receipt += Candidate.ToString() + (bDeleted ? TEXT(": removed\n") : TEXT(": deletion refused\n"));
	}
	if (bRemoved && GEditor) GEditor->ResetTransaction(FText::FromString(TEXT("Generated tag cleanup")));
	return Receipt.IsEmpty() ? TEXT("No eligible generated tags to remove.") : Receipt;
}

FString SeinTagAudit::Cleanup(const TArray<FName>& Candidates)
{
	return CleanupSource(GeneratedSource, Candidates);
}

#if WITH_DEV_AUTOMATION_TESTS
FString SeinTagAudit::CleanupForAutomation(FName SourceName, const TArray<FName>& Candidates)
{
	if (!SourceName.ToString().StartsWith(TEXT("SeinTagTest_"))) return TEXT("Requires an isolated automation source.");
	return CleanupSource(SourceName, Candidates);
}
#endif

void SeinTagAudit::ShowWindow()
{
	const auto Report = SNew(STextBlock).Text(FText::FromString(Format(Inspect())));
	const auto Window = SNew(SWindow).Title(FText::FromString(TEXT("Generated Tags")))
		.ClientSize(FVector2D(1000, 650))
		[
			SNew(SVerticalBox)
			+ SVerticalBox::Slot().FillHeight(1).Padding(12)
			[SNew(SScrollBox) + SScrollBox::Slot()[Report]]
			+ SVerticalBox::Slot().AutoHeight().Padding(12)
			[SNew(SHorizontalBox)
				+ SHorizontalBox::Slot().AutoWidth()
				[SNew(SButton).Text(FText::FromString(TEXT("Refresh")))
					.OnClicked_Lambda([Report]() { Report->SetText(FText::FromString(Format(Inspect()))); return FReply::Handled(); })]
				+ SHorizontalBox::Slot().AutoWidth().Padding(12, 0)
				[SNew(SButton).Text(FText::FromString(TEXT("Clean Up Unused Generated Tags")))
					.OnClicked_Lambda([Report]()
					{
						TArray<FName> Candidates;
						FString Preview = TEXT("Remove these unused generated tags from the dictionary? This clears editor undo history so an undo cannot restore a reference to a removed tag.\n\n");
						for (const auto& Row : Inspect()) if (Row.bCanDelete) { Candidates.Add(Row.Tag); Preview += Row.Tag.ToString() + TEXT("\n"); }
						if (Candidates.IsEmpty()) FMessageDialog::Open(EAppMsgType::Ok, FText::FromString(TEXT("No eligible tags. Save content and refresh to see why entries are retained.")));
						else if (FMessageDialog::Open(EAppMsgType::YesNo, FText::FromString(Preview)) == EAppReturnType::Yes)
							FMessageDialog::Open(EAppMsgType::Ok, FText::FromString(Cleanup(Candidates)));
						Report->SetText(FText::FromString(Format(Inspect())));
						return FReply::Handled();
					})]
			]
		];
	FSlateApplication::Get().AddWindow(Window);
}
