/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinAutoTagGenerator.cpp
 */

#include "Util/SeinAutoTagGenerator.h"

#include "Settings/PluginSettings.h"
#include "Data/SeinTagPrefixMapping.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Components/SeinIdentityPayload.h"
#include "Actor/SeinActor.h"
#include "Actor/SeinEntityBridgeComponent.h"
#include "Core/SeinAssetTagKeys.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsEditorModule.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "UObject/Package.h"
#include "Misc/Guid.h"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAutoTagGen, Log, All);

#define LOCTEXT_NAMESPACE "SeinAutoTagGenerator"

/** Dedicated INI source the auto-tag system writes generated tags into.
 *  Lives at `<Project>/Config/Tags/SeinAutoGeneratedTags.ini`. Designers
 *  can open Project Settings → Project → Gameplay Tags and see this as a
 *  separate source alongside their hand-curated `DefaultGameplayTags.ini`.
 *  Hand-edits to this file survive — the framework only ever appends. */
static const FString GSeinAutoTagSourceName = TEXT("SeinAutoGeneratedTags.ini");

namespace SeinAutoTagLocal
{
	/** Split an asset name on `_`. First segment is the prefix; rest is the
	 *  name body. Returns false if there's no `_` in the name. */
	static bool SplitOnUnderscore(const FString& AssetName, FString& OutPrefix, TArray<FString>& OutNameSegments)
	{
		TArray<FString> AllSegments;
		AssetName.ParseIntoArray(AllSegments, TEXT("_"), /*InCullEmpty*/ false);
		if (AllSegments.Num() < 2) return false;
		OutPrefix = AllSegments[0];
		OutNameSegments.Reset(AllSegments.Num() - 1);
		for (int32 i = 1; i < AllSegments.Num(); ++i)
		{
			// Skip blank inner segments (e.g. "SA__Move" — defensive).
			if (!AllSegments[i].IsEmpty())
			{
				OutNameSegments.Add(AllSegments[i]);
			}
		}
		return OutNameSegments.Num() > 0;
	}

	/** Strip the trailing "_C" that Blueprint-generated classes carry. */
	static FString StripBlueprintClassSuffix(const FString& Name)
	{
		if (Name.EndsWith(TEXT("_C")))
		{
			return Name.LeftChop(2);
		}
		return Name;
	}

	/** Read the live (in-memory) CDO of a loaded Sein BP and test whether its
	 *  identity tag equals `Tag`. Mirrors the per-class shape of the old
	 *  always-load scan (and, for actors, checks every FSeinIdentityPayload
	 *  entry). Used for assets already in memory — so their possibly-unsaved
	 *  value is authoritative — and as the fallback for assets whose registry
	 *  tag isn't populated yet. */
	static bool CDOHasMatchingTag(const UBlueprint* BP, const FGameplayTag& Tag)
	{
		if (!BP || !BP->GeneratedClass) return false;
		const UObject* CDO = BP->GeneratedClass->GetDefaultObject();
		if (!CDO) return false;

		if (const USeinAbility* Ability = Cast<USeinAbility>(CDO))
		{
			return Ability->AbilityTag == Tag;
		}
		if (const USeinEffect* Effect = Cast<USeinEffect>(CDO))
		{
			return Effect->EffectTag == Tag;
		}
		if (const ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
		{
			TArray<USeinEntityBridgeComponent*> Bridges;
			SeinActor->GetComponents<USeinEntityBridgeComponent>(Bridges);
			for (const USeinEntityBridgeComponent* Bridge : Bridges)
			{
				if (!Bridge) continue;
				for (const FInstancedStruct& Entry : Bridge->ComponentData)
				{
					if (!Entry.IsValid()) continue;
					if (Entry.GetScriptStruct() != FSeinIdentityPayload::StaticStruct()) continue;
					if (Entry.Get<FSeinIdentityPayload>().IdentityTag == Tag) return true;
				}
			}
		}
		return false;
	}

	static FString FindCollidingAssetPathInternal(
		const FGameplayTag& Tag,
		const FString& IgnorePackagePath,
		const FString& SearchPackageRoot);

	static FSeinAutoTagRegenerationResult
		RegenerateAssetTagDetailedInternal(
			UBlueprint* OwningBP,
			bool bForceOverManual,
			const FString& CollisionSearchPackageRoot);
}

bool FSeinAutoTagRegenerationResult::IsFailure() const
{
	return Outcome != ESeinAutoTagRegenerationOutcome::Updated
		&& Outcome != ESeinAutoTagRegenerationOutcome::AlreadyCurrent
		&& Outcome !=
			ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned;
}

FText FSeinAutoTagRegenerationResult::ToUserMessage(
	const UBlueprint* OwningBP) const
{
	const FText AssetName = FText::FromString(
		OwningBP ? OwningBP->GetName() : TEXT("<unknown>"));
	const FText TagName = FText::FromString(
		DerivedTag.IsValid()
			? DerivedTag.ToString()
			: TEXT("<unresolved>"));

	switch (Outcome)
	{
	case ESeinAutoTagRegenerationOutcome::Updated:
		return FText::Format(
			LOCTEXT("Updated", "Updated {0} to auto tag {1}."),
			AssetName,
			TagName);
	case ESeinAutoTagRegenerationOutcome::AlreadyCurrent:
		return FText::Format(
			LOCTEXT("AlreadyCurrent", "{0} already uses auto tag {1}."),
			AssetName,
			TagName);
	case ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned:
		return FText::Format(
			LOCTEXT("DesignerOwned",
				"{0} has a designer-owned tag. Use Reset to Auto to return ownership to the auto-tag system."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::InvalidBlueprint:
		return LOCTEXT("InvalidBlueprint",
			"The selected Blueprint has no generated class or class defaults to update.");
	case ESeinAutoTagRegenerationOutcome::AutoTagDisabled:
		return LOCTEXT("AutoTagDisabled",
			"Auto tag generation is disabled in SeinARTS project settings.");
	case ESeinAutoTagRegenerationOutcome::UnsupportedAsset:
		return FText::Format(
			LOCTEXT("UnsupportedAsset",
				"{0} has no supported SeinARTS ability, effect, or identity tag to update."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::TagDerivationFailed:
		return FText::Format(
			LOCTEXT("DerivationFailed",
				"No auto tag could be derived for {0}. Check its asset-name prefix and the Prefix Category Mappings in SeinARTS project settings."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::Collision:
		return FText::Format(
			LOCTEXT("Collision",
				"Cannot assign auto tag {0} to {1}; it is already used by {2}. Rename one asset, then use Reset to Auto."),
			TagName,
			AssetName,
			FText::FromString(CollidingAssetPath));
	default:
		return LOCTEXT("Unknown", "Auto tag regeneration failed.");
	}
}

const FSeinTagPrefixMapping* SeinAutoTag::FindMatchingPrefixMapping(
	const FName& AssetName,
	const USeinARTSCoreSettings* Settings)
{
	if (!Settings) return nullptr;
	const FString NameStr = SeinAutoTagLocal::StripBlueprintClassSuffix(AssetName.ToString());

	FString Prefix;
	TArray<FString> Body;
	if (!SeinAutoTagLocal::SplitOnUnderscore(NameStr, Prefix, Body)) return nullptr;

	for (const FSeinTagPrefixMapping& Mapping : Settings->PrefixCategoryMappings)
	{
		if (Mapping.AssetPrefix == Prefix && !Mapping.TagCategory.IsEmpty())
		{
			return &Mapping;
		}
	}
	return nullptr;
}

FGameplayTag SeinAutoTag::DeriveTagFromAssetName(
	const FName& AssetName,
	const USeinARTSCoreSettings* Settings)
{
	if (!Settings) return FGameplayTag();
	if (!Settings->bEnableAutoTagGeneration) return FGameplayTag();

	const FString NameStr = SeinAutoTagLocal::StripBlueprintClassSuffix(AssetName.ToString());

	FString Prefix;
	TArray<FString> Body;
	if (!SeinAutoTagLocal::SplitOnUnderscore(NameStr, Prefix, Body))
	{
		return FGameplayTag();
	}

	const FSeinTagPrefixMapping* Mapping = FindMatchingPrefixMapping(AssetName, Settings);
	if (!Mapping) return FGameplayTag();

	// Build the tag string segment-by-segment:
	//   <TagPrefix>.<Category>.<Body[0]>.<Body[1]>...
	// or with bAllowTagLayering=false:
	//   <TagPrefix>.<Category>.<Body joined by underscore>
	FString TagString;
	if (!Settings->TagPrefix.IsEmpty())
	{
		TagString = Settings->TagPrefix + TEXT(".");
	}
	TagString += Mapping->TagCategory;
	TagString += TEXT(".");

	if (Settings->bAllowTagLayering)
	{
		TagString += FString::Join(Body, TEXT("."));
	}
	else
	{
		TagString += FString::Join(Body, TEXT("_"));
	}

	// Register-and-lookup. The previous implementation used
	// `RequestGameplayTag(name, /*ErrorIfNotFound*/false)` which is pure
	// lookup — returns invalid for tags not yet in the manager's tree.
	// That silently broke the whole pipeline: tags weren't pre-registered
	// (we have no native UE_DEFINE_GAMEPLAY_TAG_COMMENT for auto-generated
	// SU_/SR_/SBP_ names), so Derive always returned invalid, factories
	// skipped stamping, and Force Regenerate found 0 assets.
	//
	// The FGameplayTag(FName) constructor is protected (friend-restricted
	// to UGameplayTagsManager), so we can't construct directly. The only
	// post-init path that produces a valid FGameplayTag is to write the
	// tag to an INI source via IGameplayTagsEditorModule, then look it up
	// — at which point it's in the tree and the lookup succeeds.
	//
	// AddNewGameplayTagToINI is idempotent (a duplicate add is a no-op),
	// so calling Derive repeatedly for the same name is cheap. It does
	// trigger an EditorRefreshGameplayTagTree per call, which is the
	// expensive part — RegenerateAllAssetTags batches refreshes via
	// Suspend/Resume to amortize that cost across the whole sweep.
	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	const FName TagName(*TagString);
	if (TagName.IsNone()) return FGameplayTag();

	// Fast path: already registered.
	FGameplayTag Existing = Manager.RequestGameplayTag(TagName, /*ErrorIfNotFound*/ false);
	if (Existing.IsValid()) return Existing;

	// Register via the editor module's INI path. Falls back to invalid
	// gracefully if the module isn't loaded (e.g. cooked-game contexts —
	// not a concern in practice since this file is editor-only, but
	// defensive against module load-order edge cases).
	if (IGameplayTagsEditorModule::IsAvailable())
	{
		IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(
			TagString,
			TEXT("Auto-generated by SeinARTS from an SU_/SR_/SBP_/SE_/SA_ asset name."),
			FName(*GSeinAutoTagSourceName));
	}

	return Manager.RequestGameplayTag(TagName, /*ErrorIfNotFound*/ false);
}

void SeinAutoTag::RegisterTagIfNeeded(const FGameplayTag& Tag)
{
	if (!Tag.IsValid()) return;

	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	// Fast path: tag is already in the tree (e.g. native-declared via
	// UE_DEFINE_GAMEPLAY_TAG_COMMENT, or already written to INI by an
	// earlier Derive call). RequestGameplayTag is cheap when the tag
	// exists.
	if (Manager.RequestGameplayTag(Tag.GetTagName(), /*ErrorIfNotFound*/ false).IsValid())
	{
		return;
	}

	// Otherwise persist via the editor module's INI path. AddNativeGameplayTag
	// is the wrong tool post-init — it's gated by `bDoneAddingNativeTags`
	// (see UE_5.7\\Runtime\\GameplayTags\\Private\\GameplayTagsManager.cpp:2401)
	// and silently no-ops after engine startup. AddNewGameplayTagToINI writes
	// to a config-file source, broadcasts OnTagSettingsChanged, and refreshes
	// the in-memory tag tree — the standard "add tag at runtime" path that
	// the engine's own Tag Manager UI uses.
	if (IGameplayTagsEditorModule::IsAvailable())
	{
		IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(
			Tag.GetTagName().ToString(),
			TEXT("Auto-generated by SeinARTS."),
			FName(*GSeinAutoTagSourceName));
	}
}

static FString SeinAutoTagLocal::FindCollidingAssetPathInternal(
	const FGameplayTag& Tag,
	const FString& IgnorePackagePath,
	const FString& SearchPackageRoot)
{
	if (!Tag.IsValid()) return FString();

	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

	const FString TargetTagStr = Tag.ToString();

	// The tag value each candidate carries is surfaced onto its FAssetData by the
	// USeinAbility / USeinEffect / ASeinActor GetAssetRegistryTags overrides, so
	// the common case reads it straight from the registry with NO asset load —
	// the previous implementation soft-loaded every candidate BP + CDO here,
	// which was the dominant cost of renames and regenerate sweeps. Two carve-
	// outs keep behavior identical to that always-load scan:
	//   1. Already-loaded assets are read live from their CDO, so unsaved
	//      in-memory edits win (the registry only reflects the last save).
	//   2. Assets with no surfaced tag yet (saved before this surfacing existed)
	//      fall back to a load — no real collision is ever missed; the fast path
	//      takes over once the asset is next saved/loaded.
	//
	// Three base-class buckets, same as before:
	//   1. USeinAbility (AbilityTag)        2. USeinEffect (EffectTag)
	//   3. ASeinActor  (IdentityTag, nested in the entity bridge's ComponentData)

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);
	FString NormalizedSearchRoot = SearchPackageRoot;
	while (NormalizedSearchRoot.EndsWith(TEXT("/")))
	{
		NormalizedSearchRoot.LeftChopInline(1, EAllowShrinking::No);
	}

	for (const FAssetData& Asset : Candidates)
	{
		const FString PackageName = Asset.PackageName.ToString();
		if (!NormalizedSearchRoot.IsEmpty()
			&& PackageName != NormalizedSearchRoot
			&& !PackageName.StartsWith(
				NormalizedSearchRoot + TEXT("/")))
		{
			continue;
		}
		if (!IgnorePackagePath.IsEmpty()
			&& PackageName == IgnorePackagePath)
		{
			continue;
		}

		// Skip BPs that aren't a SeinARTS taggable type. Cheap test on the
		// generated class name without loading the BP.
		const FString ParentClass = Asset.GetTagValueRef<FString>(FBlueprintTags::ParentClassPath);
		if (ParentClass.IsEmpty()) continue;

		const bool bIsAbility = ParentClass.Contains(TEXT("SeinAbility"));
		const bool bIsEffect  = ParentClass.Contains(TEXT("SeinEffect"));
		const bool bIsActor   = ParentClass.Contains(TEXT("SeinActor"));
		if (!bIsAbility && !bIsEffect && !bIsActor) continue;

		bool bCollides = false;

		if (const UBlueprint* LoadedBP = Cast<UBlueprint>(Asset.FastGetAsset(/*bLoad*/ false)))
		{
			// Already in memory — read the live CDO so unsaved edits are honored.
			bCollides = SeinAutoTagLocal::CDOHasMatchingTag(LoadedBP, Tag);
		}
		else
		{
			// Not loaded — read the surfaced tag straight from the registry.
			const FName TagKey = bIsAbility ? SeinAssetTagKeys::AbilityTag()
			                   : bIsEffect  ? SeinAssetTagKeys::EffectTag()
			                                : SeinAssetTagKeys::IdentityTag();
			FString AssetTagStr;
			if (Asset.GetTagValue<FString>(TagKey, AssetTagStr))
			{
				bCollides = (AssetTagStr == TargetTagStr);
			}
			else
			{
				// No surfaced tag (asset predates the surfacing override) — fall
				// back to a load so a real collision is never missed.
				bCollides = SeinAutoTagLocal::CDOHasMatchingTag(
					Cast<UBlueprint>(Asset.GetAsset()), Tag);
			}
		}

		if (bCollides)
		{
			return PackageName;
		}
	}

	return FString();
}

FString SeinAutoTag::FindCollidingAssetPath(
	const FGameplayTag& Tag,
	const FString& IgnorePackagePath)
{
	return SeinAutoTagLocal::FindCollidingAssetPathInternal(
		Tag,
		IgnorePackagePath,
		FString());
}

static FSeinAutoTagRegenerationResult
	SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
	UBlueprint* OwningBP,
	bool bForceOverManual,
	const FString& CollisionSearchPackageRoot)
{
	FSeinAutoTagRegenerationResult Result;
	if (!OwningBP || !OwningBP->GeneratedClass)
	{
		return Result;
	}

	const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>();
	if (!Settings || !Settings->bEnableAutoTagGeneration)
	{
		Result.Outcome =
			ESeinAutoTagRegenerationOutcome::AutoTagDisabled;
		return Result;
	}

	UObject* CDO = OwningBP->GeneratedClass->GetDefaultObject();
	if (!CDO)
	{
		return Result;
	}

	struct FAutoTagTarget
	{
		FGameplayTag* Tag = nullptr;
		bool* bAutoGenerated = nullptr;
	};
	TArray<FAutoTagTarget> Targets;
	if (USeinAbility* Ability = Cast<USeinAbility>(CDO))
	{
		Targets.Add({&Ability->AbilityTag, &Ability->bAutoGeneratedTag});
	}
	else if (USeinEffect* Effect = Cast<USeinEffect>(CDO))
	{
		Targets.Add({&Effect->EffectTag, &Effect->bAutoGeneratedTag});
	}
	else if (ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
	{
		// Identity components are designer-authored. We update existing
		// FSeinIdentityPayload entries but never synthesize one — a BP
		// without an identity component just doesn't participate in the
		// tagging system (it's still a valid Sein entity, e.g. a generic
		// projectile or environment prop).
		TArray<USeinEntityBridgeComponent*> Bridges;
		SeinActor->GetComponents<USeinEntityBridgeComponent>(Bridges);
		for (USeinEntityBridgeComponent* Bridge : Bridges)
		{
			if (!Bridge) continue;
			for (FInstancedStruct& Entry : Bridge->ComponentData)
			{
				if (!Entry.IsValid()) continue;
				if (Entry.GetScriptStruct() != FSeinIdentityPayload::StaticStruct()) continue;
				FSeinIdentityPayload& Identity = Entry.GetMutable<FSeinIdentityPayload>();
				Targets.Add({
					&Identity.IdentityTag,
					&Identity.bAutoGeneratedTag});
			}
		}
	}

	if (Targets.IsEmpty())
	{
		Result.Outcome =
			ESeinAutoTagRegenerationOutcome::UnsupportedAsset;
		return Result;
	}

	bool bHasEligibleTarget = false;
	for (const FAutoTagTarget& Target : Targets)
	{
		bHasEligibleTarget = bHasEligibleTarget
			|| bForceOverManual
			|| *Target.bAutoGenerated;
	}
	if (!bHasEligibleTarget)
	{
		Result.Outcome =
			ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned;
		return Result;
	}

	Result.DerivedTag = SeinAutoTag::DeriveTagFromAssetName(
		OwningBP->GetFName(), Settings);
	if (!Result.DerivedTag.IsValid())
	{
		Result.Outcome =
			ESeinAutoTagRegenerationOutcome::TagDerivationFailed;
		return Result;
	}

	bool bNeedsChange = false;
	for (const FAutoTagTarget& Target : Targets)
	{
		if ((bForceOverManual || *Target.bAutoGenerated)
			&& (*Target.Tag != Result.DerivedTag
				|| !*Target.bAutoGenerated))
		{
			bNeedsChange = true;
			break;
		}
	}
	if (!bNeedsChange)
	{
		Result.Outcome =
			ESeinAutoTagRegenerationOutcome::AlreadyCurrent;
		return Result;
	}

	Result.CollidingAssetPath = FindCollidingAssetPathInternal(
		Result.DerivedTag,
		OwningBP->GetOutermost()->GetName(),
		CollisionSearchPackageRoot);
	if (!Result.CollidingAssetPath.IsEmpty())
	{
		Result.Outcome = ESeinAutoTagRegenerationOutcome::Collision;
		UE_LOG(LogSeinAutoTagGen, Warning,
			TEXT("Regenerate '%s' skipped - new tag '%s' collides with '%s'."),
			*OwningBP->GetName(),
			*Result.DerivedTag.ToString(),
			*Result.CollidingAssetPath);
		return Result;
	}

	for (const FAutoTagTarget& Target : Targets)
	{
		if (!bForceOverManual && !*Target.bAutoGenerated)
		{
			continue;
		}
		*Target.Tag = Result.DerivedTag;
		*Target.bAutoGenerated = true;
	}
	SeinAutoTag::RegisterTagIfNeeded(Result.DerivedTag);
	FBlueprintEditorUtils::MarkBlueprintAsModified(OwningBP);
	Result.Outcome = ESeinAutoTagRegenerationOutcome::Updated;
	return Result;
}

FSeinAutoTagRegenerationResult SeinAutoTag::RegenerateAssetTagDetailed(
	UBlueprint* OwningBP,
	bool bForceOverManual)
{
	return SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
		OwningBP,
		bForceOverManual,
		FString());
}

#if WITH_DEV_AUTOMATION_TESTS
FSeinAutoTagRegenerationResult
	SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
		UBlueprint* OwningBP,
		bool bForceOverManual,
		const FString& CollisionSearchPackageRoot)
{
	return SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
		OwningBP,
		bForceOverManual,
		CollisionSearchPackageRoot);
}
#endif

bool SeinAutoTag::RegenerateAssetTag(
	UBlueprint* OwningBP,
	bool bForceOverManual)
{
	return RegenerateAssetTagDetailed(
		OwningBP, bForceOverManual).WasUpdated();
}

int32 SeinAutoTag::RegenerateAllAssetTags(bool bForceOverManual)
{
	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);

	// Batch tag-tree refresh. AddNewGameplayTagToINI inside Derive triggers
	// an EditorRefreshGameplayTagTree per call (destroy + reload + reconstruct
	// the full tag tree from all sources). For a sweep over N assets that's
	// O(N) refreshes — each linear in total tag count. Suspending the refresh
	// collapses the whole sweep into one final refresh at Resume time.
	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	const FGuid SuspendToken = FGuid::NewGuid();
	Manager.SuspendEditorRefreshGameplayTagTree(SuspendToken);

	int32 NumChanged = 0;
	int32 NumScanned = 0;
	int32 NumTaggableCandidates = 0;
	TArray<TWeakObjectPtr<UBlueprint>> DeferredAfterRefresh;
	for (const FAssetData& Asset : Candidates)
	{
		++NumScanned;
		const FString ParentClass = Asset.GetTagValueRef<FString>(FBlueprintTags::ParentClassPath);
		if (ParentClass.IsEmpty()) continue;
		const bool bIsSeinTaggable =
			ParentClass.Contains(TEXT("SeinAbility")) ||
			ParentClass.Contains(TEXT("SeinEffect")) ||
			ParentClass.Contains(TEXT("SeinActor"));
		if (!bIsSeinTaggable) continue;
		++NumTaggableCandidates;

		UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
		if (!BP) continue;
		const FSeinAutoTagRegenerationResult Result =
			RegenerateAssetTagDetailed(BP, bForceOverManual);
		if (Result.WasUpdated())
		{
			++NumChanged;
		}
		else if (Result.Outcome ==
			ESeinAutoTagRegenerationOutcome::TagDerivationFailed)
		{
			// A missing tag is written while tree refresh is suspended, so
			// its FGameplayTag becomes available only after Resume. Unmapped
			// names can also land here; the second pass remains a no-op.
			DeferredAfterRefresh.Add(BP);
		}
	}

	Manager.ResumeEditorRefreshGameplayTagTree(SuspendToken);
	for (const TWeakObjectPtr<UBlueprint>& WeakBP : DeferredAfterRefresh)
	{
		if (UBlueprint* BP = WeakBP.Get())
		{
			if (RegenerateAssetTagDetailed(
					BP, bForceOverManual).WasUpdated())
			{
				++NumChanged;
			}
		}
	}

	UE_LOG(LogSeinAutoTagGen, Log,
		TEXT("RegenerateAllAssetTags (force=%d): scanned %d BP(s), %d Sein-taggable, %d updated."),
		bForceOverManual ? 1 : 0, NumScanned, NumTaggableCandidates, NumChanged);
	return NumChanged;
}

#undef LOCTEXT_NAMESPACE
