/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file         SeinAutoTagGenerator.cpp
 * @author       RJ Macklem
 * @created      7 Sep 2026
 * @latest       7 Sep 2026
 * @brief        Computes initial identities without side effects and writes authoritative authoring values.
 * @disclaimer   Generated with assistance from an AI language model.
 */

#include "Util/SeinAutoTagGenerator.h"
#include "UObject/ObjectRedirector.h"

#include "Settings/PluginSettings.h"
#include "Data/SeinTagPrefixMapping.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Components/SeinIdentityPayload.h"
#include "Actor/SeinActor.h"
#include "Actor/SeinEntityBridgeComponent.h"
#include "Core/SeinAssetTagKeys.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsEditorModule.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "UObject/Package.h"
#include "Misc/Guid.h"
#include "Misc/PackageName.h"
#include "Authoring/SeinEntityComponent.h"
#include "Engine/InheritableComponentHandler.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/SCS_Node.h"
#include "ScopedTransaction.h"
#include "Editor.h"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAutoTagGen, Log, All);

#define LOCTEXT_NAMESPACE "SeinAutoTagGenerator"

/** Dedicated INI source the auto-tag system writes generated tags into.
 *  Lives at `<Project>/Config/Tags/SeinAutoGeneratedTags.ini`. Designers
 *  can open Project Settings → Project → Gameplay Tags and see this as a
 *  separate source alongside their hand-curated `DefaultGameplayTags.ini`.
 *  Cleanup considers only exclusively owned, unused generated entries. */
static const FString GSeinAutoTagSourceName = TEXT("SeinAutoGeneratedTags.ini");

namespace SeinAutoTagLocal
{
	/** Split an asset name on `_`. First segment is the prefix; rest is the
	 *  name body. Returns false if there's no `_` in the name. */
	static bool SplitOnUnderscore(const FString& AssetName, FString& OutPrefix, TArray<FString>& OutNameSegments)
	{
		TArray<FString> AllSegments;
		AssetName.ParseIntoArray(AllSegments, TEXT("_"), /*InCullEmpty*/ false);
		if (AllSegments.Num() < 2) return false;
		OutPrefix = AllSegments[0];
		OutNameSegments.Reset(AllSegments.Num() - 1);
		for (int32 i = 1; i < AllSegments.Num(); ++i)
		{
			// Skip blank inner segments (e.g. "SA__Move" — defensive).
			if (!AllSegments[i].IsEmpty())
			{
				OutNameSegments.Add(AllSegments[i]);
			}
		}
		return OutNameSegments.Num() > 0;
	}

	/** Strip the trailing "_C" that Blueprint-generated classes carry. */
	static FString StripBlueprintClassSuffix(const FString& Name)
	{
		if (Name.EndsWith(TEXT("_C")))
		{
			return Name.LeftChop(2);
		}
		return Name;
	}

	/** Read the live (in-memory) CDO of a loaded Sein BP and test whether its
	 *  identity tag equals `Tag`. Entity identity comes from its authoring component,
	 *  with a legacy payload fallback only when no authoring component exists.
	 *  Loaded values take precedence over the last saved registry value. */
	static bool CDOHasMatchingTag(const UBlueprint* BP, const FGameplayTag& Tag)
	{
		if (!BP || !BP->GeneratedClass) return false;
		const UObject* CDO = BP->GeneratedClass->GetDefaultObject();
		if (!CDO) return false;

		if (const USeinAbility* Ability = Cast<USeinAbility>(CDO))
		{
			return Ability->AbilityTag == Tag;
		}
		if (const USeinEffect* Effect = Cast<USeinEffect>(CDO))
		{
			return Effect->EffectTag == Tag;
		}
        FGameplayTag Identity;
        bool bGenerated = false;
        return SeinAutoTag::ReadAssetIdentity(BP, Identity, bGenerated) && Identity == Tag;
	}

	static FString FindCollidingAssetPathInternal(
		const FGameplayTag& Tag,
		const FString& IgnorePackagePath,
		const FString& SearchPackageRoot);

	static FSeinAutoTagRegenerationResult
		RegenerateAssetTagDetailedInternal(
			UBlueprint* OwningBP,
			bool bForceOverManual,
			const FString& CollisionSearchPackageRoot);
}

bool FSeinAutoTagRegenerationResult::IsFailure() const
{
	return Outcome != ESeinAutoTagRegenerationOutcome::Updated
		&& Outcome != ESeinAutoTagRegenerationOutcome::AlreadyCurrent
		&& Outcome !=
			ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned;
}

FText FSeinAutoTagRegenerationResult::ToUserMessage(
	const UBlueprint* OwningBP) const
{
	const FText AssetName = FText::FromString(
		OwningBP ? OwningBP->GetName() : TEXT("<unknown>"));
	const FText TagName = FText::FromString(
		DerivedTag.IsValid()
			? DerivedTag.ToString()
			: TEXT("<unresolved>"));

	if (!Detail.IsEmpty()) return Detail;
	switch (Outcome)
	{
	case ESeinAutoTagRegenerationOutcome::Updated:
		return FText::Format(
			LOCTEXT("Updated", "Updated {0} to auto tag {1}."),
			AssetName,
			TagName);
	case ESeinAutoTagRegenerationOutcome::AlreadyCurrent:
		return FText::Format(
			LOCTEXT("AlreadyCurrent", "{0} already uses auto tag {1}."),
			AssetName,
			TagName);
	case ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned:
		return FText::Format(
			LOCTEXT("DesignerOwned",
				"{0} has a designer-owned tag. Existing identities are preserved; use Rename Tag for an explicit migration."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::InvalidBlueprint:
		return LOCTEXT("InvalidBlueprint",
			"The selected Blueprint has no generated class or class defaults to update.");
	case ESeinAutoTagRegenerationOutcome::AutoTagDisabled:
		return LOCTEXT("AutoTagDisabled",
			"Auto tag generation is disabled in SeinARTS project settings.");
	case ESeinAutoTagRegenerationOutcome::UnsupportedAsset:
		return FText::Format(
			LOCTEXT("UnsupportedAsset",
				"{0} has no supported SeinARTS ability, effect, or identity tag to update."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::TagDerivationFailed:
		return FText::Format(
			LOCTEXT("DerivationFailed",
				"No auto tag could be derived for {0}. Check its asset-name prefix and the Prefix Category Mappings in SeinARTS project settings."),
			AssetName);
	case ESeinAutoTagRegenerationOutcome::Collision:
		return FText::Format(
			LOCTEXT("Collision",
				"Cannot assign auto tag {0} to {1}; it is already used by {2}. Assign a distinct identity to the copied asset; do not redirect the original tag."),
			TagName,
			AssetName,
			FText::FromString(CollidingAssetPath));
    case ESeinAutoTagRegenerationOutcome::MigrationRequired:
        return LOCTEXT("MigrationRequired", "This asset already has a stable identity. Use Rename Tag to migrate its references explicitly.");
    case ESeinAutoTagRegenerationOutcome::EditorBusy:
        return LOCTEXT("EditorBusy", "Stop Play in Editor before changing identity tags.");
    case ESeinAutoTagRegenerationOutcome::AuthoringConflict:
        return LOCTEXT("AuthoringConflict", "The identity component could not be overridden in this Blueprint. Its parent was left unchanged.");
	default:
		return LOCTEXT("Unknown", "Auto tag regeneration failed.");
	}
}

const FSeinTagPrefixMapping* SeinAutoTag::FindMatchingPrefixMapping(
	const FName& AssetName,
	const USeinARTSCoreSettings* Settings)
{
	if (!Settings) return nullptr;
	const FString NameStr = AssetName.ToString();

	FString Prefix;
	TArray<FString> Body;
	if (!SeinAutoTagLocal::SplitOnUnderscore(NameStr, Prefix, Body)) return nullptr;

	for (const FSeinTagPrefixMapping& Mapping : Settings->PrefixCategoryMappings)
	{
		if (Mapping.AssetPrefix == Prefix && !Mapping.TagCategory.IsEmpty())
		{
			return &Mapping;
		}
	}
	return nullptr;
}

FName SeinAutoTag::ProposeTagName(const FName& AssetName, const USeinARTSCoreSettings* Settings)
{
    if (!Settings || !Settings->bEnableAutoTagGeneration) return NAME_None;
    FString Prefix;
    TArray<FString> Body;
    if (!SeinAutoTagLocal::SplitOnUnderscore(AssetName.ToString(), Prefix, Body)) return NAME_None;
    const FSeinTagPrefixMapping* Mapping = FindMatchingPrefixMapping(AssetName, Settings);
    if (!Mapping) return NAME_None;
    const FString Name = (Settings->TagPrefix.IsEmpty() ? FString() : Settings->TagPrefix + TEXT("."))
        + Mapping->TagCategory + TEXT(".")
        + FString::Join(Body, Settings->bAllowTagLayering ? TEXT(".") : TEXT("_"));
    return UGameplayTagsManager::Get().IsValidGameplayTagString(Name) ? FName(*Name) : NAME_None;
}

FGameplayTag SeinAutoTag::DeriveTagFromAssetName(const FName& AssetName, const USeinARTSCoreSettings* Settings)
{
    return UGameplayTagsManager::Get().RequestGameplayTag(
        ProposeTagName(FName(*SeinAutoTagLocal::StripBlueprintClassSuffix(AssetName.ToString())), Settings), false);
}

void SeinAutoTag::RegisterTagIfNeeded(const FGameplayTag& Tag)
{
    if (!Tag.IsValid() || UGameplayTagsManager::Get().RequestGameplayTag(Tag.GetTagName(), false).IsValid()) return;
    IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(Tag.ToString(),
        TEXT("Auto-generated by SeinARTS."), FName(*GSeinAutoTagSourceName));
}

static FString SeinAutoTagLocal::FindCollidingAssetPathInternal(
	const FGameplayTag& Tag,
	const FString& IgnorePackagePath,
	const FString& SearchPackageRoot)
{
	if (!Tag.IsValid()) return FString();

	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();


	// The tag value each candidate carries is surfaced onto its FAssetData by the
	// USeinAbility / USeinEffect / ASeinActor GetAssetRegistryTags overrides, so
	// the common case reads it straight from the registry with NO asset load —
	// the previous implementation soft-loaded every candidate BP + CDO here,
	// which was the dominant cost of renames and regenerate sweeps. Two carve-
	// outs keep behavior identical to that always-load scan:
	//   1. Already-loaded assets are read live from their CDO, so unsaved
	//      in-memory edits win (the registry only reflects the last save).
	//   2. Assets with no surfaced tag yet (saved before this surfacing existed)
	//      fall back to a load — no real collision is ever missed; the fast path
	//      takes over once the asset is next saved/loaded.
	//
	// Ability, Effect and actor identity share one uniqueness namespace.

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);
	Candidates.Sort([](const FAssetData& A, const FAssetData& B) { return A.PackageName.ToString() < B.PackageName.ToString(); });
	FString NormalizedSearchRoot = SearchPackageRoot;
	while (NormalizedSearchRoot.EndsWith(TEXT("/")))
	{
		NormalizedSearchRoot.LeftChopInline(1, EAllowShrinking::No);
	}

	for (const FAssetData& Asset : Candidates)
	{
		const FString PackageName = Asset.PackageName.ToString();
		if (!NormalizedSearchRoot.IsEmpty()
			&& PackageName != NormalizedSearchRoot
			&& !PackageName.StartsWith(
				NormalizedSearchRoot + TEXT("/")))
		{
			continue;
		}
		if (!IgnorePackagePath.IsEmpty()
			&& PackageName == IgnorePackagePath)
		{
			continue;
		}

		// During native rename the disk registry may still advertise the old Blueprint,
		// while its loaded object is already a redirector rather than an identity owner.
		if (FindObject<UObjectRedirector>(nullptr, *Asset.GetObjectPathString())) continue;
		bool bCollides = false;
		if (const auto* LoadedBP = Cast<UBlueprint>(Asset.FastGetAsset(false)))
		{
			bCollides = CDOHasMatchingTag(LoadedBP, Tag);
		}
		else
		{
			bool bHasIdentityMetadata = false;
			for (FName Key : {SeinAssetTagKeys::AbilityTag(), SeinAssetTagKeys::EffectTag(), SeinAssetTagKeys::IdentityTag()})
			{
				FString Value;
				if (Asset.GetTagValue(Key, Value))
				{
					bHasIdentityMetadata = true;
					bCollides |= FName(*Value) == Tag.GetTagName();
				}
			}
			if (!bHasIdentityMetadata)
			{
				const FString Parent = Asset.GetTagValueRef<FString>(FBlueprintTags::NativeParentClassPath);
				const UClass* Native = FindObject<UClass>(nullptr, *FPackageName::ExportTextPathToObjectPath(Parent));
				// Unknown ancestry must not silently hide an older Blueprint from collision checks.
				if (!Native || Native->IsChildOf(USeinAbility::StaticClass())
					|| Native->IsChildOf(USeinEffect::StaticClass()) || Native->IsChildOf(ASeinActor::StaticClass()))
					bCollides = CDOHasMatchingTag(Cast<UBlueprint>(Asset.GetAsset()), Tag);
			}
		}

		if (bCollides)
		{
			return PackageName;
		}
	}

	return FString();
}

FString SeinAutoTag::FindCollidingAssetPath(
	const FGameplayTag& Tag,
	const FString& IgnorePackagePath)
{
	return SeinAutoTagLocal::FindCollidingAssetPathInternal(
		Tag,
		IgnorePackagePath,
		FString());
}

namespace SeinAutoTagLocal
{
    struct FIdentityTarget
    {
        FGameplayTag* Tag = nullptr;
        bool* Generated = nullptr;
        UObject* Owner = nullptr;
        USeinEntityBridgeComponent* Bridge = nullptr;
        USeinIdentityComponent* Component = nullptr;
    };

    static FIdentityTarget ResolveTarget(const UBlueprint* BP)
    {
        FIdentityTarget Result;
        if (!BP || !BP->GeneratedClass) return Result;
        UObject* CDO = BP->GeneratedClass->GetDefaultObject();
        if (auto* Ability = Cast<USeinAbility>(CDO))
            return {&Ability->AbilityTag, &Ability->bAutoGeneratedTag, Ability};
        if (auto* Effect = Cast<USeinEffect>(CDO))
            return {&Effect->EffectTag, &Effect->bAutoGeneratedTag, Effect};
        const auto* Actor = Cast<ASeinActor>(CDO);
        if (!Actor) return Result;
        auto* Bridge = Actor->FindComponentByClass<USeinEntityBridgeComponent>();
        TArray<const USeinIdentityComponent*> Components;
        AActor::GetActorClassDefaultComponents<USeinIdentityComponent>(BP->GeneratedClass.Get(), Components);
        if (!Components.IsEmpty())
        {
            // Multiple or disabled authoring components never fall back to stale baked data.
            if (Components.Num() != 1 || !Components[0]->bInjectionEnabled) return Result;
            auto* Component = const_cast<USeinIdentityComponent*>(Components[0]);
            return {&Component->Identity.IdentityTag, &Component->Identity.bAutoGeneratedTag, Component, Bridge, Component};
        }
        if (Bridge)
            for (FInstancedStruct& Entry : Bridge->ComponentData)
                if (auto* Identity = Entry.GetMutablePtr<FSeinIdentityPayload>())
                    return {&Identity->IdentityTag, &Identity->bAutoGeneratedTag, Bridge, Bridge};
        return Result;
    }

    static bool MakeWritable(UBlueprint* BP, FIdentityTarget& Target)
    {
        if (!Target.Owner || Target.Owner->GetOutermost() == BP->GetOutermost()) return Target.Owner != nullptr;
        if (!Target.Component) return false;
        for (UClass* Class = BP->GeneratedClass; Class; Class = Class->GetSuperClass())
        {
            auto* ParentBP = Cast<UBlueprint>(Class->ClassGeneratedBy);
            if (!ParentBP || !ParentBP->SimpleConstructionScript) continue;
            for (USCS_Node* Node : ParentBP->SimpleConstructionScript->GetAllNodes())
            {
                if (Node->GetActualComponentTemplate(CastChecked<UBlueprintGeneratedClass>(BP->GeneratedClass)) != Target.Component) continue;
                auto* Handler = BP->GetInheritableComponentHandler(true);
                if (!Handler) return false;
                Handler->Modify();
                auto* Component = Cast<USeinIdentityComponent>(Handler->CreateOverridenComponentTemplate(FComponentKey(Node)));
                if (!Component) return false;
                Target = {&Component->Identity.IdentityTag, &Component->Identity.bAutoGeneratedTag, Component, Target.Bridge, Component};
                return true;
            }
        }
        return false;
    }

    static FSeinAutoTagRegenerationResult Assign(UBlueprint* BP, FName Proposed, const FString& SearchRoot)
    {
        FSeinAutoTagRegenerationResult Result;
        if (GEditor && GEditor->PlayWorld)
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::EditorBusy;
            return Result;
        }
        FIdentityTarget Target = ResolveTarget(BP);
        if (!Target.Tag)
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::UnsupportedAsset;
            return Result;
        }
        if (Proposed.IsNone())
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::TagDerivationFailed;
            return Result;
        }
        auto& Manager = UGameplayTagsManager::Get();
        Result.DerivedTag = Manager.RequestGameplayTag(Proposed, false);
        if (Result.DerivedTag.IsValid() && Result.DerivedTag.GetTagName() != Proposed)
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::AuthoringConflict;
            Result.Detail = LOCTEXT("RedirectedName", "The proposed name is a compatibility redirect. Choose a new unused identity name.");
            return Result;
        }
        // Check collisions even when the existing value already looks current.
        Result.CollidingAssetPath = FindCollidingAssetPathInternal(Result.DerivedTag, BP->GetOutermost()->GetName(), SearchRoot);
        if (!Result.CollidingAssetPath.IsEmpty())
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::Collision;
            return Result;
        }
        if (*Target.Tag == Result.DerivedTag && Result.DerivedTag.IsValid() && *Target.Generated)
        {
            SeinAutoTag::RememberGeneratedIdentity(BP, Result.DerivedTag);
            Result.Outcome = ESeinAutoTagRegenerationOutcome::AlreadyCurrent;
            return Result;
        }
        const FScopedTransaction Transaction(LOCTEXT("AssignIdentity", "Assign generated identity tag"));
        BP->Modify();
        if (!MakeWritable(BP, Target))
        {
            Result.Outcome = ESeinAutoTagRegenerationOutcome::AuthoringConflict;
            return Result;
        }
        if (!Result.DerivedTag.IsValid())
        {
            if (!IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(Proposed.ToString(),
                TEXT("Auto-generated by SeinARTS."), FName(*GSeinAutoTagSourceName)))
            {
                Result.Outcome = ESeinAutoTagRegenerationOutcome::TagDerivationFailed;
                return Result;
            }
            Result.DerivedTag = Manager.RequestGameplayTag(Proposed, false);
            if (!Result.DerivedTag.IsValid()) return Result;
        }
        Target.Owner->Modify();
        // Capture migration state before assignment; first-capture seeding must not restore the old tag.
        if (Target.Component && Target.Bridge) Target.Bridge->BakeAuthoredDataComponents(true);
        Target = ResolveTarget(BP);
        if (!Target.Tag) return Result;
        if (Target.Bridge && !Target.Component) Target.Bridge->BeginComponentDataEdit();
        *Target.Tag = Result.DerivedTag;
        *Target.Generated = true;
        if (Target.Component && Target.Bridge) Target.Bridge->NotifyAuthoringComponentEdited(*Target.Component);
        else if (Target.Bridge)
        {
            // Legacy payload authors still use the bridge's propagation and undo path.
            Target.Bridge->EndComponentDataEdit();
        }
        SeinAutoTag::RememberGeneratedIdentity(BP, Result.DerivedTag);
        FBlueprintEditorUtils::MarkBlueprintAsModified(BP);
        Result.Outcome = ESeinAutoTagRegenerationOutcome::Updated;
        return Result;
    }
}

bool SeinAutoTag::ReadAssetIdentity(const UBlueprint* BP, FGameplayTag& OutTag, bool& bOutGenerated)
{
    OutTag = FGameplayTag();
    bOutGenerated = false;
    const auto Target = SeinAutoTagLocal::ResolveTarget(BP);
    if (!Target.Tag) return false;
    OutTag = *Target.Tag;
    bOutGenerated = *Target.Generated;
    return true;
}

FSeinAutoTagRegenerationResult SeinAutoTag::InitializeNewAssetTag(UBlueprint* BP)
{
    return SeinAutoTagLocal::Assign(BP, ProposeTagName(BP ? BP->GetFName() : NAME_None,
        GetDefault<USeinARTSCoreSettings>()), FString());
}

static FSeinAutoTagRegenerationResult SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
    UBlueprint* BP, bool bForceOverManual, const FString& SearchRoot)
{
    FSeinAutoTagRegenerationResult Result;
    if (!BP || !BP->GeneratedClass) return Result;
    const auto* Settings = GetDefault<USeinARTSCoreSettings>();
    if (!Settings->bEnableAutoTagGeneration)
    {
        Result.Outcome = ESeinAutoTagRegenerationOutcome::AutoTagDisabled;
        return Result;
    }
    FGameplayTag Current;
    bool bGenerated = false;
    if (!SeinAutoTag::ReadAssetIdentity(BP, Current, bGenerated))
    {
        Result.Outcome = ESeinAutoTagRegenerationOutcome::UnsupportedAsset;
        return Result;
    }
    if (!bForceOverManual && !bGenerated)
    {
        Result.Outcome = ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned;
        return Result;
    }
    const FName Proposed = SeinAutoTag::ProposeTagName(BP->GetFName(), Settings);
    if (Current.IsValid())
    {
        Result.DerivedTag = Current;
        Result.CollidingAssetPath = FindCollidingAssetPathInternal(Current, BP->GetOutermost()->GetName(), SearchRoot);
        if (!Result.CollidingAssetPath.IsEmpty()) Result.Outcome = ESeinAutoTagRegenerationOutcome::Collision;
        else if (Current.GetTagName() != Proposed && (bGenerated || bForceOverManual))
            return SeinAutoTag::ReconcileGeneratedIdentity(BP, Current.GetTagName());
        else return Assign(BP, Proposed, SearchRoot);
        return Result;
    }
    const FName Previous = SeinAutoTag::LastGeneratedIdentity(BP);
    if (!Previous.IsNone() && Previous != Proposed)
        return SeinAutoTag::ReconcileGeneratedIdentity(BP, Previous);
    return Assign(BP, Proposed, SearchRoot);
}

FSeinAutoTagRegenerationResult SeinAutoTag::RegenerateAssetTagDetailed(
	UBlueprint* OwningBP,
	bool bForceOverManual)
{
	return SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
		OwningBP,
		bForceOverManual,
		FString());
}

#if WITH_DEV_AUTOMATION_TESTS
FSeinAutoTagRegenerationResult
	SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
		UBlueprint* OwningBP,
		bool bForceOverManual,
		const FString& CollisionSearchPackageRoot)
{
	return SeinAutoTagLocal::RegenerateAssetTagDetailedInternal(
		OwningBP,
		bForceOverManual,
		CollisionSearchPackageRoot);
}
#endif

bool SeinAutoTag::RegenerateAssetTag(
	UBlueprint* OwningBP,
	bool bForceOverManual)
{
	return RegenerateAssetTagDetailed(
		OwningBP, bForceOverManual).WasUpdated();
}

int32 SeinAutoTag::RegenerateAllAssetTags(bool bForceOverManual)
{
	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);

    int32 NumChanged = 0, NumScanned = Candidates.Num(), NumTaggableCandidates = 0;
    for (const FAssetData& Asset : Candidates)
    {
        const FString NativePath = Asset.GetTagValueRef<FString>(FBlueprintTags::NativeParentClassPath);
        const UClass* Native = FindObject<UClass>(nullptr, *FPackageName::ExportTextPathToObjectPath(NativePath));
        if (!Native || !(Native->IsChildOf(USeinAbility::StaticClass()) || Native->IsChildOf(USeinEffect::StaticClass()) || Native->IsChildOf(ASeinActor::StaticClass()))) continue;
        ++NumTaggableCandidates;
        UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
        const auto Result = RegenerateAssetTagDetailed(BP, bForceOverManual);
        if (Result.WasUpdated()) ++NumChanged;
        else if (Result.IsFailure()) UE_LOG(LogSeinAutoTagGen, Warning, TEXT("%s"), *Result.ToUserMessage(BP).ToString());
    }

	UE_LOG(LogSeinAutoTagGen, Log,
		TEXT("RegenerateAllAssetTags (force=%d): scanned %d BP(s), %d Sein-taggable, %d updated."),
		bForceOverManual ? 1 : 0, NumScanned, NumTaggableCandidates, NumChanged);
	return NumChanged;
}

#undef LOCTEXT_NAMESPACE
