/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file    SeinAutoTagGenerator.cpp
 */

#include "Util/SeinAutoTagGenerator.h"

#include "Settings/PluginSettings.h"
#include "Data/SeinTagPrefixMapping.h"
#include "Abilities/SeinAbility.h"
#include "Effects/SeinEffect.h"
#include "Components/SeinIdentityComponent.h"
#include "Actor/SeinActor.h"
#include "Actor/SeinEntityComponent.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsEditorModule.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "UObject/Package.h"
#include "Misc/Guid.h"

DEFINE_LOG_CATEGORY_STATIC(LogSeinAutoTagGen, Log, All);

/** Dedicated INI source the auto-tag system writes generated tags into.
 *  Lives at `<Project>/Config/Tags/SeinAutoGeneratedTags.ini`. Designers
 *  can open Project Settings → Project → Gameplay Tags and see this as a
 *  separate source alongside their hand-curated `DefaultGameplayTags.ini`.
 *  Hand-edits to this file survive — the framework only ever appends. */
static const FString GSeinAutoTagSourceName = TEXT("SeinAutoGeneratedTags.ini");

namespace SeinAutoTagLocal
{
	/** Split an asset name on `_`. First segment is the prefix; rest is the
	 *  name body. Returns false if there's no `_` in the name. */
	static bool SplitOnUnderscore(const FString& AssetName, FString& OutPrefix, TArray<FString>& OutNameSegments)
	{
		TArray<FString> AllSegments;
		AssetName.ParseIntoArray(AllSegments, TEXT("_"), /*InCullEmpty*/ false);
		if (AllSegments.Num() < 2) return false;
		OutPrefix = AllSegments[0];
		OutNameSegments.Reset(AllSegments.Num() - 1);
		for (int32 i = 1; i < AllSegments.Num(); ++i)
		{
			// Skip blank inner segments (e.g. "SA__Move" — defensive).
			if (!AllSegments[i].IsEmpty())
			{
				OutNameSegments.Add(AllSegments[i]);
			}
		}
		return OutNameSegments.Num() > 0;
	}

	/** Strip the trailing "_C" that Blueprint-generated classes carry. */
	static FString StripBlueprintClassSuffix(const FString& Name)
	{
		if (Name.EndsWith(TEXT("_C")))
		{
			return Name.LeftChop(2);
		}
		return Name;
	}
}

const FSeinTagPrefixMapping* SeinAutoTag::FindMatchingPrefixMapping(
	const FName& AssetName,
	const USeinARTSCoreSettings* Settings)
{
	if (!Settings) return nullptr;
	const FString NameStr = SeinAutoTagLocal::StripBlueprintClassSuffix(AssetName.ToString());

	FString Prefix;
	TArray<FString> Body;
	if (!SeinAutoTagLocal::SplitOnUnderscore(NameStr, Prefix, Body)) return nullptr;

	for (const FSeinTagPrefixMapping& Mapping : Settings->PrefixCategoryMappings)
	{
		if (Mapping.AssetPrefix == Prefix && !Mapping.TagCategory.IsEmpty())
		{
			return &Mapping;
		}
	}
	return nullptr;
}

FGameplayTag SeinAutoTag::DeriveTagFromAssetName(
	const FName& AssetName,
	const USeinARTSCoreSettings* Settings)
{
	if (!Settings) return FGameplayTag();
	if (!Settings->bEnableAutoTagGeneration) return FGameplayTag();

	const FString NameStr = SeinAutoTagLocal::StripBlueprintClassSuffix(AssetName.ToString());

	FString Prefix;
	TArray<FString> Body;
	if (!SeinAutoTagLocal::SplitOnUnderscore(NameStr, Prefix, Body))
	{
		return FGameplayTag();
	}

	const FSeinTagPrefixMapping* Mapping = FindMatchingPrefixMapping(AssetName, Settings);
	if (!Mapping) return FGameplayTag();

	// Build the tag string segment-by-segment:
	//   <TagPrefix>.<Category>.<Body[0]>.<Body[1]>...
	// or with bAllowTagLayering=false:
	//   <TagPrefix>.<Category>.<Body joined by underscore>
	FString TagString;
	if (!Settings->TagPrefix.IsEmpty())
	{
		TagString = Settings->TagPrefix + TEXT(".");
	}
	TagString += Mapping->TagCategory;
	TagString += TEXT(".");

	if (Settings->bAllowTagLayering)
	{
		TagString += FString::Join(Body, TEXT("."));
	}
	else
	{
		TagString += FString::Join(Body, TEXT("_"));
	}

	// Register-and-lookup. The previous implementation used
	// `RequestGameplayTag(name, /*ErrorIfNotFound*/false)` which is pure
	// lookup — returns invalid for tags not yet in the manager's tree.
	// That silently broke the whole pipeline: tags weren't pre-registered
	// (we have no native UE_DEFINE_GAMEPLAY_TAG_COMMENT for auto-generated
	// SU_/SR_/SBP_ names), so Derive always returned invalid, factories
	// skipped stamping, and Force Regenerate found 0 assets.
	//
	// The FGameplayTag(FName) constructor is protected (friend-restricted
	// to UGameplayTagsManager), so we can't construct directly. The only
	// post-init path that produces a valid FGameplayTag is to write the
	// tag to an INI source via IGameplayTagsEditorModule, then look it up
	// — at which point it's in the tree and the lookup succeeds.
	//
	// AddNewGameplayTagToINI is idempotent (a duplicate add is a no-op),
	// so calling Derive repeatedly for the same name is cheap. It does
	// trigger an EditorRefreshGameplayTagTree per call, which is the
	// expensive part — RegenerateAllAssetTags batches refreshes via
	// Suspend/Resume to amortize that cost across the whole sweep.
	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	const FName TagName(*TagString);
	if (TagName.IsNone()) return FGameplayTag();

	// Fast path: already registered.
	FGameplayTag Existing = Manager.RequestGameplayTag(TagName, /*ErrorIfNotFound*/ false);
	if (Existing.IsValid()) return Existing;

	// Register via the editor module's INI path. Falls back to invalid
	// gracefully if the module isn't loaded (e.g. cooked-game contexts —
	// not a concern in practice since this file is editor-only, but
	// defensive against module load-order edge cases).
	if (IGameplayTagsEditorModule::IsAvailable())
	{
		IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(
			TagString,
			TEXT("Auto-generated by SeinARTS from an SU_/SR_/SBP_/SE_/SA_ asset name."),
			FName(*GSeinAutoTagSourceName));
	}

	return Manager.RequestGameplayTag(TagName, /*ErrorIfNotFound*/ false);
}

void SeinAutoTag::RegisterTagIfNeeded(const FGameplayTag& Tag)
{
	if (!Tag.IsValid()) return;

	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	// Fast path: tag is already in the tree (e.g. native-declared via
	// UE_DEFINE_GAMEPLAY_TAG_COMMENT, or already written to INI by an
	// earlier Derive call). RequestGameplayTag is cheap when the tag
	// exists.
	if (Manager.RequestGameplayTag(Tag.GetTagName(), /*ErrorIfNotFound*/ false).IsValid())
	{
		return;
	}

	// Otherwise persist via the editor module's INI path. AddNativeGameplayTag
	// is the wrong tool post-init — it's gated by `bDoneAddingNativeTags`
	// (see UE_5.7\\Runtime\\GameplayTags\\Private\\GameplayTagsManager.cpp:2401)
	// and silently no-ops after engine startup. AddNewGameplayTagToINI writes
	// to a config-file source, broadcasts OnTagSettingsChanged, and refreshes
	// the in-memory tag tree — the standard "add tag at runtime" path that
	// the engine's own Tag Manager UI uses.
	if (IGameplayTagsEditorModule::IsAvailable())
	{
		IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(
			Tag.GetTagName().ToString(),
			TEXT("Auto-generated by SeinARTS."),
			FName(*GSeinAutoTagSourceName));
	}
}

FString SeinAutoTag::FindCollidingAssetPath(
	const FGameplayTag& Tag,
	const FString& IgnorePackagePath)
{
	if (!Tag.IsValid()) return FString();

	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

	const FString TagString = Tag.ToString();

	// We can't query asset registry by an in-asset UPROPERTY directly, so
	// the scan loads the CDO for each candidate BP and reads the tag field.
	// Cost: O(N) BPs of the relevant base classes, each load triggers a
	// soft asset load. Fine for the rare collision-check path; if it ever
	// becomes hot, cache tag → asset path in the editor module.
	//
	// Three base-class buckets to scan:
	//   1. USeinAbility (AbilityTag)
	//   2. USeinEffect (EffectTag)
	//   3. ASeinActor with FSeinIdentityComponent on the entity bridge
	//      (IdentityTag) — checked via the BP CDO

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);

	for (const FAssetData& Asset : Candidates)
	{
		if (!IgnorePackagePath.IsEmpty() && Asset.PackageName.ToString() == IgnorePackagePath)
		{
			continue;
		}

		// Skip BPs that aren't a SeinARTS taggable type. Cheap test on the
		// generated class name without loading the BP.
		const FString ParentClass = Asset.GetTagValueRef<FString>(FBlueprintTags::ParentClassPath);
		if (ParentClass.IsEmpty()) continue;

		const bool bIsSeinTaggable =
			ParentClass.Contains(TEXT("SeinAbility")) ||
			ParentClass.Contains(TEXT("SeinEffect")) ||
			ParentClass.Contains(TEXT("SeinActor"));
		if (!bIsSeinTaggable) continue;

		const UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
		if (!BP || !BP->GeneratedClass) continue;
		const UObject* CDO = BP->GeneratedClass->GetDefaultObject();
		if (!CDO) continue;

		// Read whichever tag field matches the class.
		if (const USeinAbility* Ability = Cast<USeinAbility>(CDO))
		{
			if (Ability->AbilityTag == Tag)
			{
				return Asset.PackageName.ToString();
			}
		}
		else if (const USeinEffect* Effect = Cast<USeinEffect>(CDO))
		{
			if (Effect->EffectTag == Tag)
			{
				return Asset.PackageName.ToString();
			}
		}
		else if (const ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
		{
			// Check the entity bridge's FSeinIdentityComponent::IdentityTag.
			// The bridge subobject is `EntityBridge` on ASeinActor; the
			// IdentityComponent lives in its ComponentData array.
			TArray<USeinEntityComponent*> Bridges;
			SeinActor->GetComponents<USeinEntityComponent>(Bridges);
			for (USeinEntityComponent* Bridge : Bridges)
			{
				if (!Bridge) continue;
				for (const FInstancedStruct& Entry : Bridge->ComponentData)
				{
					if (!Entry.IsValid()) continue;
					if (Entry.GetScriptStruct() != FSeinIdentityComponent::StaticStruct()) continue;
					const FSeinIdentityComponent& Identity = Entry.Get<FSeinIdentityComponent>();
					if (Identity.IdentityTag == Tag)
					{
						return Asset.PackageName.ToString();
					}
				}
			}
		}
	}

	return FString();
}

bool SeinAutoTag::RegenerateAssetTag(UBlueprint* OwningBP, bool bForceOverManual)
{
	if (!OwningBP || !OwningBP->GeneratedClass) return false;
	const USeinARTSCoreSettings* Settings = GetDefault<USeinARTSCoreSettings>();
	if (!Settings || !Settings->bEnableAutoTagGeneration) return false;

	UObject* CDO = OwningBP->GeneratedClass->GetDefaultObject();
	if (!CDO) return false;

	const FName AssetName = OwningBP->GetFName();
	const FGameplayTag NewTag = DeriveTagFromAssetName(AssetName, Settings);
	if (!NewTag.IsValid()) return false;

	// Lambda shared across the three target shapes. Returns true on actual
	// change.
	auto TryApply = [&](FGameplayTag& OutTag, bool& OutAutoFlag) -> bool
	{
		if (!bForceOverManual && !OutAutoFlag) return false;  // designer owns it
		if (OutTag == NewTag && OutAutoFlag) return false;     // already correct

		const FString Collider = FindCollidingAssetPath(NewTag, OwningBP->GetOutermost()->GetName());
		if (!Collider.IsEmpty())
		{
			UE_LOG(LogSeinAutoTagGen, Warning,
				TEXT("Regenerate '%s' skipped — new tag '%s' collides with '%s'."),
				*OwningBP->GetName(), *NewTag.ToString(), *Collider);
			return false;
		}

		OutTag = NewTag;
		OutAutoFlag = true;
		RegisterTagIfNeeded(NewTag);
		return true;
	};

	bool bChanged = false;
	if (USeinAbility* Ability = Cast<USeinAbility>(CDO))
	{
		bChanged = TryApply(Ability->AbilityTag, Ability->bAutoGeneratedTag);
	}
	else if (USeinEffect* Effect = Cast<USeinEffect>(CDO))
	{
		bChanged = TryApply(Effect->EffectTag, Effect->bAutoGeneratedTag);
	}
	else if (ASeinActor* SeinActor = Cast<ASeinActor>(CDO))
	{
		// Identity components are designer-authored. We update existing
		// FSeinIdentityComponent entries but never synthesize one — a BP
		// without an identity component just doesn't participate in the
		// tagging system (it's still a valid Sein entity, e.g. a generic
		// projectile or environment prop).
		TArray<USeinEntityComponent*> Bridges;
		SeinActor->GetComponents<USeinEntityComponent>(Bridges);
		for (USeinEntityComponent* Bridge : Bridges)
		{
			if (!Bridge) continue;
			for (FInstancedStruct& Entry : Bridge->ComponentData)
			{
				if (!Entry.IsValid()) continue;
				if (Entry.GetScriptStruct() != FSeinIdentityComponent::StaticStruct()) continue;
				FSeinIdentityComponent& Identity = Entry.GetMutable<FSeinIdentityComponent>();
				if (TryApply(Identity.IdentityTag, Identity.bAutoGeneratedTag))
				{
					bChanged = true;
				}
			}
		}
	}

	if (bChanged)
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(OwningBP);
	}
	return bChanged;
}

int32 SeinAutoTag::RegenerateAllAssetTags(bool bForceOverManual)
{
	FAssetRegistryModule& AssetRegistryModule =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();

	TArray<FAssetData> Candidates;
	FARFilter Filter;
	Filter.bRecursiveClasses = true;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	AssetRegistry.GetAssets(Filter, Candidates);

	// Batch tag-tree refresh. AddNewGameplayTagToINI inside Derive triggers
	// an EditorRefreshGameplayTagTree per call (destroy + reload + reconstruct
	// the full tag tree from all sources). For a sweep over N assets that's
	// O(N) refreshes — each linear in total tag count. Suspending the refresh
	// collapses the whole sweep into one final refresh at Resume time.
	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();
	const FGuid SuspendToken = FGuid::NewGuid();
	Manager.SuspendEditorRefreshGameplayTagTree(SuspendToken);

	int32 NumChanged = 0;
	int32 NumScanned = 0;
	int32 NumTaggableCandidates = 0;
	for (const FAssetData& Asset : Candidates)
	{
		++NumScanned;
		const FString ParentClass = Asset.GetTagValueRef<FString>(FBlueprintTags::ParentClassPath);
		if (ParentClass.IsEmpty()) continue;
		const bool bIsSeinTaggable =
			ParentClass.Contains(TEXT("SeinAbility")) ||
			ParentClass.Contains(TEXT("SeinEffect")) ||
			ParentClass.Contains(TEXT("SeinActor"));
		if (!bIsSeinTaggable) continue;
		++NumTaggableCandidates;

		UBlueprint* BP = Cast<UBlueprint>(Asset.GetAsset());
		if (!BP) continue;
		if (RegenerateAssetTag(BP, bForceOverManual))
		{
			++NumChanged;
		}
	}

	Manager.ResumeEditorRefreshGameplayTagTree(SuspendToken);

	UE_LOG(LogSeinAutoTagGen, Log,
		TEXT("RegenerateAllAssetTags (force=%d): scanned %d BP(s), %d Sein-taggable, %d updated."),
		bForceOverManual ? 1 : 0, NumScanned, NumTaggableCandidates, NumChanged);
	return NumChanged;
}
