#pragma once

#include "NativeGameplayTags.h"

namespace SAFInitTags {
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Complete);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_FrontArmour);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_SideArmour);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_RearArmour);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Health);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_MaxHealth);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Shields);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_MaxShields);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Morale);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_MaxMorale);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Durability);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Defense);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Accuracy);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Evasion);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_WeaponHandling);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_WeaponSkill);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_CritChance);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_CritMultiplier);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Luck);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_MoveSpeed);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_SprintModifier);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Speed);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Agility);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_FormationSpacing);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_BuildTime);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_BuildSpeed);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost1);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost2);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost3);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost4);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost5);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost6);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost7);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost8);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost9);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost10);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost11);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_Cost12);

  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_FieldOfView);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_DefenseRange);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_ChaseRange);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_AbilityRadius);
  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Init_EffectRadius);
}
