/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file         AutoTagFeedbackTests.cpp
 * @author       RJ Macklem
 * @created      22 Aug 2026
 * @latest       22 Aug 2026
 * @brief        Qualifies actionable auto-tag regeneration outcomes.
 *
 * @disclaimer   This code was generated in whole or in part with the assistance
 *               of an AI language model.
 */

#include "CQTest.h"

#include "Abilities/SeinAbility.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Data/SeinTagPrefixMapping.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/PackageName.h"
#include "Settings/PluginSettings.h"
#include "Tags/SeinARTSGameplayTags.h"
#include "UObject/Package.h"
#include "Util/SeinAutoTagGenerator.h"

namespace UE::SeinARTSTests::AutoTagFeedback
{
	struct FScopedAutoTagFeedbackSettings
	{
		FScopedAutoTagFeedbackSettings()
			: Settings(GetMutableDefault<USeinARTSCoreSettings>())
			, bSavedEnabled(Settings->bEnableAutoTagGeneration)
			, SavedTagPrefix(Settings->TagPrefix)
			, SavedMappings(Settings->PrefixCategoryMappings)
			, bSavedLayering(Settings->bAllowTagLayering)
		{
			Settings->bEnableAutoTagGeneration = true;
			Settings->TagPrefix = TEXT("SeinARTS.Command.Context");
			Settings->PrefixCategoryMappings = {
				FSeinTagPrefixMapping(TEXT("SA"), TEXT("Target")),
			};
			Settings->bAllowTagLayering = true;
		}

		~FScopedAutoTagFeedbackSettings()
		{
			Settings->bEnableAutoTagGeneration = bSavedEnabled;
			Settings->TagPrefix = SavedTagPrefix;
			Settings->PrefixCategoryMappings = SavedMappings;
			Settings->bAllowTagLayering = bSavedLayering;
		}

		USeinARTSCoreSettings* Settings = nullptr;
		bool bSavedEnabled = false;
		FString SavedTagPrefix;
		TArray<FSeinTagPrefixMapping> SavedMappings;
		bool bSavedLayering = false;
	};

	struct FScopedAutoTagFeedbackAssets
	{
		~FScopedAutoTagFeedbackAssets()
		{
			for (UBlueprint* Blueprint : Blueprints)
			{
				if (!Blueprint)
				{
					continue;
				}
				FAssetRegistryModule::AssetDeleted(Blueprint);
				Blueprint->ClearFlags(RF_Public | RF_Standalone);
				Blueprint->MarkAsGarbage();
			}
			for (UPackage* Package : Packages)
			{
				if (Package)
				{
					Package->SetDirtyFlag(false);
					Package->MarkAsGarbage();
				}
			}
		}

		UBlueprint* CreateAbility(const FString& PackageName)
		{
			UPackage* Package = CreatePackage(*PackageName);
			if (!Package)
			{
				return nullptr;
			}
			Packages.Add(Package);

			const FName AssetName(*FPackageName::GetLongPackageAssetName(
				PackageName));
			UBlueprint* Blueprint = FKismetEditorUtilities::CreateBlueprint(
				USeinAbility::StaticClass(),
				Package,
				AssetName,
				BPTYPE_Normal,
				UBlueprint::StaticClass(),
				UBlueprintGeneratedClass::StaticClass(),
				NAME_None);
			if (!Blueprint || !Blueprint->GeneratedClass)
			{
				return nullptr;
			}

			Blueprints.Add(Blueprint);
			FAssetRegistryModule::AssetCreated(Blueprint);
			return Blueprint;
		}

		TArray<UBlueprint*> Blueprints;
		TArray<UPackage*> Packages;
	};

	USeinAbility* GetAutoTagFeedbackAbilityCDO(UBlueprint* Blueprint)
	{
		return Blueprint && Blueprint->GeneratedClass
			? Cast<USeinAbility>(
				Blueprint->GeneratedClass->GetDefaultObject())
			: nullptr;
	}
}

TEST(AutoTagRegenerationReportsActionableOutcomes,
	"SeinARTS.Editor.AutoTag")
{
	using namespace UE::SeinARTSTests::AutoTagFeedback;

	FScopedAutoTagFeedbackSettings SettingsScope;
	FScopedAutoTagFeedbackAssets AssetsScope;
	const FString Suffix = FGuid::NewGuid().ToString(EGuidFormats::Digits);
	const FString SearchRoot = FString::Printf(
		TEXT("/Game/__SeinAutomation/AutoTag/%s"),
		*Suffix);
	const FString PrimaryPackage =
		SearchRoot / TEXT("Primary/SA_Ground");
	UBlueprint* Primary = AssetsScope.CreateAbility(PrimaryPackage);
	USeinAbility* PrimaryCDO = GetAutoTagFeedbackAbilityCDO(Primary);
	ASSERT_THAT(IsNotNull(Primary));
	ASSERT_THAT(IsNotNull(PrimaryCDO));
	ASSERT_THAT(IsTrue(
		SeinARTSTags::Command_Context_Target_Ground.GetTag().IsValid()));

	PrimaryCDO->AbilityTag = FGameplayTag();
	PrimaryCDO->bAutoGeneratedTag = false;
	const FSeinAutoTagRegenerationResult DesignerOwned =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/false,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		DesignerOwned.Outcome ==
			ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned));
	ASSERT_THAT(IsFalse(DesignerOwned.IsFailure()));

	const FSeinAutoTagRegenerationResult Updated =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		Updated.Outcome == ESeinAutoTagRegenerationOutcome::Updated));
	ASSERT_THAT(IsTrue(Updated.WasUpdated()));
	ASSERT_THAT(IsFalse(Updated.IsFailure()));
	ASSERT_THAT(IsTrue(
		PrimaryCDO->AbilityTag
			== SeinARTSTags::Command_Context_Target_Ground.GetTag()));
	ASSERT_THAT(IsTrue(PrimaryCDO->bAutoGeneratedTag));

	const FSeinAutoTagRegenerationResult AlreadyCurrent =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		AlreadyCurrent.Outcome ==
			ESeinAutoTagRegenerationOutcome::AlreadyCurrent));
	ASSERT_THAT(IsFalse(AlreadyCurrent.WasUpdated()));
	ASSERT_THAT(IsFalse(AlreadyCurrent.IsFailure()));

	const FString UnmappedPackage =
		SearchRoot / TEXT("Unmapped/Unknown_Ground");
	UBlueprint* Unmapped = AssetsScope.CreateAbility(UnmappedPackage);
	USeinAbility* UnmappedCDO = GetAutoTagFeedbackAbilityCDO(Unmapped);
	ASSERT_THAT(IsNotNull(Unmapped));
	ASSERT_THAT(IsNotNull(UnmappedCDO));
	UnmappedCDO->AbilityTag = FGameplayTag();
	UnmappedCDO->bAutoGeneratedTag = true;
	const FSeinAutoTagRegenerationResult DerivationFailed =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Unmapped,
			/*bForceOverManual=*/false,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		DerivationFailed.Outcome ==
			ESeinAutoTagRegenerationOutcome::TagDerivationFailed));
	ASSERT_THAT(IsTrue(DerivationFailed.IsFailure()));
	ASSERT_THAT(IsFalse(UnmappedCDO->AbilityTag.IsValid()));

	const FString CandidatePackage =
		SearchRoot / TEXT("Candidate/SA_Ground");
	UBlueprint* Candidate = AssetsScope.CreateAbility(CandidatePackage);
	USeinAbility* CandidateCDO = GetAutoTagFeedbackAbilityCDO(Candidate);
	ASSERT_THAT(IsNotNull(Candidate));
	ASSERT_THAT(IsNotNull(CandidateCDO));
	CandidateCDO->AbilityTag = FGameplayTag();
	CandidateCDO->bAutoGeneratedTag = false;

	const FSeinAutoTagRegenerationResult Collision =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Candidate,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		Collision.Outcome ==
			ESeinAutoTagRegenerationOutcome::Collision));
	ASSERT_THAT(IsTrue(Collision.IsFailure()));
	ASSERT_THAT(IsFalse(Collision.WasUpdated()));
	ASSERT_THAT(IsTrue(Collision.DerivedTag
		== SeinARTSTags::Command_Context_Target_Ground.GetTag()));
	ASSERT_THAT(AreEqual(PrimaryPackage, Collision.CollidingAssetPath));
	ASSERT_THAT(IsFalse(CandidateCDO->AbilityTag.IsValid()));
	ASSERT_THAT(IsFalse(CandidateCDO->bAutoGeneratedTag));
	const FString CollisionMessage =
		Collision.ToUserMessage(Candidate).ToString();
	ASSERT_THAT(IsTrue(CollisionMessage.Contains(PrimaryPackage)));
	ASSERT_THAT(IsTrue(CollisionMessage.Contains(
		SeinARTSTags::Command_Context_Target_Ground.GetTag().ToString())));
	ASSERT_THAT(IsTrue(CollisionMessage.Contains(TEXT("Reset to Auto"))));
}
