/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 *
 * @file         AutoTagFeedbackTests.cpp
 * @author       RJ Macklem
 * @created      22 Aug 2026
 * @latest       22 Aug 2026
 * @brief        Qualifies actionable auto-tag regeneration outcomes.
 *
 * @disclaimer   This code was generated in whole or in part with the assistance
 *               of an AI language model.
 */

#include "CQTest.h"

#include "Abilities/SeinAbility.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Data/SeinTagPrefixMapping.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/PackageName.h"
#include "Settings/PluginSettings.h"
#include "Tags/SeinARTSGameplayTags.h"
#include "UObject/Package.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Actor/SeinActor.h"
#include "Actor/SeinEntityBridgeComponent.h"
#include "Authoring/SeinEntityComponent.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/SCS_Node.h"
#include "GameplayTagsManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "UObject/UnrealType.h"

namespace UE::SeinARTSTests::AutoTagFeedback
{
	struct FScopedAutoTagFeedbackSettings
	{
		FScopedAutoTagFeedbackSettings()
			: Settings(GetMutableDefault<USeinARTSCoreSettings>())
			, bSavedEnabled(Settings->bEnableAutoTagGeneration)
			, SavedTagPrefix(Settings->TagPrefix)
			, SavedMappings(Settings->PrefixCategoryMappings)
			, bSavedLayering(Settings->bAllowTagLayering)
		{
			Settings->bEnableAutoTagGeneration = true;
			Settings->TagPrefix = TEXT("SeinARTS.Command.Context");
			Settings->PrefixCategoryMappings = {
				FSeinTagPrefixMapping(TEXT("SA"), TEXT("Target")),
			};
			Settings->bAllowTagLayering = true;
		}

		~FScopedAutoTagFeedbackSettings()
		{
			Settings->bEnableAutoTagGeneration = bSavedEnabled;
			Settings->TagPrefix = SavedTagPrefix;
			Settings->PrefixCategoryMappings = SavedMappings;
			Settings->bAllowTagLayering = bSavedLayering;
		}

		USeinARTSCoreSettings* Settings = nullptr;
		bool bSavedEnabled = false;
		FString SavedTagPrefix;
		TArray<FSeinTagPrefixMapping> SavedMappings;
		bool bSavedLayering = false;
	};

	struct FScopedAutoTagFeedbackAssets
	{
		~FScopedAutoTagFeedbackAssets()
		{
			for (UBlueprint* Blueprint : Blueprints)
			{
				if (!Blueprint)
				{
					continue;
				}
				FAssetRegistryModule::AssetDeleted(Blueprint);
				Blueprint->ClearFlags(RF_Public | RF_Standalone);
				Blueprint->MarkAsGarbage();
			}
			for (UPackage* Package : Packages)
			{
				if (Package)
				{
					Package->SetDirtyFlag(false);
					Package->MarkAsGarbage();
				}
			}
		}

		UBlueprint* CreateAbility(const FString& PackageName, UClass* Parent = USeinAbility::StaticClass())
		{
			UPackage* Package = CreatePackage(*PackageName);
			if (!Package)
			{
				return nullptr;
			}
			Packages.Add(Package);

			const FName AssetName(*FPackageName::GetLongPackageAssetName(
				PackageName));
			UBlueprint* Blueprint = FKismetEditorUtilities::CreateBlueprint(
                Parent,
				Package,
				AssetName,
				BPTYPE_Normal,
				UBlueprint::StaticClass(),
				UBlueprintGeneratedClass::StaticClass(),
				NAME_None);
			if (!Blueprint || !Blueprint->GeneratedClass)
			{
				return nullptr;
			}

			Blueprints.Add(Blueprint);
			FAssetRegistryModule::AssetCreated(Blueprint);
			return Blueprint;
		}

		TArray<UBlueprint*> Blueprints;
		TArray<UPackage*> Packages;
	};

	USeinAbility* GetAutoTagFeedbackAbilityCDO(UBlueprint* Blueprint)
	{
		return Blueprint && Blueprint->GeneratedClass
			? Cast<USeinAbility>(
				Blueprint->GeneratedClass->GetDefaultObject())
			: nullptr;
	}
}

TEST(AutoTagRegenerationReportsActionableOutcomes,
	"SeinARTS.Editor.AutoTag")
{
	using namespace UE::SeinARTSTests::AutoTagFeedback;

	FScopedAutoTagFeedbackSettings SettingsScope;
	FScopedAutoTagFeedbackAssets AssetsScope;
	const FString Suffix = FGuid::NewGuid().ToString(EGuidFormats::Digits);
	const FString SearchRoot = FString::Printf(
		TEXT("/Game/__SeinAutomation/AutoTag/%s"),
		*Suffix);
	const FString PrimaryPackage =
		SearchRoot / TEXT("Primary/SA_Ground");
	UBlueprint* Primary = AssetsScope.CreateAbility(PrimaryPackage);
	USeinAbility* PrimaryCDO = GetAutoTagFeedbackAbilityCDO(Primary);
	ASSERT_THAT(IsNotNull(Primary));
	ASSERT_THAT(IsNotNull(PrimaryCDO));
	ASSERT_THAT(IsTrue(
		SeinARTSTags::Command_Context_Target_Ground.GetTag().IsValid()));

	PrimaryCDO->AbilityTag = FGameplayTag();
	PrimaryCDO->bAutoGeneratedTag = false;
	const FSeinAutoTagRegenerationResult DesignerOwned =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/false,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		DesignerOwned.Outcome ==
			ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned));
	ASSERT_THAT(IsFalse(DesignerOwned.IsFailure()));

	const FSeinAutoTagRegenerationResult Updated =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		Updated.Outcome == ESeinAutoTagRegenerationOutcome::Updated));
	ASSERT_THAT(IsTrue(Updated.WasUpdated()));
	ASSERT_THAT(IsFalse(Updated.IsFailure()));
	ASSERT_THAT(IsTrue(
		PrimaryCDO->AbilityTag
			== SeinARTSTags::Command_Context_Target_Ground.GetTag()));
	ASSERT_THAT(IsTrue(PrimaryCDO->bAutoGeneratedTag));

	const FSeinAutoTagRegenerationResult AlreadyCurrent =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Primary,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		AlreadyCurrent.Outcome ==
			ESeinAutoTagRegenerationOutcome::AlreadyCurrent));
	ASSERT_THAT(IsFalse(AlreadyCurrent.WasUpdated()));
	ASSERT_THAT(IsFalse(AlreadyCurrent.IsFailure()));

	const FString UnmappedPackage =
		SearchRoot / TEXT("Unmapped/Unknown_Ground");
	UBlueprint* Unmapped = AssetsScope.CreateAbility(UnmappedPackage);
	USeinAbility* UnmappedCDO = GetAutoTagFeedbackAbilityCDO(Unmapped);
	ASSERT_THAT(IsNotNull(Unmapped));
	ASSERT_THAT(IsNotNull(UnmappedCDO));
	UnmappedCDO->AbilityTag = FGameplayTag();
	UnmappedCDO->bAutoGeneratedTag = true;
	const FSeinAutoTagRegenerationResult DerivationFailed =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Unmapped,
			/*bForceOverManual=*/false,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		DerivationFailed.Outcome ==
			ESeinAutoTagRegenerationOutcome::TagDerivationFailed));
	ASSERT_THAT(IsTrue(DerivationFailed.IsFailure()));
	ASSERT_THAT(IsFalse(UnmappedCDO->AbilityTag.IsValid()));

	const FString CandidatePackage =
		SearchRoot / TEXT("Candidate/SA_Ground");
	UBlueprint* Candidate = AssetsScope.CreateAbility(CandidatePackage);
	USeinAbility* CandidateCDO = GetAutoTagFeedbackAbilityCDO(Candidate);
	ASSERT_THAT(IsNotNull(Candidate));
	ASSERT_THAT(IsNotNull(CandidateCDO));
	CandidateCDO->AbilityTag = FGameplayTag();
	CandidateCDO->bAutoGeneratedTag = false;

	const FSeinAutoTagRegenerationResult Collision =
		SeinAutoTag::RegenerateAssetTagDetailedForAutomation(
			Candidate,
			/*bForceOverManual=*/true,
			SearchRoot);
	ASSERT_THAT(IsTrue(
		Collision.Outcome ==
			ESeinAutoTagRegenerationOutcome::Collision));
	ASSERT_THAT(IsTrue(Collision.IsFailure()));
	ASSERT_THAT(IsFalse(Collision.WasUpdated()));
	ASSERT_THAT(IsTrue(Collision.DerivedTag
		== SeinARTSTags::Command_Context_Target_Ground.GetTag()));
	ASSERT_THAT(AreEqual(PrimaryPackage, Collision.CollidingAssetPath));
	ASSERT_THAT(IsFalse(CandidateCDO->AbilityTag.IsValid()));
	ASSERT_THAT(IsFalse(CandidateCDO->bAutoGeneratedTag));
	const FString CollisionMessage =
		Collision.ToUserMessage(Candidate).ToString();
	ASSERT_THAT(IsTrue(CollisionMessage.Contains(PrimaryPackage)));
	ASSERT_THAT(IsTrue(CollisionMessage.Contains(
		SeinARTSTags::Command_Context_Target_Ground.GetTag().ToString())));
	ASSERT_THAT(IsFalse(CollisionMessage.IsEmpty()));
}

TEST(TagProposalDoesNotPersistOrRegisterNames, "SeinARTS.Editor.AutoTag")
{
    using namespace UE::SeinARTSTests::AutoTagFeedback;
    FScopedAutoTagFeedbackSettings Scope;
    const FString Path = FPaths::ProjectConfigDir() / TEXT("Tags/SeinAutoGeneratedTags.ini");
    FString Before, After;
    FFileHelper::LoadFileToString(Before, *Path);
    const FName Asset(*FString::Printf(TEXT("SA_%s"), *FGuid::NewGuid().ToString(EGuidFormats::Digits)));
    const FName Proposed = SeinAutoTag::ProposeTagName(Asset, Scope.Settings);
    ASSERT_THAT(IsFalse(Proposed.IsNone()));
    ASSERT_THAT(IsFalse(SeinAutoTag::DeriveTagFromAssetName(Asset, Scope.Settings).IsValid()));
    ASSERT_THAT(IsFalse(UGameplayTagsManager::Get().RequestGameplayTag(Proposed, false).IsValid()));
    FFileHelper::LoadFileToString(After, *Path);
    ASSERT_THAT(AreEqual(Before, After));
}

TEST(ManuallyOwnedAssetRenamePreservesIdentity, "SeinARTS.Editor.AutoTag")
{
    using namespace UE::SeinARTSTests::AutoTagFeedback;
    FScopedAutoTagFeedbackSettings Settings;
    FScopedAutoTagFeedbackAssets Assets;
    const FString Root = TEXT("/Game/__SeinAutomation/AutoTag/") + FGuid::NewGuid().ToString(EGuidFormats::Digits);
    UBlueprint* BP = Assets.CreateAbility(Root / TEXT("SA_Ground"));
    auto* CDO = GetAutoTagFeedbackAbilityCDO(BP);
    ASSERT_THAT(IsNotNull(CDO));
    const FGameplayTag Original = SeinARTSTags::Command_Context_Target_Ground;
    CDO->AbilityTag = Original;
    CDO->bAutoGeneratedTag = false;
    const FString OldPath = BP->GetPathName();
    ASSERT_THAT(IsTrue(BP->Rename(TEXT("SA_Friendly"), nullptr, REN_DontCreateRedirectors | REN_NonTransactional)));
    FAssetRegistryModule::AssetRenamed(BP, OldPath);
    ASSERT_THAT(IsTrue(CDO->AbilityTag == Original));
    const auto Retained = SeinAutoTag::RegenerateAssetTagDetailedForAutomation(BP, false, Root);
    ASSERT_THAT(IsTrue(Retained.Outcome == ESeinAutoTagRegenerationOutcome::SkippedDesignerOwned));
    const auto Explicit = SeinAutoTag::RegenerateAssetTagDetailedForAutomation(BP, true, Root);
    ASSERT_THAT(IsTrue(Explicit.Outcome == ESeinAutoTagRegenerationOutcome::MigrationRequired));
    ASSERT_THAT(IsTrue(CDO->AbilityTag == Original));
}

TEST(DerivedBlueprintIdentityCollisionsAreDetectedEvenWhenCurrent, "SeinARTS.Editor.AutoTag")
{
    using namespace UE::SeinARTSTests::AutoTagFeedback;
    FScopedAutoTagFeedbackSettings Settings;
    FScopedAutoTagFeedbackAssets Assets;
    const FString Root = TEXT("/Game/__SeinAutomation/AutoTag/") + FGuid::NewGuid().ToString(EGuidFormats::Digits);
    UBlueprint* Parent = Assets.CreateAbility(Root / TEXT("Base/SA_Ground"));
    UBlueprint* Child = Assets.CreateAbility(Root / TEXT("Child/SA_Friendly"), Parent->GeneratedClass);
    auto* ParentCDO = GetAutoTagFeedbackAbilityCDO(Parent);
    auto* ChildCDO = GetAutoTagFeedbackAbilityCDO(Child);
    ASSERT_THAT(IsNotNull(ChildCDO));
    ParentCDO->AbilityTag = SeinARTSTags::Command_Context_Target_Ground;
    ChildCDO->AbilityTag = ParentCDO->AbilityTag;
    ParentCDO->bAutoGeneratedTag = true;
    ChildCDO->bAutoGeneratedTag = true;
    const auto Result = SeinAutoTag::RegenerateAssetTagDetailedForAutomation(Parent, true, Root);
    ASSERT_THAT(IsTrue(Result.Outcome == ESeinAutoTagRegenerationOutcome::Collision));
    ASSERT_THAT(AreEqual(Child->GetOutermost()->GetName(), Result.CollidingAssetPath));
}

TEST(IdentityGenerationWritesAuthoringComponentAndSurvivesRebake, "SeinARTS.Editor.AutoTag")
{
    using namespace UE::SeinARTSTests::AutoTagFeedback;
    FScopedAutoTagFeedbackSettings Settings;
    FScopedAutoTagFeedbackAssets Assets;
    const FString Root = TEXT("/Game/__SeinAutomation/AutoTag/") + FGuid::NewGuid().ToString(EGuidFormats::Digits);
    UBlueprint* BP = Assets.CreateAbility(Root / TEXT("SA_Ground"), ASeinActor::StaticClass());
    USCS_Node* Node = BP->SimpleConstructionScript->CreateNode(USeinIdentityComponent::StaticClass(), TEXT("SeinIdentity"));
    BP->SimpleConstructionScript->AddNode(Node);
    FKismetEditorUtilities::CompileBlueprint(BP);
    const auto Result = SeinAutoTag::RegenerateAssetTagDetailedForAutomation(BP, true, Root);
    ASSERT_THAT(IsTrue(Result.WasUpdated()));
    auto* Component = Cast<USeinIdentityComponent>(Node->ComponentTemplate);
    ASSERT_THAT(IsNotNull(Component));
    ASSERT_THAT(IsTrue(Component->Identity.IdentityTag == Result.DerivedTag));
    ASSERT_THAT(IsTrue(Component->Identity.bAutoGeneratedTag));
    auto* Actor = Cast<ASeinActor>(BP->GeneratedClass->GetDefaultObject());
    auto* Bridge = Actor->FindComponentByClass<USeinEntityBridgeComponent>();
    ASSERT_THAT(IsNotNull(Bridge));
    Bridge->BakeAuthoredDataComponents(false);
    bool bFound = false;
    for (const auto& Entry : Bridge->ComponentData)
        if (const auto* Identity = Entry.GetPtr<FSeinIdentityPayload>())
        {
            bFound = true;
            ASSERT_THAT(IsTrue(Identity->IdentityTag == Result.DerivedTag));
        }
    ASSERT_THAT(IsTrue(bFound));
    Component->Identity.IdentityTag = SeinARTSTags::Command_Context_Target_Friendly;
    FPropertyChangedEvent Event(FSeinIdentityPayload::StaticStruct()->FindPropertyByName(
        GET_MEMBER_NAME_CHECKED(FSeinIdentityPayload, IdentityTag)));
    Component->PostEditChangeProperty(Event);
    ASSERT_THAT(IsFalse(Component->Identity.bAutoGeneratedTag));
}

TEST(NewChildIdentityOverridesInheritedComponentWithoutChangingParent, "SeinARTS.Editor.AutoTag")
{
	using namespace UE::SeinARTSTests::AutoTagFeedback;
	FScopedAutoTagFeedbackSettings Settings;
	FScopedAutoTagFeedbackAssets Assets;
	const FString Root = TEXT("/Game/__SeinAutomation/AutoTag/") + FGuid::NewGuid().ToString(EGuidFormats::Digits);
	UBlueprint* Parent = Assets.CreateAbility(Root / TEXT("Parent/Unmapped_Base"), ASeinActor::StaticClass());
	USCS_Node* Node = Parent->SimpleConstructionScript->CreateNode(USeinIdentityComponent::StaticClass(), TEXT("SeinIdentity"));
	Parent->SimpleConstructionScript->AddNode(Node);
	FKismetEditorUtilities::CompileBlueprint(Parent);
	auto* ParentComponent = CastChecked<USeinIdentityComponent>(Node->ComponentTemplate);
	ParentComponent->Identity.IdentityTag = SeinARTSTags::Command_Context_Target_Ground;
	ParentComponent->Identity.bAutoGeneratedTag = true;
	auto* ParentActor = CastChecked<ASeinActor>(Parent->GeneratedClass->GetDefaultObject());
	ParentActor->FindComponentByClass<USeinEntityBridgeComponent>()->NotifyAuthoringComponentEdited(*ParentComponent);
	// AssetCreated exercises the module's new-asset callback against an inherited SCS template.
	UBlueprint* Child = Assets.CreateAbility(Root / TEXT("Child/SA_Friendly"), Parent->GeneratedClass);
	ASSERT_THAT(IsNotNull(Child));
	FGameplayTag ChildTag, ParentTag;
	bool bChildGenerated = false, bParentGenerated = false;
	ASSERT_THAT(IsTrue(SeinAutoTag::ReadAssetIdentity(Child, ChildTag, bChildGenerated)));
	ASSERT_THAT(IsTrue(SeinAutoTag::ReadAssetIdentity(Parent, ParentTag, bParentGenerated)));
	ASSERT_THAT(IsTrue(ChildTag == SeinARTSTags::Command_Context_Target_Friendly.GetTag()));
	ASSERT_THAT(IsTrue(ParentTag == SeinARTSTags::Command_Context_Target_Ground.GetTag()));
	ASSERT_THAT(IsTrue(bChildGenerated));
	ASSERT_THAT(IsTrue(bParentGenerated));
	FKismetEditorUtilities::CompileBlueprint(Child);
	ASSERT_THAT(IsTrue(SeinAutoTag::ReadAssetIdentity(Child, ChildTag, bChildGenerated)));
	ASSERT_THAT(IsTrue(ChildTag == SeinARTSTags::Command_Context_Target_Friendly.GetTag()));
	ASSERT_THAT(IsTrue(ParentComponent->Identity.IdentityTag == ParentTag));
}
