/**
 * SeinARTS Framework - Copyright (c) 2026 Phenom Studios, Inc.
 * @file         TagMigrationTests.cpp
 * @author       RJ Macklem
 * @created      7 Sep 2026
 * @latest       7 Sep 2026
 * @brief        Exercises isolated tag sources, loaded references and conservative cleanup.
 * @disclaimer   Generated with assistance from an AI language model.
 */
#include "CQTest.h"
#include "Editor/SeinTagLifecycleTestTypes.h"
#include "Abilities/SeinAbility.h"
#include "Components/SeinIdentityPayload.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "GameplayTagsEditorModule.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsSettings.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/Paths.h"
#include "Misc/FileHelper.h"
#include "HAL/FileManager.h"
#include "UObject/Package.h"
#include "UObject/Linker.h"
#include "Util/SeinAutoTagGenerator.h"
#include "Util/SeinTagAudit.h"
#include "Settings/PluginSettings.h"
#include "Data/SeinTagPrefixMapping.h"
#include "AssetToolsModule.h"
#include "IAssetTools.h"
#include "Misc/PackageName.h"
#include "UObject/SavePackage.h"
#include "ScopedTransaction.h"
#include "Editor.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "EdGraphSchema_K2.h"
#include "PackageTools.h"
#include "Lib/SeinAbilityBPFL.h"

namespace
{
	struct FTagSourceFixture
	{
		FString Suffix = FGuid::NewGuid().ToString(EGuidFormats::Digits);
		FString Root = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir() / TEXT("TagLifecycleTests") / Suffix);
		FName SourceName{*(TEXT("SeinTagTest_") + Suffix + TEXT(".ini"))};
		FString TagRoot = TEXT("SeinTagTest") + Suffix;
		TArray<TWeakObjectPtr<UObject>> Assets;
		TArray<TWeakObjectPtr<UPackage>> Packages;
		TArray<FString> ExtraFiles;
		FString SavedMount;
		FString SavedDirectory;
		FTagSourceFixture()
		{
			IFileManager::Get().MakeDirectory(*Root, true);
			IGameplayTagsEditorModule::Get().AddNewGameplayTagSource(SourceName.ToString(), Root);
			UGameplayTagsManager::Get().AddTagIniSearchPath(Root);
		}
		~FTagSourceFixture()
		{
			SeinAutoTag::FinishPendingTagMigrations();
			for (const auto& Weak : Assets) if (UObject* Asset = Weak.Get())
			{
				Asset->SetFlags(RF_Transient);
				FAssetRegistryModule::AssetDeleted(Asset);
				Asset->ClearFlags(RF_Public | RF_Standalone);
				Asset->MarkAsGarbage();
			}
			for (const auto& Weak : Packages) if (UPackage* Package = Weak.Get()) { ResetLoaders(Package); Package->SetDirtyFlag(false); Package->MarkAsGarbage(); }
			UGameplayTagsManager::Get().RemoveTagIniSearchPath(Root);
			IFileManager::Get().Delete(*(Root / SourceName.ToString()));
			for (const auto& File : ExtraFiles) IFileManager::Get().Delete(*File);
			UGameplayTagsManager::Get().EditorRefreshGameplayTagTree();
			if (!SavedMount.IsEmpty()) FPackageName::UnRegisterMountPoint(SavedMount, SavedDirectory);
		}
		void EnableSavedAssets()
		{
			SavedMount = TEXT("/SeinTagLifecycle") + Suffix + TEXT("/");
			SavedDirectory = Root / TEXT("Assets/");
			IFileManager::Get().MakeDirectory(*SavedDirectory, true);
			FPackageName::RegisterMountPoint(SavedMount, SavedDirectory);
		}
		bool Save(UObject* Asset)
		{
			const FString File = FPackageName::LongPackageNameToFilename(Asset->GetOutermost()->GetName(), FPackageName::GetAssetPackageExtension());
			ExtraFiles.AddUnique(File);
			FSavePackageArgs Args;
			Args.TopLevelFlags = RF_Public | RF_Standalone;
			return UPackage::SavePackage(Asset->GetOutermost(), Asset, *File, Args);
		}
		FGameplayTag Add(const FString& SuffixName)
		{
			const FString Name = TagRoot + TEXT(".") + SuffixName;
			IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(Name, TEXT("Auto-generated by SeinARTS."), SourceName);
			return UGameplayTagsManager::Get().RequestGameplayTag(FName(*Name), false);
		}
		UPackage* Package(const FString& Name)
		{
			auto* Result = CreatePackage(*((SavedMount.IsEmpty() ? TEXT("/Game/__SeinAutomation/TagLifecycle/") + Suffix + TEXT("/") : SavedMount) + Name));
			Packages.Add(Result);
			return Result;
		}
		UBlueprint* Ability(FGameplayTag Tag, const FString& Name = TEXT("SA_Original"))
		{
			auto* BP = FKismetEditorUtilities::CreateBlueprint(USeinAbility::StaticClass(), Package(Name), FName(*Name),
				BPTYPE_Normal, UBlueprint::StaticClass(), UBlueprintGeneratedClass::StaticClass(), NAME_None);
			Assets.Add(BP);
			// Fixture identity comes from the isolated source, not the production factory hook.
			BP->SetFlags(RF_Transient);
			FAssetRegistryModule::AssetCreated(BP);
			BP->ClearFlags(RF_Transient);
			auto* CDO = CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject());
			CDO->AbilityTag = Tag;
			CDO->bAutoGeneratedTag = true;
			return BP;
		}
		void MarkClean()
		{
			for (const auto& Weak : Packages) if (auto* P = Weak.Get()) P->SetDirtyFlag(false);
		}
	};
	struct FAssetNameTagSettings
	{
		USeinARTSCoreSettings* Settings = GetMutableDefault<USeinARTSCoreSettings>();
		bool Enabled = Settings->bEnableAutoTagGeneration;
		bool Layering = Settings->bAllowTagLayering;
		FString Prefix = Settings->TagPrefix;
		TArray<FSeinTagPrefixMapping> Mappings = Settings->PrefixCategoryMappings;
		explicit FAssetNameTagSettings(const FString& Root)
		{
			Settings->bEnableAutoTagGeneration = true;
			Settings->bAllowTagLayering = true;
			Settings->TagPrefix = Root;
			Settings->PrefixCategoryMappings = {FSeinTagPrefixMapping(TEXT("SA"), TEXT("Ability"))};
		}
		~FAssetNameTagSettings()
		{
			SeinAutoTag::FinishPendingTagMigrations();
			Settings->bEnableAutoTagGeneration = Enabled;
			Settings->bAllowTagLayering = Layering;
			Settings->TagPrefix = Prefix;
			Settings->PrefixCategoryMappings = Mappings;
		}
	};

}

TEST(ExplicitTagMigrationRepairsLoadedTablesQueriesMapsAndPayloads, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Old = Fixture.Add(TEXT("Original"));
	ASSERT_THAT(IsTrue(Old.IsValid()));
	auto* BP = Fixture.Ability(Old);
	auto* Table = NewObject<UDataTable>(Fixture.Package(TEXT("Table")), TEXT("Table"), RF_Public | RF_Standalone);
	Fixture.Assets.Add(Table);
	Table->RowStruct = FSeinTagLifecycleTestRow::StaticStruct();
	FSeinTagLifecycleTestRow Row;
	Row.Tag = Old;
	Row.Tags.AddTag(Old);
	Row.Map.Add(Old, 42);
	Row.Query = FGameplayTagQuery::MakeQuery_MatchTag(Old);
	Row.Payload.InitializeAs<FSeinIdentityPayload>();
	Row.Payload.GetMutable<FSeinIdentityPayload>().IdentityTag = Old;
	Table->AddRow(TEXT("Row"), Row);
	FAssetRegistryModule::AssetCreated(Table);
	Fixture.MarkClean();
	const FName NewName(*(Fixture.TagRoot + TEXT(".Renamed")));
	const auto Result = SeinAutoTag::RenameAssetTag(BP, NewName);
	ASSERT_THAT(IsTrue(Result.WasUpdated()));
	const auto* After = Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("TagMigrationTest"));
	ASSERT_THAT(IsNotNull(After));
	ASSERT_THAT(IsTrue(After->Tag == Result.DerivedTag));
	ASSERT_THAT(IsTrue(After->Tags.HasTagExact(Result.DerivedTag)));
	ASSERT_THAT(AreEqual(42, After->Map.FindRef(Result.DerivedTag)));
	ASSERT_THAT(IsTrue(After->Query.Matches(After->Tags)));
	ASSERT_THAT(IsTrue(After->Payload.Get<FSeinIdentityPayload>().IdentityTag == Result.DerivedTag));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Old.GetTagName(), false) == Result.DerivedTag));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == Result.DerivedTag));
	// Incoming redirects remain valid when an identity is explicitly renamed again.
	Fixture.MarkClean();
	const auto Again = SeinAutoTag::RenameAssetTag(BP, FName(*(Fixture.TagRoot + TEXT(".Final"))));
	ASSERT_THAT(IsTrue(Again.WasUpdated()));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Old.GetTagName(), false) == Again.DerivedTag));
}

TEST(GeneratedTagAuditRetainsDirtyContentAndReferencedImplicitParents, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Leaf = Fixture.Add(TEXT("Category.Leaf"));
	ASSERT_THAT(IsTrue(Leaf.IsValid()));
	const FString Config = FPaths::ProjectConfigDir() / (TEXT("SeinTagAuditTest_") + Fixture.Suffix + TEXT(".ini"));
	Fixture.ExtraFiles.Add(Config);
	FFileHelper::SaveStringToFile(TEXT("[TagTest]\nParent=") + Fixture.TagRoot + TEXT(".Category\n"), *Config);
	auto Rows = SeinTagAudit::InspectForAutomation(Fixture.SourceName);
	const auto* Found = Rows.FindByPredicate([Leaf](const auto& Row) { return Row.Tag == Leaf.GetTagName(); });
	ASSERT_THAT(IsNotNull(Found));
	ASSERT_THAT(IsFalse(Found->bCanDelete));
	IFileManager::Get().Delete(*Config);
	Rows = SeinTagAudit::InspectForAutomation(Fixture.SourceName);
	Found = Rows.FindByPredicate([Leaf](const auto& Row) { return Row.Tag == Leaf.GetTagName(); });
	ASSERT_THAT(IsNotNull(Found));
	ASSERT_THAT(IsTrue(Found->bCanDelete));
	UPackage* Dirty = Fixture.Package(TEXT("Dirty"));
	Dirty->SetDirtyFlag(true);
	Rows = SeinTagAudit::InspectForAutomation(Fixture.SourceName);
	Found = Rows.FindByPredicate([Leaf](const auto& Row) { return Row.Tag == Leaf.GetTagName(); });
	ASSERT_THAT(IsNotNull(Found));
	ASSERT_THAT(IsFalse(Found->bCanDelete));
	ASSERT_THAT(IsTrue(Found->Reason.Contains(TEXT("unsaved"))));
}

TEST(GeneratedTagCleanupDeletesUnusedLeafAndRetainsOwnedIdentity, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Unused = Fixture.Add(TEXT("Unused"));
	const auto Owned = Fixture.Add(TEXT("Owned"));
	ASSERT_THAT(IsTrue(Unused.IsValid()));
	ASSERT_THAT(IsTrue(Owned.IsValid()));
	Fixture.Ability(Owned);
	Fixture.MarkClean();
	const auto Rows = SeinTagAudit::InspectForAutomation(Fixture.SourceName);
	const auto* Eligible = Rows.FindByPredicate([Unused](const auto& Row) { return Row.Tag == Unused.GetTagName(); });
	ASSERT_THAT(IsNotNull(Eligible));
	ASSERT_THAT(IsTrue(Eligible->bCanDelete));
	const FString Receipt = SeinTagAudit::CleanupForAutomation(Fixture.SourceName, {Unused.GetTagName(), Owned.GetTagName()});
	ASSERT_THAT(IsTrue(Receipt.Contains(Unused.ToString() + TEXT(": removed"))));
	ASSERT_THAT(IsFalse(UGameplayTagsManager::Get().RequestGameplayTag(Unused.GetTagName(), false).IsValid()));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Owned.GetTagName(), false).IsValid()));
	FString Disk;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Disk, *(Fixture.Root / Fixture.SourceName.ToString()))));
	ASSERT_THAT(IsFalse(Disk.Contains(TEXT("Tag=\"") + Unused.ToString() + TEXT("\""))));
	ASSERT_THAT(IsTrue(Disk.Contains(TEXT("Tag=\"") + Owned.ToString() + TEXT("\""))));
}

TEST(ExplicitTagMigrationRejectsCrossSourceIncomingAliasBeforeWriting, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Identity, Aliases;
	const auto Old = Identity.Add(TEXT("Original"));
	auto* BP = Identity.Ability(Old);
	Identity.MarkClean();
	const auto* AliasSource = UGameplayTagsManager::Get().FindTagSource(Aliases.SourceName);
	ASSERT_THAT(IsNotNull(AliasSource));
	FGameplayTagRedirect Redirect;
	Redirect.OldTagName = FName(*(Aliases.TagRoot + TEXT(".Previous")));
	Redirect.NewTagName = Old.GetTagName();
	AliasSource->SourceTagList->GameplayTagRedirects.Add(Redirect);
	ASSERT_THAT(IsTrue(AliasSource->SourceTagList->TryUpdateDefaultConfigFile(AliasSource->SourceTagList->ConfigFileName)));
	UGameplayTagsManager::Get().EditorRefreshGameplayTagTree();
	FString Before, After;
	const FString IdentityPath = Identity.Root / Identity.SourceName.ToString();
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Before, *IdentityPath)));
	const auto Result = SeinAutoTag::RenameAssetTag(BP, FName(*(Identity.TagRoot + TEXT(".Renamed"))));
	ASSERT_THAT(IsFalse(Result.WasUpdated()));
	ASSERT_THAT(IsTrue(Result.Detail.ToString().Contains(TEXT("another tag source"))));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *IdentityPath)));
	ASSERT_THAT(AreEqual(Before, After));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == Old));
}

TEST(IdentityRenameMovesFullHierarchyIncludingImplicitParentsAndChildOwners, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Root = Fixture.Add(TEXT("Infantry"));
	const auto Officer = Fixture.Add(TEXT("Infantry.Officer"));
	const auto Radio = Fixture.Add(TEXT("Infantry.Support.Radio"));
	const auto Outside = Fixture.Add(TEXT("Infantryman"));
	const auto Implicit = UGameplayTagsManager::Get().RequestGameplayTag(FName(*(Fixture.TagRoot + TEXT(".Infantry.Support"))));
	auto* BP = Fixture.Ability(Root);
	auto* ChildBP = Fixture.Ability(Officer, TEXT("SA_Officer"));
	auto* Table = NewObject<UDataTable>(Fixture.Package(TEXT("Table")), TEXT("Table"), RF_Public | RF_Standalone);
	Fixture.Assets.Add(Table);
	Table->RowStruct = FSeinTagLifecycleTestRow::StaticStruct();
	FSeinTagLifecycleTestRow Row;
	Row.Tag = Implicit;
	Row.Tags.AddTag(Radio);
	Row.Query = FGameplayTagQuery::MakeQuery_MatchTag(Root);
	Row.Map.Add(Root, 1);
	Row.Map.Add(Officer, 2);
	Row.Map.Add(Implicit, 3);
	Row.Payload.InitializeAs<FSeinIdentityPayload>();
	Row.Payload.GetMutable<FSeinIdentityPayload>().IdentityTag = Officer;
	Table->AddRow(TEXT("Row"), Row);
	FAssetRegistryModule::AssetCreated(Table);
	Fixture.MarkClean();
	const FString Destination = Fixture.TagRoot + TEXT(".Soldier");
	const auto Result = SeinAutoTag::RenameAssetTag(BP, FName(*Destination));
	ASSERT_THAT(IsTrue(Result.WasUpdated()));
	auto& Manager = UGameplayTagsManager::Get();
	const auto NewOfficer = Manager.RequestGameplayTag(FName(*(Destination + TEXT(".Officer"))));
	const auto NewSupport = Manager.RequestGameplayTag(FName(*(Destination + TEXT(".Support"))));
	const auto NewRadio = Manager.RequestGameplayTag(FName(*(Destination + TEXT(".Support.Radio"))));
	ASSERT_THAT(IsTrue(NewRadio.MatchesTag(NewSupport)));
	ASSERT_THAT(IsTrue(NewRadio.MatchesTag(Result.DerivedTag)));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(ChildBP->GeneratedClass->GetDefaultObject())->AbilityTag == NewOfficer));
	const auto* After = Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("HierarchyMigrationTest"));
	ASSERT_THAT(IsNotNull(After));
	ASSERT_THAT(IsTrue(After->Tag == NewSupport));
	ASSERT_THAT(IsTrue(After->Tags.HasTagExact(NewRadio)));
	ASSERT_THAT(IsTrue(After->Query.Matches(After->Tags)));
	ASSERT_THAT(AreEqual(1, After->Map.FindRef(Result.DerivedTag)));
	ASSERT_THAT(AreEqual(2, After->Map.FindRef(NewOfficer)));
	ASSERT_THAT(AreEqual(3, After->Map.FindRef(NewSupport)));
	ASSERT_THAT(IsTrue(After->Payload.Get<FSeinIdentityPayload>().IdentityTag == NewOfficer));
	ASSERT_THAT(IsFalse(Manager.FindTagNode(NewSupport)->IsExplicitTag()));
	ASSERT_THAT(IsTrue(Manager.RequestGameplayTag(Outside.GetTagName()) == Outside));
	// A second rename must keep every original root/child/intermediate alias resolving directly.
	Fixture.MarkClean();
	const FString FinalRoot = Fixture.TagRoot + TEXT(".Veteran");
	const auto Again = SeinAutoTag::RenameAssetTag(BP, FName(*FinalRoot));
	ASSERT_THAT(IsTrue(Again.WasUpdated()));
	Manager.EditorRefreshGameplayTagTree();
	for (const auto& Pair : TArray<TPair<FGameplayTag, FString>>{
		{Root, TEXT("")}, {Officer, TEXT(".Officer")}, {Implicit, TEXT(".Support")}, {Radio, TEXT(".Support.Radio")}})
	{
		const FName Expected(*(FinalRoot + Pair.Value));
		ASSERT_THAT(IsTrue(Manager.RequestGameplayTag(Pair.Key.GetTagName()).GetTagName() == Expected));
		const auto* Source = Manager.FindTagSource(Fixture.SourceName);
		ASSERT_THAT(IsTrue(Source->SourceTagList->GameplayTagRedirects.ContainsByPredicate(
			[&Pair, Expected](const auto& Redirect) { return Redirect.OldTagName == Pair.Key.GetTagName() && Redirect.NewTagName == Expected; })));
	}
}

TEST(HierarchyRenameRejectsConflictingDestinationOrMixedSourceWithoutPartialWrites, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture, Other;
	const auto Root = Fixture.Add(TEXT("Infantry"));
	Fixture.Add(TEXT("Infantry.Officer"));
	Fixture.Add(TEXT("Soldier.Officer"));
	auto* BP = Fixture.Ability(Root);
	Fixture.MarkClean();
	const FString Path = Fixture.Root / Fixture.SourceName.ToString();
	FString Before, After;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Before, *Path)));
	const auto Conflict = SeinAutoTag::RenameAssetTag(BP, FName(*(Fixture.TagRoot + TEXT(".Soldier"))));
	ASSERT_THAT(IsFalse(Conflict.WasUpdated()));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(Before, After));
	IGameplayTagsEditorModule::Get().AddNewGameplayTagToINI(Fixture.TagRoot + TEXT(".Infantry.Other"),
		TEXT("Auto-generated by SeinARTS."), Other.SourceName);
	const auto Mixed = SeinAutoTag::RenameAssetTag(BP, FName(*(Fixture.TagRoot + TEXT(".Veteran"))));
	ASSERT_THAT(IsFalse(Mixed.WasUpdated()));
	ASSERT_THAT(IsFalse(Mixed.Detail.IsEmpty()));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(Before, After));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == Root));
}

TEST(HierarchyRenameRetainsExternallyAddedUnrelatedDefinition, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Root = Fixture.Add(TEXT("Infantry"));
	Fixture.Add(TEXT("Infantry.Officer"));
	auto* BP = Fixture.Ability(Root);
	Fixture.MarkClean();
	const FString Path = Fixture.Root / Fixture.SourceName.ToString();
	FString External, After;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(External, *Path)));
	External += TEXT("\nGameplayTagList=(Tag=\"") + Fixture.TagRoot
		+ TEXT(".ExternallyAdded\",DevComment=\"Manual external entry\")\n");
	ASSERT_THAT(IsTrue(FFileHelper::SaveStringToFile(External, *Path)));
	const auto Result = SeinAutoTag::RenameAssetTag(BP, FName(*(Fixture.TagRoot + TEXT(".Soldier"))));
	ASSERT_THAT(IsFalse(Result.WasUpdated()));
	ASSERT_THAT(IsTrue(Result.Detail.ToString().Contains(TEXT("outside this editor"))));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(External, After));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == Root));
}

TEST(RepeatedHierarchyRenameFailureRestoresDictionaryAliasesAndLoadedIdentity, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Original = Fixture.Add(TEXT("Infantry"));
	const auto OriginalChild = Fixture.Add(TEXT("Infantry.Officer"));
	auto* BP = Fixture.Ability(Original);
	auto* ChildBP = Fixture.Ability(OriginalChild, TEXT("SA_Officer"));
	Fixture.MarkClean();
	const auto First = SeinAutoTag::RenameAssetTag(BP, FName(*(Fixture.TagRoot + TEXT(".Soldier"))));
	ASSERT_THAT(IsTrue(First.WasUpdated()));
	Fixture.MarkClean();
	const auto ChildBefore = CastChecked<USeinAbility>(ChildBP->GeneratedClass->GetDefaultObject())->AbilityTag;
	const FString Path = Fixture.Root / Fixture.SourceName.ToString();
	FString Before, After;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Before, *Path)));
	const auto Failed = SeinAutoTag::RenameAssetTagWithRefreshFailureForAutomation(BP, FName(*(Fixture.TagRoot + TEXT(".Veteran"))));
	ASSERT_THAT(IsFalse(Failed.WasUpdated()));
	ASSERT_THAT(IsTrue(Failed.Detail.ToString().Contains(TEXT("lookups were restored"))));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(Before, After));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == First.DerivedTag));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(ChildBP->GeneratedClass->GetDefaultObject())->AbilityTag == ChildBefore));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Original.GetTagName()) == First.DerivedTag));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(OriginalChild.GetTagName()) == ChildBefore));
}

TEST(GeneratedTagCleanupRetainsSourceEditedOutsideEditor, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	const auto Unused = Fixture.Add(TEXT("Unused"));
	const FString Path = Fixture.Root / Fixture.SourceName.ToString();
	FString Before, After;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Before, *Path)));
	Before += TEXT("\nGameplayTagList=(Tag=\"") + Fixture.TagRoot + TEXT(".External\",DevComment=\"Authored outside editor\")\n");
	ASSERT_THAT(IsTrue(FFileHelper::SaveStringToFile(Before, *Path)));
	const auto Receipt = SeinTagAudit::CleanupForAutomation(Fixture.SourceName, {Unused.GetTagName()});
	ASSERT_THAT(IsTrue(Receipt.Contains(TEXT("differs from disk"))));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(Before, After));
}

TEST(ContentBrowserRenameMigratesGeneratedHierarchyDirtyReferencesAndUndo, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	FAssetNameTagSettings Settings(Fixture.TagRoot);
	Fixture.EnableSavedAssets();
	const auto Old = Fixture.Add(TEXT("Ability.Cancel.Production"));
	const auto Child = Fixture.Add(TEXT("Ability.Cancel.Production.Queued"));
	auto* BP = Fixture.Ability(Old, TEXT("SA_Cancel_Production"));
	ASSERT_THAT(IsTrue(Fixture.Save(BP)));
	auto* Table = NewObject<UDataTable>(Fixture.Package(TEXT("References")), TEXT("References"), RF_Public | RF_Standalone | RF_Transactional);
	Fixture.Assets.Add(Table);
	Table->RowStruct = FSeinTagLifecycleTestRow::StaticStruct();
	FSeinTagLifecycleTestRow Row;
	Row.Tag = Old;
	Row.Tags.AddTag(Child);
	Row.Query = FGameplayTagQuery::MakeQuery_MatchTag(Old);
	Row.Map.Add(Old, 21);
	Table->AddRow(TEXT("Row"), Row);
	FAssetRegistryModule::AssetCreated(Table);
	ASSERT_THAT(IsTrue(Fixture.Save(Table)));
	auto* Consumer = Fixture.Ability(Fixture.Add(TEXT("Ability.Consumer")), TEXT("SA_Consumer"));
	auto* Graph = FBlueprintEditorUtils::CreateNewGraph(Consumer, TEXT("MigrationGraph"), UEdGraph::StaticClass(), UEdGraphSchema_K2::StaticClass());
	FBlueprintEditorUtils::AddUbergraphPage(Consumer, Graph);
	auto* Call = NewObject<UK2Node_CallFunction>(Graph);
	Graph->AddNode(Call);
	Call->CreateNewGuid();
	Call->SetFromFunction(USeinAbilityBPFL::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(USeinAbilityBPFL, SeinActivateAbility)));
	Call->AllocateDefaultPins();
	Call->FindPinChecked(TEXT("AbilityTag"))->DefaultValue = TEXT("(TagName=\"") + Old.ToString() + TEXT("\")");
	ASSERT_THAT(IsTrue(Fixture.Save(Consumer)));
	{
		FScopedTransaction Edit(FText::FromString(TEXT("Change unrelated balance value")));
		Table->Modify();
		Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("Rename"))->Map[Old] = 42;
	}
	Table->MarkPackageDirty();
	auto& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>(TEXT("AssetTools")).Get();
	ASSERT_THAT(IsTrue(AssetTools.RenameAssets({FAssetRenameData(TWeakObjectPtr<UObject>(BP), Fixture.SavedMount.LeftChop(1), TEXT("SA_Produce_Cancel"))})));
	Fixture.Packages.AddUnique(BP->GetOutermost());
	Fixture.ExtraFiles.Add(FPackageName::LongPackageNameToFilename(BP->GetOutermost()->GetName(), FPackageName::GetAssetPackageExtension()));
	const FName Expected(*(Fixture.TagRoot + TEXT(".Ability.Produce.Cancel")));
	const auto New = UGameplayTagsManager::Get().RequestGameplayTag(Expected);
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag == New));
	const auto* After = Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("Rename"));
	ASSERT_THAT(IsTrue(After->Tag == New));
	ASSERT_THAT(IsTrue(After->Query.Matches(After->Tags)));
	ASSERT_THAT(IsTrue(Call->FindPinChecked(TEXT("AbilityTag"))->DefaultValue.Contains(New.ToString())));
	FGameplayTagContainer Dictionary;
	UGameplayTagsManager::Get().RequestAllGameplayTags(Dictionary, false);
	ASSERT_THAT(IsFalse(Dictionary.HasTagExact(Old)));
	ASSERT_THAT(IsFalse(Dictionary.HasTagExact(Child)));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Old.GetTagName()) == New));
	ASSERT_THAT(IsTrue(GEditor->UndoTransaction()));
	SeinAutoTag::FinishPendingTagMigrations();
	After = Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("UndoRename"));
	ASSERT_THAT(IsTrue(After->Tag == New));
	ASSERT_THAT(AreEqual(21, After->Map.FindRef(New)));
	// Reclaiming the original asset name must reverse the hierarchy without redirect cycles.
	ASSERT_THAT(IsTrue(AssetTools.RenameAssets({FAssetRenameData(TWeakObjectPtr<UObject>(BP), Fixture.SavedMount.LeftChop(1), TEXT("SA_Cancel_Production"))})));
	Fixture.Packages.AddUnique(BP->GetOutermost());
	SeinAutoTag::FinishPendingTagMigrations();
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag.GetTagName() == Old.GetTagName()));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Expected).GetTagName() == Old.GetTagName()));
	// Reopen real saved Blueprint packages, including a graph consumer compiled by migration.
	ASSERT_THAT(IsTrue(Fixture.Save(BP)));
	ASSERT_THAT(IsTrue(Fixture.Save(Consumer)));
	const FString OwnerPath = BP->GetPathName(), ConsumerPath = Consumer->GetPathName();
	const FString OwnerPackage = BP->GetOutermost()->GetName(), ConsumerPackage = Consumer->GetOutermost()->GetName();
	Fixture.Assets.Remove(BP);
	Fixture.Assets.Remove(Consumer);
	Fixture.Packages.Remove(BP->GetOutermost());
	Fixture.Packages.Remove(Consumer->GetOutermost());
	FText ReloadError;
	const bool bReloaded = UPackageTools::ReloadPackages({BP->GetOutermost(), Consumer->GetOutermost()}, ReloadError, EReloadPackagesInteractionMode::AssumePositive);
	BP = FindObject<UBlueprint>(nullptr, *OwnerPath);
	Consumer = FindObject<UBlueprint>(nullptr, *ConsumerPath);
	if (BP) Fixture.Assets.Add(BP);
	if (Consumer) Fixture.Assets.Add(Consumer);
	if (auto* Package = FindPackage(nullptr, *OwnerPackage)) Fixture.Packages.AddUnique(Package);
	if (auto* Package = FindPackage(nullptr, *ConsumerPackage)) Fixture.Packages.AddUnique(Package);
	ASSERT_THAT(IsTrue(bReloaded));
	ASSERT_THAT(IsNotNull(BP));
	ASSERT_THAT(IsNotNull(Consumer));
	ASSERT_THAT(IsTrue(CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject())->AbilityTag.GetTagName() == Old.GetTagName()));
	ASSERT_THAT(IsTrue(BP->Status != BS_Error && Consumer->Status != BS_Error));
	bool bFoundLiteral = false;
	for (UEdGraph* Page : Consumer->UbergraphPages)
		for (UEdGraphNode* Node : Page->Nodes)
			if (auto* Pin = Node->FindPin(TEXT("AbilityTag"))) bFoundLiteral |= Pin->DefaultValue.Contains(Old.ToString());
	ASSERT_THAT(IsTrue(bFoundLiteral));

}

TEST(ReinitializeAfterResetMigratesRememberedGeneratedIdentity, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	FAssetNameTagSettings Settings(Fixture.TagRoot);
	const auto Old = Fixture.Add(TEXT("Ability.Cancel.Production"));
	auto* BP = Fixture.Ability(Old, TEXT("SA_Produce_Cancel"));
	SeinAutoTag::RememberGeneratedIdentity(BP, Old);
	auto* CDO = CastChecked<USeinAbility>(BP->GeneratedClass->GetDefaultObject());
	CDO->AbilityTag = FGameplayTag();
	CDO->bAutoGeneratedTag = false;
	const auto Result = SeinAutoTag::RegenerateAssetTagDetailed(BP, true);
	ASSERT_THAT(IsTrue(Result.WasUpdated()));
	ASSERT_THAT(IsTrue(CDO->AbilityTag.GetTagName() == FName(*(Fixture.TagRoot + TEXT(".Ability.Produce.Cancel")))));
	FGameplayTagContainer Dictionary;
	UGameplayTagsManager::Get().RequestAllGameplayTags(Dictionary, false);
	ASSERT_THAT(IsFalse(Dictionary.HasTagExact(Old)));
}

TEST(RepairConsolidatesOldGeneratedNameAfterAlreadyReinitialized, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	FAssetNameTagSettings Settings(Fixture.TagRoot);
	const auto Old = Fixture.Add(TEXT("Ability.Cancel.Production"));
	const auto New = Fixture.Add(TEXT("Ability.Produce.Cancel"));
	auto* BP = Fixture.Ability(New, TEXT("SA_Produce_Cancel"));
	const auto Result = SeinAutoTag::ReconcileGeneratedIdentity(BP, Old.GetTagName());
	ASSERT_THAT(IsTrue(Result.WasUpdated()));
	FGameplayTagContainer Dictionary;
	UGameplayTagsManager::Get().RequestAllGameplayTags(Dictionary, false);
	ASSERT_THAT(IsFalse(Dictionary.HasTagExact(Old)));
	ASSERT_THAT(IsTrue(Dictionary.HasTagExact(New)));
	ASSERT_THAT(IsTrue(UGameplayTagsManager::Get().RequestGameplayTag(Old.GetTagName()) == New));
}

TEST(RepairRejectsDistinctMapKeysWithoutChangingDictionary, "SeinARTS.Editor.AutoTag")
{
	FTagSourceFixture Fixture;
	FAssetNameTagSettings Settings(Fixture.TagRoot);
	Fixture.EnableSavedAssets();
	const auto Old = Fixture.Add(TEXT("Ability.Cancel.Production"));
	const auto New = Fixture.Add(TEXT("Ability.Produce.Cancel"));
	auto* BP = Fixture.Ability(New, TEXT("SA_Produce_Cancel"));
	auto* Table = NewObject<UDataTable>(Fixture.Package(TEXT("References")), TEXT("References"), RF_Public | RF_Standalone);
	Fixture.Assets.Add(Table);
	Table->RowStruct = FSeinTagLifecycleTestRow::StaticStruct();
	FSeinTagLifecycleTestRow Row;
	Row.Map.Add(Old, 21);
	Row.Map.Add(New, 42);
	Table->AddRow(TEXT("Row"), Row);
	FAssetRegistryModule::AssetCreated(Table);
	ASSERT_THAT(IsTrue(Fixture.Save(Table)));
	const FString TablePath = Table->GetPathName();
	const FString TableFile = FPackageName::LongPackageNameToFilename(Table->GetOutermost()->GetName(), FPackageName::GetAssetPackageExtension());
	FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry").Get().ScanFilesSynchronous({TableFile}, true);
	Fixture.Assets.Remove(Table);
	Fixture.Packages.Remove(Table->GetOutermost());
	FText UnloadError;
	ASSERT_THAT(IsTrue(UPackageTools::UnloadPackages({Table->GetOutermost()}, UnloadError)));
	const FString Path = Fixture.Root / Fixture.SourceName.ToString();
	FString Before, After;
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(Before, *Path)));
	const auto Result = SeinAutoTag::ReconcileGeneratedIdentity(BP, Old.GetTagName());
	Table = FindObject<UDataTable>(nullptr, *TablePath);
	if (Table) { Fixture.Assets.Add(Table); Fixture.Packages.Add(Table->GetOutermost()); }
	ASSERT_THAT(IsNotNull(Table));
	ASSERT_THAT(IsTrue(Result.IsFailure()));
	ASSERT_THAT(IsTrue(Result.Detail.ToString().Contains(TEXT("distinct map keys"))));
	ASSERT_THAT(IsTrue(FFileHelper::LoadFileToString(After, *Path)));
	ASSERT_THAT(AreEqual(Before, After));
	const auto* Unchanged = Table->FindRow<FSeinTagLifecycleTestRow>(TEXT("Row"), TEXT("Conflict"));
	ASSERT_THAT(AreEqual(21, Unchanged->Map.FindRef(Old)));
	ASSERT_THAT(AreEqual(42, Unchanged->Map.FindRef(New)));
}
